### ISSUE TITLE
peerQuerySpeculative should use a channel for responses

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1018]
when we fanout queries to peers, peerQuerySpeculative waits for all responses, then returns them all to the caller at once.  The caller then iterates over the responses and unmarshals them.

By returning the responses over a channel as they are received we get 2 benefits.

1) faster queries.  Currently, the time taken to process the responses is `(slowest peer response) + (time to unmarshal all data)` .  When using a channel, the process time is `(slowest peer response) + (time to unmarshal slowest peers data)`.  

2) reduced heap size.  As soon as a response from a peer has been processed, the raw []byte can be discarded rather then having to keep hold of it until all peers have responded.  see https://play.golang.org/p/8jBFfKyFPx5 for comparission. with 1MB response sizes from 16 peers, the channel approach has a 40% smaller heap.

**Comment by shanson7** [comment]
Check out this PR: https://github.com/bloomberg/metrictank/pull/36

We have been running this in prod for a month or so. It has helped reduce maybe heap allocation for expensive requests.

FWIW, I think a full solution would marshal directly into the generated type from the response body, without a []byte in between.

**Comment by Dieterbe** [comment]
per above PR this is done for `clusterFindByTag`.
for other codepaths, see #1092
