### ISSUE TITLE
mdm v2 input with org-id = 0 is not working

### ISSUE THREAD

**Issue by deniszh** [grafana/metrictank#1026]
Not sure is it related to metrictank or tsdb-gw.

Setup: tsdb-gw v0.9.0-g72ce022 -> Kafka (0.10.x, 0.11.x, 1.1) -> metrictank 0.9.0-304-g095aaa4

Issue: if tsdb-gw is configured with `v2 = true`, `v2-org = true` and org-id=0 metrictank ignores corresponding v2 (i.e. metricPoint) messages from Kafka, counting them as `unknown`.

Workaround: 
or disable mdm v2: set `v2 = false`
or change org-id to any positive value, e.g. set org-id=1.

**Comment by Dieterbe** [comment]
I *think* the problem might be that we decided in some parts to reject orgid=0 (because if that data comes in, we don't know the difference between set to 0 or unspecified) while in other places allowing it, or even defaulting to it.
see #260
