### ISSUE TITLE
[]Point reuse: everywhere and safer

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1049]
1) other than perhaps some trivial cases, everywhere where we need a `[]Point`, we should pull it out of the pool, rather than allocating anew. 
2) everywhere we're done with a `[]Point`, we should add it to the pool.

We create and discard point slices in a lot of different places throughout the code base. in the `expr` library we do a pretty good job, but there's other places where we don't, e.g. : 
* `getTargetsRemote` currently allocates new AFAICT. 
* ROB.Get() allocates, though typically only small slices. it is emptied again in Server.getSeriesFixed() (and currently not pooled again)
* `divide` in dataprocessor.go (called via Server. getTarget() ) is typically the last stop for its divisor argument, currently we don't send it into the pool

note: for functions such as `divide` it may depend on caller context whether the function can pool slices that it's done with. maybe the caller wants to re-purpose such slices further.  I haven't investigated exhaustively the source tree to see if this is a real or imagined problem, but if it's real maybe we'll make 2 versions of the function, or add a boolean flag to mark whether it's safe to pool input values that aren't reused.

3) because in so many different packages all throughout our codebase we want to pool slices, and repurpose them, i want to make this safer (e.g. don't accidentally reuse slices that have already been pooled). for this reason I propose a type like so:

```
type PointSlice {
values []schema.Point
done
}
```
the done flag is set whenever we add it to the pool. any code that wants to read from a pointslice that has done=true should error.

4) I want to study a bit whether we have large discrepancies in sizes between slices that go in and out of the pool. already mentioned the ROB which typically uses short slices. others may be dependent on whether we're talking about data prio-consolidation or post. it might make sense to use different sizeclasses internally.

note : #958 works on some of this

**Comment by replay** [comment]
is the `done` flag really necessary? i think it should probably be possible to ensure that we don't accidentally reuse pooled slices without having to add an additional boolean and logic to check the boolean. or do you have a specific example where it would be hard to determine whether a slice has been pooled or not?

**Comment by Dieterbe** [comment]
>  i think it should probably be possible to ensure that we don't accidentally reuse pooled slices without having to add an additional boolean and logic to check the boolean

how?

**Comment by replay** [comment]
Hmm that's an old comment, not sure what I had in mind at the time. I think probably I just meant that in those code area which use point slices, it's usually possible to make sure that once a slice has been returned to the pool we keep no reference to it and don't accidentally use it anymore.

**Comment by Dieterbe** [comment]
To expand a bit on my previous suggestion, what I was thinking is a pool that holds `*PointSlice`, which is defined like so:

```
type PointSlice {
values []schema.Point
avail bool              // whether this PointSlice has not been claimed for use
}
```

* upon adding a `*PS` to pool, confirm that `ps.avail` is false and set to true.
* upon retrieving a `*PS` from pool, confirm that `ps.avail` is true and set to false.
* upon usage of a `*PS` (any reads/writes), confirm that `ps.avail` is false.

This way, we can at runtime detect cases where the same PS is being used by multiple users (e.g. a PS was returned to the pool but was still used later on for reads, or the same PS was added to the pool twice)

Issues with this approach:
1) now we have 2 pointers (one to PointSlice, one to underlying array)
2) what we need to pass around to functions etc are `*PointSlice`, not `[]schema.Point`, not sure if we want this concern leaking into functions - and adjusting lots of code.


An alternative approach is inspired by this nice piece of code:
https://github.com/grafana/metrictank/blob/22762285c2da700d500f4ec771680d28dfff68b6/expr/datamap.go#L44-L50

We can keep a map (downside: memory heavy) or a bloom filter (downside: can't remove items, false positives) of all addresses of the last slot of all arrays that are pooled. We can check this list at any time to confirm whether an array has already been claimed or not.

Note also what happens with `append()` doing a reallocate for growth. any time this happens we discard an array that could have been pooled. (a bit of a different from the main topic here though), and also the 2nd approach here cannot detect issues if they're masked by a reallocate.

I think we should only introduce runtime safety checks if we know an elegant way to do it. currently i don't see one.
