### ISSUE TITLE
chunk cache uses excessive heap space

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1058]
observed this in our ops environment with
`metrictank (built with go1.10.3, git hash 0.10.0-16-gd7b6500)`
https://snapshot.raintank.io/dashboard/snapshot/Dv4j5LdTTdyWpNsGKUM0xU7paonUoLSc?orgId=2
(happened to all read instances as far as i can see, but i just picked one)
observations:
* heap usage grows following the exact same pattern as chunk cache. except on a different "scale": chunk cache goes from 0 to about 715MiB, whereas heap grows from 1.28GiB to 4.8GiB(3.52GiB growth), a 5x multiple
* median chunk size ~60B

I have the full profile locally, but here's the most important thing:
```
File: metrictank
Type: inuse_space
Time: Sep 20, 2018 at 12:09pm (EEST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top15
Showing nodes accounting for 3.59GB, 91.62% of 3.92GB total
Dropped 228 nodes (cum <= 0.02GB)
Showing top 15 nodes out of 100
      flat  flat%   sum%        cum   cum%
    1.10GB 27.98% 27.98%     1.10GB 27.98%  github.com/grafana/metrictank/vendor/github.com/gocql/gocql.copyBytes
    0.66GB 16.86% 44.84%     0.66GB 16.86%  github.com/grafana/metrictank/mdata/cache.(*CCacheMetric).AddRange
    0.27GB  6.83% 51.67%     0.27GB  6.83%  container/list.(*List).insertValue (inline)
    0.23GB  5.86% 57.53%     0.50GB 12.69%  github.com/grafana/metrictank/mdata/cache/accnt.(*LRU).touch
    0.21GB  5.44% 62.98%     0.22GB  5.59%  github.com/grafana/metrictank/idx/memory.(*MemoryIdx).add
    0.21GB  5.41% 68.39%     0.21GB  5.41%  github.com/grafana/metrictank/mdata/cache/accnt.(*FlatAccnt).addRange
    0.19GB  4.83% 73.21%     0.23GB  5.84%  github.com/grafana/metrictank/mdata.NewAggMetric
    0.17GB  4.45% 77.66%     0.88GB 22.56%  github.com/grafana/metrictank/mdata/cache/accnt.(*FlatAccnt).eventLoop
    0.15GB  3.77% 81.43%     0.15GB  3.77%  github.com/grafana/metrictank/mdata/chunk.New
    0.12GB  2.94% 84.37%     0.12GB  2.94%  github.com/grafana/metrictank/vendor/github.com/dgryski/go-tsz.(*bstream).writeByte
    0.09GB  2.32% 86.69%     0.09GB  2.32%  github.com/grafana/metrictank/vendor/github.com/dgryski/go-tsz.(*bstream).writeBit
    0.07GB  1.71% 88.41%     0.07GB  1.71%  bytes.makeSlice
    0.05GB  1.31% 89.72%     0.05GB  1.38%  github.com/grafana/metrictank/vendor/github.com/eapache/go-xerial-snappy.Decode
    0.05GB  1.16% 90.88%     0.05GB  1.16%  bytes.(*Buffer).String (inline)
    0.03GB  0.74% 91.62%     0.03GB  0.74%  github.com/grafana/metrictank/mdata/cache.(*CCacheMetric).Add
```

**Comment by Dieterbe** [comment]
here's the profile and a goroutine dump (one possible explanation might be that some request goroutines stay running instead of ending, holding open references to chunks?)
[Uploading stuff.zip…]()

**Comment by tehlers320** [comment]
0.9.0-322
https://snapshot.raintank.io/dashboard/snapshot/MFQR2Fkuy7y5cUqx1G6vOHOyqHIBY4Rz 

only read/query nodes behave like this. write nodes are always fine.

**Comment by Dieterbe** [comment]
thanks for sharing @tehlers320 
on your snapshot it's harder to correlate because you also had growth of the amount of points stored in the process. but likely the same thing is going on.

the good news is that we have a good profile, a goroutine dump and the dashboard.
everything needed to get to the bottom of this.
