### ISSUE TITLE
batch pruning, and maybe further pruning tweaks?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1066]
a bit of backstory...
we discovered that one of our prod clusters was spending too much time pruning, and blocking render requests, so we implemented #1062 , locking more granularly (once for each metric to be pruned rather than one lock for all of them). this fixed the latency to get a lock on the index, and thus the latency of render requests during pruning.
However, it also impacted throughput on the index. after deploying it, we saw that during pruning, ingestion would slowdown, and the kafka input would develop a backlog, making read nodes non-ready.

 #1065 reduces the rate of pruning, as to lower the impact on available bandwidth on the index, and slowing down ingestion not so much.

one more thing I think we should look into is see if we get better performance by pruning in batches.
e.g. every 50ms worth of prunes via 1 lock instead of 1 lock per metric.

@replay said he also had some other ideas to make #1062 better, so i'ld like to hear your thoughts

**Comment by woodsaj** [comment]
I dont think this will lead to a significant improvement.  The overhead of acquiring the lock is small compared to amount of processing to delete a single series from the index.

I think the biggest improvement will come from partitioning the index up using concurrentMaps or just having an index per partition.

**Comment by Dieterbe** [comment]
>  The overhead of acquiring the lock is small compared to amount of processing to delete a single series from the index

how do you know this for sure? i'm not sure if mutex operations are well represented in cpu profiles, since AFAIK part of the time spent is sleeping, not execution. a go trace would shed more light on this.
but I do know that we saw ingestion performance drop significantly once we switched to lock-per-series.

**Comment by woodsaj** [comment]
it takes microseconds to acquire a lock and milliseconds (at least on the problematic instances we are dealing with) to delete a metric.

When we had 1 lock held for the entire time needed to delete all series the process was still really slow and only deleted at rate of about 50 series/second.
