### ISSUE TITLE
Consolidator "MaximumConsolidator" not configured error

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1067]
when consolidateBy() is used in a query an error is returned if rollup data is needed and the consolidation function specified is not configured for a series.

Instead of error'ing, MT should just use the default aggregation defined for the series.

**Comment by Dieterbe** [comment]
huh? you're saying that if a user explicitly asks for a given consolidation, but the data isn't there to support it, instead of telling the user we can't fulfill the request, we should silently use differently consolidated data ?

**Comment by woodsaj** [comment]
yes.  especially given that we are overloading "consolidateBy" to mean both runtime consolidation and also selecting the rollup to use.

I find it irritating when i zoom out on a dashboard and many of the panels suddenly fail

**Comment by shanson7** [comment]
We've seen this happen to many dashboards. Users that build a dashboard with a short, real-time frame in mind end up getting broken (or wrong!) dashboards when someone zooms out. 

Silently switching to the default seems dangerous as well however...

IMO, it is very complicated to build dashboards while keeping in mind pre-aggregation (rollups, series alignment) and post-aggregation (runtime consolidation), since functions used in between can change the desired behavior. Also, functions that are nested into other functions (as in grafana's reference syntax, e.g. #A) can be very hard to rationalize about without being able to pin down a rollup configuration. I discussed this with @DanCech on slack a bit.

I think this is a more complicated subject that would be difficult to solve with the existing graphite language.

**Comment by woodsaj** [comment]
As @shanson7 points out, handling rollup selection correctly cant be done using only consolidateBy. 
Because graphite only has 1 aggregation for rollups, consolidateBy is only used for runtime consolidation which is always the last step before returning data. Because it is the last step in the processing pipeline, only 1 consolidateBy setting can be used per target.

The simple example that illustrates the problem is getting the difference between min and max consolidation of a single series.  You might think you can just do
```
diffSeries(consolidateBy(some.metric, 'max''), consolidateBy(some.metric, 'min'))
```
but that doesnt work.  Internally graphite will run `diffSeries(some.metric, some.metric)` then consolidate the result by either min or max (i am not sure whether the first or last seen consolidateBy is used, i suspect it is the last) if the number of points being returned is > maxDatapoints..

I think the solution to the problem is to add a new Function in MT (and graphite if it is being used in front of MT).   Something like `withRollup(some.metric, 'max')`  we can then more correctly handle the consolidation/rollup selection.   I havent fully thought this through, there may be giant holes in the idea.

But in spite of all of that, the intent of this issue is to make MT compatible  with Graphite's broken behaviour right now.

For our prod deployments we now typically only store sum and avg rollups.   Experience has shown us that customers dont care about rollups and aggregation (other SaaS metrics companies typically only offer avg rollups).  Avg is **good enough** for everything except counts, which is why we also store 'sum'.

So for our use case, if rollup data is being used we always want to use avg, unless consolidateBy('sum') is explicitly requested.  If a customer requests consolidateBy('max') on 1hour averages; we know that the returned data is not going to be 100% accurate. But it will be good enough.

**Comment by DanCech** [comment]
A simple solution for MT may be to support a rollup selection syntax in the series selector, so the user can specify `some.series--sum` or similar for those specific scenarios.

**Comment by woodsaj** [comment]
The issue raised here is about the fact that currently, Metrictank is behaving in a way that is not Graphite compatible.    I want to get this bug fixed.   

Properly handling rollup selection is a bigger feature request and outside the scope of this issue.

So, to fix this issue we just need to make MT graphite compatible. which means that using any valid ConsolidateBy() should not result in an error.

There are 2 approaches to fix this:
1) Like graphite we use consolidateBy() only for runtime consolidation after all functions have been executed. and just always use the default consolidation for rollups.
2) we treat the consolidateBy() as a `hint`  for rollup selection.  Based on the `hint` we select the most appropriate rollup to use.

option "1" seems like a step backwards and prevents non-default rollups from every being queried.  
option "2" ensures that we return the most accurate results given the data we have. 

The way i see the hints working is :
- if consolidateBy() is not passed, we use the default aggregation for rollups (same as we do today)
- if consolidateBy() is set, then we find the best match from the available aggregations

| requested | order of preference |
| -- | -- |
| avg | avg, last, max, min, sum |
|min | min, last, avg, max, sum |
|max | max, last, avg, min, sum|
|sum | sum, last, avg, max, min|
|last | last, avg, max, min, sum|

This would just require a simple change to:
https://github.com/grafana/metrictank/blob/0.10.1/api/graphite.go#L692-L703
to add:

```
if consReq == 0 {
    ...
} else {
    fn := closestAggMethod(consReq, mdata.Aggregations.Get(archive.AggId).AggregationMethod)
    cons = consolidation.Consolidator(fn)
}
```
```
func closestAggMethod(consolidation.Consolidator, []aggregations.Method) consolidation.Consolidator {
 // return best match
}
```

**Comment by DanCech** [comment]
The problem with #2 is that graphite-web does not pass `consolidateBy` in requests to cluster hosts, so with the proxy deployment model MT will not be aware of any `consolidateBy` in the query.

**Comment by woodsaj** [comment]
> The problem with 2 is that graphite-web does not pass consolidateBy

Yes, but that is a separate issue.  

Right now we have to proxy all requests to graphite first because MT returns errors for requests that should work.   If we fix the issue with "2" we can start handling most queries in MT directly without proxying.    

This leads to the issue of query results being inconsistent based on whether they are proxied or not.  Minor changes to a query, like adding aliasByMetric() which is not yet implemented in MT, would force the query to be proxied and the rollup selection could change.

So while we wont be totally solving the problem, implemimenting 2 is a big improvement from where we are now.

**Comment by woodsaj** [comment]
I also think we can address the consolidateBy not being passed through to graphite by putting it into a header that we configure graphite to forward.   We proxy a request to graphite when there is one or more functions requested that MT doesnt support.  So the proxying happens after we have parsed the query.  So when we proxy we already have access to any consolidateBy() funcs used and can then populate a header.
