### ISSUE TITLE
Prune index in Cassandra

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1069]
We currently keep adding entries to the index in Cassandra and never prune them. At startup MT needs to load all of that data and filter it by the LastUpdated property to ignore the ones that have not been updated for a certain amount of time, but this makes the startup slower and slower because it needs to filter more data.
We should delete index entries from Cassandra once they have reached a certain age. That pruning age should probably be higher than when we prune them from the memory index, because we want to keep the ability to just adjust the memory pruning settings and restart MT to restore index entries that have already been pruned from memory.
If a user decides to send a metric again, and hence "activates" it again in the cassandra/memory indices, the historic data will still be available just like it is now.

The simplest solution for that would probably be a simple go routine that occasionally loads all the data from the cassandra index and deletes all the entries that haven't been updated for a certain time.

**Comment by deniszh** [comment]
I'm very 👍 for this ticket. Old metrics are bloating used memory on cluster restarts and potentially hazardous to overall cluster stability (e.g. after long period cluster will go OOM during restart).

**Comment by replay** [comment]
@deniszh have you observed a case where MT OOMed before it became ready, because it was loading so much index data? AFAIK that's a scenario that we have not seen ourselves (yet). I think it might be relatively easy to solve this specific problem by simply filtering the data from the index while it is being loaded, instead of first loading and then filtering it.

**Comment by shanson7** [comment]
@replay - As another datapoint, we see a decent amount of memory used just loading in the cassandra data (even before indexing), but much less than when we actually start consuming the backlog.

> I think it might be relatively easy to solve this specific problem by simply filtering the data from the index while it is being loaded, instead of first loading and then filtering it.

This might not be as easy as you think, since the reason that the data is all loaded in first is to join series that may differ by only interval changes.

**Comment by deniszh** [comment]
@replay 
> have you observed a case where MT OOMed before it became ready, because it was loading so much index data?

Not yet, but I definitely notice increased memory consumption right after cluster restart, and - if metrics are never cleaning up - what will stop index to grow indefinitely and consume more and more memory? E.g. after 1 month we have 500K metric in tank, and 2M in the index, so,  in 2 month it will be 4M, in 3 - 6M etc.

> I think it might be relatively easy to solve this specific problem by simply filtering the data from the index while it is being loaded, instead of first loading and then filtering it.

Yes, I was also thinking of a similar solution. Not sure what @shanson7 means in "series differ by only interval changes",  though...

**Comment by shanson7** [comment]
@deniszh 

> what will stop index to grow indefinitely and consume more and more memory?

While all of the metric definitions for a given set of partitions are pulled in on start up, they will not all be indexed. That is controlled by the `MT_CASSANDRA_IDX_MAX_STALE` setting (ours is set to `720h`. That means that it really is just a start up cost. Most of our instances are at around 4M in the index, and about a 10GB heap to load in all of those metric definitions. 

One this we did do, however, is set a TTL on our `metric_idx` table. I think this is the cheapest solution to the "forever growing" problem.

**Comment by shanson7** [comment]
No, it also uses [when loading the initial index](https://github.com/grafana/metrictank/blob/master/idx/cassandra/cassandra.go#L364).

It will read in all of the old data, but will not index anything older than maxStale (except in the interval change scenario).

**Comment by deniszh** [comment]
Ah, I totally misread the whole issue then, sorry.  🤦‍♂️ Indeed, it's filtering during load index, so, it's just a matter of startup time.
Well, separate "disk prune" parameter for separate prune routine will be enough IMO.

**Comment by deniszh** [comment]
I'm wondering now does I have working prune setting at all... `idx.cassandra.prune.values.count32` is still 0 in my case...

**Comment by shanson7** [comment]
You might be hitting the same issue I did. `30d` didn't work for us, we needed `720h`

**Comment by deniszh** [comment]
Wow, that's interesting! Thanks, @shanson7, will check.

**Comment by replay** [comment]
unfortunately that variable appears to rely on `ParseDuration`, `d` is not a valid unit: https://golang.org/pkg/time/#ParseDuration

**Comment by deniszh** [comment]
Wow, that's very sneaky, indeed! Thanks for help!

**Comment by deniszh** [comment]
As I'm not only one who was hitten by that pesky duration, it's provably better to at least mention that in example config, or even log warning or something. Will create separate issue for that.

**Comment by deniszh** [comment]
Ah, missed #944

**Comment by shanson7** [comment]
This issue inspired me to do a little research into our cluster. It takes our instances 15-20 minutes (!!) to load in all the metadata from cassandra. I wrote a tool that mimics the cassandra idx and does the same logic to keep series that have an interval change from a live series.

The result is that `60%` of our data is staler than `90d`, and we only use `30d` for the memory idx stale time. So, pruning cassandra could drastically speed up our start up (not to mention, reduce the memory cost)

**Comment by Dieterbe** [comment]
> It takes our instances 15-20 minutes (!!)

I'm seeing the same with our largest cloud instances. 
obviously this is something we will address, but it will take at least another few months I think.
