### ISSUE TITLE
Delete endpoint does not update the tag index

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1081]
The delete endpoint removes metrics from the main index based on their path, but it does not update the tag index if these metrics have tags. This should be fixed. I don't think it needs to be in the scope of this issue to allow the user to delete by tag, but when a user deletes a tagged metric by name then the tag index needs to be udpated accordingly.

**Comment by woodsaj** [comment]
There is already a `/tags/delSeries` call that should be used if the user wants to delete tag based series.
Though it is undocumented and looks to be incomplete.  The call just takes a list of path expressions in the format "<seriesName>;<key=value>[;<key=value>]".  But i think we need a delete call that uses tagQuery expressions. ie, `name=~foo.* , dc=dc1`

Perhaps we could just add an additional query param to "/metrics/delete" to indicate that the query is a tag query expression.

**Comment by Dieterbe** [comment]
#1023

**Comment by replay** [comment]
Currently `/metrics/delete` accepts one parameter `query` which is a single string. If we want to support deleting queries by tag expressions we need to be able to accept a list of strings. It would be possibleto make the `query` parameter accept tagQuery expressions separated by `;`, but that seems quite inconsistent with other tag query endpoints. So I think we should modify `/metrics/delete` and add another parameter to it called `expr` (same as to find series), this parameter accepts a list of tag query expressions. If none or both parameters are specified (`expr` / `query`) then an error gets returned, because only one of them is allowed to be used. In the request handler we'll then query the series by the criteria and delete the result set from both indices.

**Comment by Dieterbe** [comment]
dup of #1023

**Comment by Dieterbe** [comment]
why do we suddenly care so much for deleting by tag expressions? is there a need for this?

**Comment by replay** [comment]
Eldin brought it up a few times because there's a customer who wants to use it. AFAIK that's all, i believe it's quite an edge case that it is used because most users never delete and not that many users use tags, this will  only be important for users that combine those two.

**Comment by Dieterbe** [comment]
ok feel free to either rename this ticket then (and reopen) or create a new one
