### ISSUE TITLE
inaccurate tracking of total memory used by chunk cache

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1086]
We currently only track and report on the size of the actual data being stored in the chunk cache, but not the overhead. This has been brought up before in #963. I propose we track an approximation of the overhead used by the chunk cache and flat accounting.

My initial thoughts were to ignore flat accounting, but it will grow as the cache grows, so I think we should track it as well. This is important to give more realistic indicators of memory usage to allow for better planning and monitoring. I would like to clarify that all of the suggested numbers below are in addition to what we are already counting (the size of the data).

I think we should add the following for overhead for the cache:

- 24 bytes per metricCache map entry in ccache (excluding the *CCacheMetric)
- 24 bytes per metricRawKey map entry in ccache (excluding the map[schema.Archive]struct{})
- 52 bytes per *CCacheChunk map entry in ccache_metric(48 for *CacheChunk, at least 4 per map key)
- 84+ bytes per *CCacheMetric (80 for struct, numChunks * 4 for []key values)

And the following for flat accounting:

- 24 bytes per metrics map entry in flat_accnt (exluding the *FlatAccntMet)
- 16+ bytes per *FlatAccntMet map entry in flat_accnt ( (numChunks * 4) + (numChunks * 8) )

And lastly for the LRU:

- 28 bytes per EvictTarget

Due to the heavy use of maps I believe these numbers will still be smaller than what is actually being used, but I think that is outside the scope of this issue.

I believe that all of these accounting changes can be implemented inside flat_accnt. The logic for when an item is added or removed is already there. All we need to do is add the stats and adjust the numbers.

Open to ideas and discussion.

**Comment by DanCech** [comment]
Seems reasonable

**Comment by woodsaj** [comment]
This seems like a lot of overhead.  Across all of our clusters the average chunk size over the last 24hours was 317Bytes.
