### ISSUE TITLE
streaming processing and series limiting on other cluster calls

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1092]
#1021 introduced streaming processing and series limiting for `clusterFindByTag`

`findSeries` (which does a similar thing but for non-tagged queries) should get the same changes.

we should probably also switch these to stream processing:
clusterTagDetails, clusterTags, clusterAutoCompleteTags, clusterAutoCompleteTagValues

 @shanson7 @woodsaj not sure if my memory is failing me, but i just realized spec-exec is implented for all the above calls, but not for actually getting data (`getTargets`). what's the reasoning for this? have we discussed this before? seems we should also switch this over to `peerQuerySpeculativeChan`

**Comment by Dieterbe** [comment]
eventually we should be able to delete `peerQuerySpeculative` and just use `peerQuerySpeculativeChan`

**Comment by shanson7** [comment]
I believe the reason we don't do speculative execution for `getTargets` is that those requests target a subset of peers (just the ones that had matching series) and each peer gets a different request

**Comment by woodsaj** [comment]
I think #1104 is relevant to this discussion
