### ISSUE TITLE
auto downsizing of chunk cache?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1094]
currently, our chunk cache will grow and never evict until max size is reached.
this means if users don't query many different chunks, chunks will accumulate in the cache that rarely get queried. having a high hit rate is good, but not at the cost of wasting memory.

to this end i wonder if perhaps we should automatically shrink and grow the cache size (up to the configured max size) based on how many evictions happen.
something like:

* no evictions in >= X hours or evicted data hasn't been accessed in >= Y hours -> shrink cache
* evictions of recently used data -> grow cache again

**Comment by Dieterbe** [comment]
this is basically the poor man's version of applying max-age on chunks (which would require tracking more metadata)

**Comment by robert-milan** [comment]
I like the idea. It mimics some of the behavior of an LFU but without the per metric overhead of tracking each chunk.

If there aren't any evictions for a given period of time and we decide to shrink the cache by evicting from the end of the list, how many do we evict? Is it based on the size of the LRU, the cache, or something else?

Will there be user-configurable settings for this?
- the ability to turn this on or off
- the time period before chunks will automatically be evicted
- number of chunks to evict during automatic eviction

**Comment by Dieterbe** [comment]
ability to toggle behavior on/off shouldn't be needed. if one needs that, it's a sign our heuristic or implementation isn't good and needs fixing.

as for the criteria, this needs some research into what makes sense for our cache implementation
