### ISSUE TITLE
followup after  Refactor how chunks are persisted. #95 

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#110]
I don't understand the new benchmarks @ https://github.com/raintank/raintank-metric/pull/95/files
normally in each iteration upto b.N a new comparable load should be added, so that go test can repeatedly call the function with an increasing b.N and converge on a timing number per "operation" or workload.
but here the operation is adding a worker queue, with all the workload outside of the loop.

see also http://dave.cheney.net/2013/06/30/how-to-write-benchmarks-in-go

**Comment by woodsaj** [comment]
yeah there have been a lot of changes since these benches were written.  When they were written they were designed to show linear growth in ns/op and B/op as the number of series grew.

I work on rewriting them.
