### ISSUE TITLE
standardize tag naming: key vs name vs tag

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1102]
we use `key` in a bunch of places throughout the index. and sometimes we call it "tag" and sometimes "name", which is quite confusing!
I think we should make tag mean "a=b" where a is a key or name and b is the value. but we should try to refrain from calling `a` here a tag.

just one of the examples: these lines of code are together in the code, one of them uses key, the other name, but they are the same thing.
```
type TagIndex map[string]TagValue // key -> list of values

func (t *TagIndex) addTagId(name, value string, id schema.MKey) {
```

we definitely use `key` in some places to refer to the series identifiers.

is graphite strongly opinionated about any of this?

**Comment by Dieterbe** [comment]
then what is `tag1=value1` ? looking at https://graphite.readthedocs.io/en/latest/tags.html and https://github.com/graphite-project/carbon/blob/7246aeff75826d66473ec818354386275c79c610/lib/carbon/util.py seems this is also called a "tag"

**Comment by DanCech** [comment]
There isn't really a good name for that, the map of tag=value pairs is commonly referred to as the series' "tags", but I haven't really had a need to refer to a single tag=value pair as a unit (that I can recall).

**Comment by Dieterbe** [comment]
well in the code it is a named thing as it is something that needs to be parsed out.
it's also hard to write a proper specification without distinctly naming this thing.

**Comment by DanCech** [comment]
The least-contortionist approach may be to refer to `name=value` as a "tag pair", `name` as a "tag name" (or "tag"), and `value` as a "tag value".

**Comment by DanCech** [comment]
I wouldn't use the term tagspec in this context, as that is already used to refer to tag matching specifications on the query side eg https://github.com/graphite-project/graphite-web/blob/master/webapp/graphite/tags/base.py#L19
