### ISSUE TITLE
cluster peers should send chunks directly

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1104]
currently, `getTargetsRemote` queries  "/getdata" on peers, which return msgp encoded `models.Series[]`

the getdata handler calls getTargetsLocal which calls getTarget. at a quick glance, this seems to get chunks from a bunch of places (cache, AggMetrics) and also points (from the ROB), calls Fix, divide (if it's an aggregegated avg), and generates the Series structures.

we speculate it may perform better for peers to just send back the raw chunks, and the requester than iterates over them, does the consolidation etc. this may put more load on the query nodes, but we plan to add separate query mode anyway.

**Comment by shanson7** [comment]
While evaluating replacing our cassandra store with something more performant, we see that the msgp encoding, gzip and http writes take a considerable amount of time for large responses. As an example:

getTargetsLocal runtime takes 106ms to fetch ~130k chunks (mostly from cache, some from store). Then there is *something* happening for another 1.35s before the `HTTP POST getdata` span completes (in local dev, this seems to be a lot of time in gzip and HTTP write). Looking at the msgp encoder for the response, "Datapoints" is particularly verbose. Each element has:

map header for 2 elements (1 byte), "Val" (4 bytes), 8 byte float, "Ts" (3 bytes), 4 byte uint for a total of 20 bytes per datapoint.

As it mentioned here, sending the encoded chunk in this space would have a huge savings for large requests.

**Comment by shanson7** [comment]
This is one that we still talk about off github. I have a feeling this would be a big win.

**Comment by shanson7** [comment]
I have some spare cycles and am interested in tackling this one. I think that this needs some discussion on how it should be implemented. The current workflow is something like:

1. query with 1 or more targets goes to initial node Q (maybe dedicated query node, maybe read node)
1. Node Q will fan out the resolve series requests to at least 1 node in each shard group.
1. Node Q will determine which archive should be fetched and optionally which consolidation to run (if normalization is needed).
1. Fans out the requests again. Read nodes will perform any consolidation/normalization required beyond what exists in storage.
1. Read nodes will also "trim" extra data off of the ends if the chunks go beyond the requested `from`/`to`

This change could maintain all of this behavior, but change the encoding that is returned to the query nodes to be more efficient. 

Or, it could push most of the work that the read nodes do onto the query node and the read nodes would only be responsible for fetching the chunks from storage.

Thoughts?

**Comment by shanson7** [comment]
There are some challenges to simply returning the raw chunks and leaving normalization/alignment/Averaging to the query nodes. 

In [getSeriesFixed](https://github.com/grafana/metrictank/blob/ae2200b999856549e8c3f5314ce2fabc4839ca7d/api/dataprocessor.go#L414) we call [newRequestContext](https://github.com/grafana/metrictank/blob/ae2200b999856549e8c3f5314ce2fabc4839ca7d/api/dataprocessor.go#L697) which adjusts the from/to based on the required normalization. 

If we want to move this logic into the query node, it could need to be done at a higher level and planned ahead of the request. Or it could remain where it is and the AggNum/OutInterval could still be sent as part of the request.

**Comment by shanson7** [comment]
So, benchmarking the "easy" way (read nodes do all the same work as today, but encode the data in the more compact form) on machines with fast network shows that the overhead of re-encoding gorilla and decoding on the query node side was too high and effectively nullified the benefit in terms of request latency. The query node allocation rate was reduced though.

I expect the "full" solution of read nodes simply fetching and returning chunks and query nodes doing normalization / averaging would be superior. However, that is a larger project that I don't have the bandwidth for at the moment.

**Comment by Dieterbe** [comment]
> However, that is a larger project that I don't have the bandwidth for at the moment.

Same for us at Grafana Labs :'(
