### ISSUE TITLE
index-rules.conf based pruning for bigtable

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1108]
#924 was rebased on master but I forgot to apply the new mechanism to the bigtable idx plugin

**Comment by woodsaj** [comment]
@Dieterbe i idont think any changes are needed.  The indexrules are loaded and handled by the memory-idx plugin, which both cassandra-idx and bigtable-idx use.

I dont see any changes in #924 made to the cassandra idx plugin

**Comment by woodsaj** [comment]
never mind, had another look and there are clearly changes needed.
