### ISSUE TITLE
kafka offset tracking should run in separate goroutine to consumer

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1113]
https://github.com/grafana/metrictank/blob/master/input/kafkamdm/kafkamdm.go#L312-L326

If consuming a message blocks (eg due to the index being locked or writeQueue is full), then we dont consume from the ticker until after we become unblocked.   This can leave us with long periods with no insight into how far behind an MT node is falling behind.

**Comment by Dieterbe** [comment]
and vice versa. if `k.tryGetOffset` is slow, it blocks ingestion.

I have some WIP code to address this but changing this is a minor conflict with #1022

**Comment by woodsaj** [comment]
removing the offsetMgr already introduce conflicts.  adding a few more wont hurt.
