### ISSUE TITLE
allow users to get metricDefs from MT index

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1115]
there is a `GET /index/get?id=123.abc12345abc1234abc` but it returns a msgpack endcoded def which is not user friendly. 

So we need to either:
- add a new api method that returns json
- add support for a `format` param to be passed
- honour the `Accept` request header and respond with an accepted content type.  eg the following request should return a json response or a `406 Not Acceptable` error.
```
curl -H "Accept: application/json" "http://localhost:6060/index/get?id=1234.abcde123123abcd"
```
- create a cli tool for querying this api method and then print the response as json

There are a number of these internal cluster api methods that are useful for debugging and we should provide a user friendly way to interact with all of them.

My preferences for this are
- honour the `accept` header and support msgpack and json responses.
- cli api tool.

I suspect that the a cli api tool is probably going to be the least amount of work.

**Comment by tehlers320** [comment]
You could use https://github.com/tagomoris/msgpack-inspect to decode the msgpack. It can even convert a msgpack to json.

**Comment by woodsaj** [comment]
> when you say users, do you mean operators?
yes

> what are uses cases for a user or operator having a def id

`There are a number of these internal cluster api methods that are useful for debugging`
I am often needing to get a metricDef based by id. the common reasons are
- To get metricDef details for MetricPoint payloads retrieved with mt-kafka-mdm-sniff-out-of-order
- to compare metricDef details in memory  with those in cassandra
- once we start logging the metricId's, deal with cassandraIdx write issues

> which they can do with mt-index-cat

Gives you what is in Cassandra, not what is in the in-memory index.

**Comment by Dieterbe** [comment]
interestingly I don't think `/index/get` is used anymore by metrictank itself.

If you sniffed an MKey off kafka, you know the partition, which means you can target the right MT instance.
I have a use case today where a customer is having issue with the rendering of a series. Metrictank can tell me the name but not the MKey or partition. Thanks to #1526 it's now trivial to compute the MKey for a series.
I now would like to target `/index/get` to get info from the live index, but don't know which partition it lives on. So i need to query across all shards. A few ideas:
1) call `/cluster` to get all peer addresses in a script around the proposed tool, call tool repeatedly
2) same, but have tool take care of this
3) have the tool join the gossip cluster as some kind of observer role, similar to query pods.

I don't like the idea of 3, as it may interfere with the functioning of the cluster. The tool should remain as isolated as possible.


for simplicitly, going with 1 now.

**Comment by woodsaj** [comment]
Would it not be simpler to just add a 'format' option for /metrics/find that returns the full metricdefs (or series name + id)

**Comment by woodsaj** [comment]
To be clear i am suggesting simply adding a new format to https://github.com/grafana/metrictank/blob/master/api/graphite.go#L332

eg
```
	case "metrictank":
		response.Write(ctx, response.NewJson(200, nodes, request.Jsonp))
```

**Comment by Dieterbe** [comment]
we could do that for either or both of the "find" and "get" methods, and we could do it for the internal /index api as well as the user facing (with fan-out) api. and it's probably fairly easy in all cases

it really depends on what you have (an MKey or a name/pattern) and whether you want to query against a single node or across the cluster.

however, i have no more need for this right now. so i won't work on this now.
