### ISSUE TITLE
btStore: unable to apply writes to bigtable. rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8976801 vs. 4194304)

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1118]
how to reproduce:
* launch docker-dev-bigtable stack
* `fakemetrics feed --mpo 20000 --carbon-addr localhost:2003`

MT will log errors like:
```
metrictank_1   | 2018-10-26 12:25:13.015 [ERROR] btStore: unable to apply writes to bigtable. rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8976801 vs. 4194304)
metrictank_1   | 2018-10-26 12:25:13.204 [ERROR] btStore: unable to apply writes to bigtable. rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8830070 vs. 4194304)
metrictank_1   | 2018-10-26 12:25:13.204 [WARNING] btStore: Failed to write 1940 chunks to bigtable. they will be retried. rpc error: code = ResourceExhausted desc = grpc: received message larger than max (8830070 vs. 4194304)
metrictank_1   | 2018-10-26 12:25:13.206 [ERROR] btStore: unable to apply writes to bigtable. rpc error: code = ResourceExhausted desc = grpc: received message larger than max (9068544 vs. 4194304)
```

when i try a smaller volume with fakemetrics, I think the issue disappears

**Comment by woodsaj** [comment]
I think this is just an issue with the bigtable emulator.  Real Bigtable instances allow payloads up to 100MB
https://github.com/GoogleCloudPlatform/google-cloud-go/blob/master/bigtable/bigtable.go#L74

So if the 4MB is the grpc default, and seems reasonable the emulator would use that.

The simple solution to this is to just reduce "MT_BIGTABLE_STORE_WRITE_MAX_FLUSH_SIZE"  from the default 10000, to 1000

**Comment by Dieterbe** [comment]
> Live Bigtable instances accept up to 100MB and this is what the bigtable client library is configured to use

**Comment by Dieterbe** [comment]
last week it seemed that didn't quite fix it, but retrying today it does seem to fix it. went up to 100kHz and 300kHz and seems to work fine with the patch applied.
