### ISSUE TITLE
partitioning metrics by nameWithTags (aka shard by tag)

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1123]
we currently support partitioning series with 
- byOrgId
- bySeries

bySeries uses just the series `name` field.  For tag based series there could be 100s of 1000s of series with the same name.  This could lead to the split between partitions being unbalanced.

Ideally, bySeries would just use nameWithTags, but this would break existing deployments that are already using tags.  So instead we need to add a new partitioning scheme, eg `bySeriesWithTags`

**Comment by robert-milan** [comment]
Closed by #1427
