### ISSUE TITLE
protecting against bit rot

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#113]
http://www.circonus.com/underneath-clean-data-avoiding-rot/

we will run into cases where data corrupts, we should anticipate for it.
if we're going to use ZFS, we need machines with ECC (and probably solaris/illumos)

for comparison influxdb uses crc checksums in their data chunks, but i'm not sure it lets them repair faulty chunks, bypass bad sectors etc.

**Comment by Dieterbe** [comment]
or does cassandra help with this? then we should be able to rely on ECC and tcp checksums to provide reliable data into our metric tank instances

**Comment by woodsaj** [comment]
I dont think that adding checksums will provide any real benefit.   Having the checksums will allow you to detect when chunks are corrupt, but you cant do anything to repair the chunk

handling bitrot in cassandra is a separate issue that is completely independent to metric-tank
