### ISSUE TITLE
Bug in idx metrics_active tracking

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1132]
I expect that there is a bug in the tracking of active metrics. We recently enabled more aggressive pruning (max-stale = `3d`) on our write instances and it seems that every prune brings them closer to zero, to the point that over time there is an underflow and the `idx.metrics_active.gauge32` value jumps to 4 billion. It seems that somehow prune is overestimating how much it is removing. Perhaps it would be simpler to `Set` the gauge to the be `len(defById)` in prune (and maybe some other places?) instead of trying to track the delta?

**Comment by Dieterbe** [comment]
> Perhaps it would be simpler to Set the gauge to the be len(defById) in prune (and maybe some other places?) instead of trying to track the delta?

that's a good point.
