### ISSUE TITLE
scaleToSeconds should set the consolidation to `average`

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1135]
Similar to other normalization functions (e.g. `summarize`) the default consolidation should be set to `avg` for `scaleToSeconds` to prevent issues with runtime consolidation.

**Comment by shanson7** [comment]
I don't think graphite does this and I'm no longer convinced it is a good idea. Hidden behaviors are complicated to rationalize about and debug.

**Comment by Dieterbe** [comment]
i've been thinking of a similar argument, e.g. for queries like `summarize(foo,..."sum")` : should we set the fetch consolidator to "sum" (if available) ? I like to think so. These are the kinds of smoother experiences I'ld like to provide, but it's not compatible with graphite does things..
