### ISSUE TITLE
add whisper import support for bigtable store

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1162]
The mt-whisper-importer only works with cassandra backends.    We need to update it to work with bigtable as well.

Currently, the importer writes directly to cassandra using its own insert statements.  To future proof the importing we should add "BulkImport" methods to the `Store` interface and move the importer logic into the various store implementations.

**Comment by replay** [comment]
That's not directly related to this issue, but since you're talking about "future proofing":
Should we also add support for whisper stores that contain tagged metrics? At the moment, if a graphite installation uses tags, we won't be able to import the metrics.

**Comment by replay** [comment]
Update:
The MT PR has been merged, the related HM-API PR is still waiting for review: https://github.com/raintank/hosted-metrics-api/pull/235

**Comment by Dieterbe** [comment]
#1291
