### ISSUE TITLE
Kafka alternative

### ISSUE THREAD

**Issue by biancalana** [grafana/metrictank#1174]
Hi @Dieterbe 

  As discussed in 3106f885b6de11c52db4ade05b6d626abfb060c8, NSQ has been discontinued and now there isn't any official alternative to kafka. An option could be [NATS](https://nats.io/).

From NATS website: 

> "NATS Server is a simple, high performance open source messaging system for cloud native applications, IoT messaging, and microservices architectures."

 As you said, MT currently requires data to be in-order and partitioned. In order to achieve that there is [NATS Streaming Server](https://nats.io/documentation/streaming/nats-streaming-intro/) that implements *almost* everything, the partition side needs to be done at client (metric publisher side) NATS Streaming implements subject channel and durable subscriptions that make this possible.

**Comment by Dieterbe** [comment]
do you have a preference for NATS? if so, how strong? also, anything you can tell us about your experience with nats or nats streaming server?

**Comment by biancalana** [comment]
We are building our observability platform using [nats-streaming](https://github.com/nats-io/nats-streaming-server) as the transport layer for metrics and logs events. We have made that choice based on nats scalability and easy administration.

Definitively nats has a LOTS less features than Kafka, such as: topic partitions, ksql, etc. But don't you think that having an easier alternative to kafka would improve metrictank's adoption?

We have build event collectors, processors and publishers around nats and everything is working great, the main issue is having a metrictank cluster. Currently we have ~300 msgs/s on nats-streaming.
For now is acceptable for us to have two metrictank instances receiving the same metrics and having those metrics on cassandra two times in case of one metrictank instance failure. 

But I think that it would be a lot easier to have metrictank ingesting the metrics directly from nats-streaming and also using nats as transport and synchronization layer.

**Comment by Dieterbe** [comment]
> But don't you think that having an easier alternative to kafka would improve metrictank's adoption?

Yes.  But we need to put some more thought into this.  This NATS based stack, is it open source? I'm trying to gauge how popular nats is for this sort of application.

**Comment by tehlers320** [comment]
Nats is part of Knative which I think is a great idea. It's an attempt to standardize the k8 tools to stop vendor lock in from something like say Kinesis (that's how I see it). I've been looking at Knative allot the past 2 weeks and would love to push this over using vendor offerings.  Would love to hear how nats scales. I'm sitting at 1.5m msg per second, are there good benchmarks out there somewhere? Is there a cost benefit over Kafka for instance?

**Comment by deniszh** [comment]
With all respect, with AWS choosing Kafka instead of own Kinesis means that Kafka pretty much wins over any other queue in popularity.
But NATS probably can be a good option for other use cases, though. If it's a part of Knative now - it's a good move.

**Comment by woodsaj** [comment]
> an easier alternative to kafka

From my brief review of Nats Streaming server, it is not any simpler to use/operate compared with Kafka.

I do think that Nats support could be a good thing.  But the Metrictank team at GrafanaLabs don't have any experience with it, so it is not something that we can drive at this time.

**Comment by tehlers320** [comment]
> With all respect, but when AWS choose Kafka instead of own Kinesis means that Kafka pretty much wins over any other "queue technology" by popularity.
It cost 2x as much to run the hosted Kafka rather than run your ec2 versions of the same spec. I'm not sure if it was a "win" rather a way to expand their Profits. 2x is an awful lot for just hosting the same thing on EC2 with some automation tagged on it.

> But NATS probably can be a good option for other use cases, though. If it's a part of Knative now - it's a good move.
I misread the doc, it is "suggested" for persistence with knative. Either kafka for NATs

Per the Knative docs
`This allows message delivery in a cluster to vary based on requirements, so that some events might be handled by an in-memory implementation while others would be persisted using Kafka or NATS Streaming.`

It is in the incubator though, so it could become very popular very quickly.
https://landscape.cncf.io/

**Comment by fkaleo** [comment]
Another interesting option: Pulsar
https://medium.com/@anuradha.neo/kafka-is-not-the-best-anymore-meet-pulsar-9eb435c9fc0b
