### ISSUE TITLE
reorderBuffer.interval is not set correctly

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1196]
the reorderBuffer is created with `NewReorderBuffer(reorderWindow, ret.SecondsPerPoint)`.  where `ret` is a `conf.Retention`.   Unlike in graphite, the default storageSchemas dont explicitly set the secodsPerPoint of every series. Instead, we map retention policies to a range of metric intervals.  We then use the "interval" property sent with each MetricData payload.  

With a default config, the secondsPerPoint is set to "1s" and this is what is being passed when creating the reorderBuffer.

**Comment by Dieterbe** [comment]
@woodsaj i polished up mauro's PR above. what do you think?

**Comment by Dieterbe** [comment]
per awoods:

> the rob is always (with our default retention policy) being configured with an interval of 1s.  So, the re-order buffer size needs to be set to the number of seconds that you want to be able to reorder points in, not the number of points.
When the rob is created, it allocates a slice to fit all of the entries, but only end up putting data points into a few slots.  Eg with an interval of 10s, and a rob of 30.   We get a slice that holds 30points, but we only ever put 3 in it. (30/10).
>
> with this change, a rob of 30, would still use the same amount of memory, but would support re-ording points for 5minutes (if they have a 10s interval)
