### ISSUE TITLE
memory leak & unable to get stack trace

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1197]
https://ops.grafana.net/dashboard/snapshot/JTTwVj7u6NjDzTpP9XDHhoGEt2lt5yvi?orgId=1
sorry, not available to the public, but basically it shows a few cycles of chunk cache growing to levels of 100, 82, 80 utilization%, and resetting to near-zero again. only for the first reset, is there some eviction.
for each spike, used is 3.5 to 4.4GB and total used (incl all overhead) 6.1 to 8GB
throughout all of this, there's a consistently high hit rate (!)
also, as these cycles happen, memory changes from 10.8GB heap (22RSS) to 21.7 heap / 31.2RSS

[heap.zip](https://github.com/grafana/metrictank/files/2718151/heap.zip) (0.10.1-91-g8512071)

furthermore what's interesting is when I try to run `curl -q 'http://localhost:6060/debug/pprof/goroutine?debug=2'` (even if i cancel after 15s), the instance seems to block and kubernetes acts like so `Killing container with id docker://metrictank:Container failed liveness probe.. Container will be killed and recreated`

**Comment by replay** [comment]
To me this looks like they OOMed. I tried to find the pod, but unfortunately it doesn't seem to exist anymore.

**Comment by Dieterbe** [comment]
true.
here's a zoomed in version on one of the "resets"
https://snapshot.raintank.io/dashboard/snapshot/hdgl7ccA39dhZo6lXlD4Pi8cTKOE2Xx7?orgId=2
this also shows that briefly the cache hit rate drops but restores in about 2 minutes. implying the cache will mostly fill with stuff we don't need, confirming we need #1094 but that's a separate conversation.

**Comment by Dieterbe** [comment]
d'oh. you're right. looking at the request stats, those were cache deletes. my bad.
so this is then simply another instance of what we already have other tickets for (mem leak + chunk cache seems to have overhead)
as far as the problematic stackdump getting, #1198 will help with that.
