### ISSUE TITLE
use different metrics counts for out-of-order and dupliate timestamps

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1202]
currently, we discard points and increment `tank.metrics_too_old` when a point's timestamp is <= lastTs for the same series.

However, it is beneficial to be able to differentiate between old data being sent and duplicate data being sent.

I propose that we add a new metric `tank.duplicate_ts` so we can maintain separate counts of duplicates vs out-of-order.

see also #1201

**Comment by fkaleo** [comment]
Given discussion in #1201, I suggest we call it `tank.discarded.new_value_for_timestamp` instead of `tank.duplicate_ts`
