### ISSUE TITLE
Characters supported in tag values

### ISSUE THREAD

**Issue by qqbb18** [grafana/metrictank#1216]
We would like to gain more insight into what printable ASCII characters (32-126) are supported in **tag values** on Grafana/MetricTank.
Currently, our system only directly supports a limited character set: a-zA-Z0-9-_./%, and blocks other characters (or only allows other special characters via encoding them into HEX format).  However, the tag values in the timeseries data into our system might contain substantially more characters than this list.  Therefore we plan to support additional ASCII characters in tag values, given that they will not cause issues to any existing Grafana/MetricTank functionality, such as query, computation, etc.  We have conducted some basic tests on MetricTank and Grafana by putting each character to different positions of a tag value: leading, trailing and somewhere in the middle.  After combining the test results with other limitations, we have an initial proposal for the characters supported by our system, which is listed below:

  0 - 9 allow everywhere in a tag value 
a - z allow everywhere in a tag value 
A - Z allow everywhere in a tag value  
  ! # % & - / : < = > @ _ . allow everywhere in a tag value  
(space) ~ allow only in the middle of a tag value

; Always block in a tag value because this is not supported by MetricTank
 ' Always block in a tag value because this is causes request error (unexpected character) when used on Grafana
 " $ ( ) * + , ? [ ] \ ^ ` { } | Always block in a tag value because they might cause ambiguity when used in regex queries

  Please kindly provide suggestions/comments if you feel any of this is not accurate. Moreover, in order to better understand the restrictions on tag values, we would like to confirm with you on the officially supported list of characters. If possible, please provide brief explanations on why a character is not supported. Finally, it is probably worth adding a regression test for this so we can confidently extend the character set that we plan to support in the future. Thanks!

This issue has also been posted to Grafana:
https://github.com/grafana/grafana/issues/15261

**Comment by Dieterbe** [comment]
we should probably align with Graphite on this...

**Comment by replay** [comment]
I forgot to mention that actually a tag value could start with `~`, but then it's going to be hard to query it because `=~` is the regular expression operator

**Comment by qqbb18** [comment]
@replay This was exactly what I have found from my tests: the only character not accepted by MT is **;**. Thanks for adding a unit test to include all the characters mentioned above! I totally agree that it is tricky to figure out how to test with regex queries.

However I found there are cases some other characters do not work well with Grafana, for example, **'**, this always gives request error "unexpected character", but this might be a Grafana/Graphite issue ...

**Comment by replay** [comment]
The issue with `'` in the middle of the value is probably related to how Grafana submits the query to Graphite. May I ask why it is necessary for you to use such characters in tag values?

**Comment by shalstea** [comment]
We aren't asking for it per se.  We are suggesting that you document and test what you support/don't support.  We would love to have all the characters supported but realize that, that isn't feasible.

For us we are sourcing tag values from systems we don't control (hardware device info, etc).  They can have any character, if we don't support them directly then we have to encode the values in some way.

**Comment by replay** [comment]
As an update to the Graphite (and MT is Graphite compatible) documentation, we got the character support documented in the official docs now: https://github.com/graphite-project/graphite-web/pull/2426

**Comment by Dieterbe** [comment]
@replay status of this?

**Comment by replay** [comment]
On Metrictank side i think this can be considered done with the merging of the following PRs:
https://github.com/grafana/metrictank/pull/1371
https://github.com/grafana/metrictank/pull/1348
https://github.com/raintank/schema/pull/28

In Graphite & Carbon there are still related changes which have not been merged yet, but that doesn't really concern this issue: 
https://github.com/graphite-project/graphite-web/pull/2458
https://github.com/graphite-project/carbon/pull/858

**Comment by robert-milan** [comment]
> On Metrictank side i think this can be considered done with the merging of the following PRs:
> #1371
> #1348
> [raintank/schema#28](https://github.com/raintank/schema/pull/28)
> 

^^ Those are all merged

> In Graphite & Carbon there are still related changes which have not been merged yet, but that doesn't really concern this issue:
> [graphite-project/graphite-web#2458](https://github.com/graphite-project/graphite-web/pull/2458)
> [graphite-project/carbon#858](https://github.com/graphite-project/carbon/pull/858)

There are ongoing discussions and work related to the graphite-project changes.

**Comment by shalstea** [comment]
Can this be closed ?

**Comment by replay** [comment]
I'm waiting for the two PRs in the graphite-project to be closed. let me ping the involved people about those
