### ISSUE TITLE
Pruning sometimes takes too long

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1224]
We have customer instances where index pruning can take up to 1.5 days. We should aim to get that under 3h, because 3h is usually our pruning interval, otherwise they'll overlap. 

One idea would be to parallelize the pruning:
As we need to acquire an index lock anyway, which means not much else happens during the pruning, we could execute at least certain parts of the pruning process in multiple parallel threads (f.e. iterating over all MDs to select the ones to prune could be done in a bunch of threads, those that need to get pruned would then get pushed into a channel which is consumed by another thread which just prunes all the MDs it receives from that chan).

**Comment by Dieterbe** [comment]
> otherwise they'll overlap.

a long-running prune will cause the next one to be skipped
