### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by wolfman2g1** [grafana/metrictank#1226]
I get 401 on unauthorized when trying to fetch a metric from graphite.

` metrictank[25150]: [Macaron] 2019-03-02 06:23:43: Started POST /render/ for 10.2.194.27
Mar  2 06:23:43  metrictank[25150]: [Macaron] #033[4;31m2019-03-02 06:23:43: Completed /render/ 401 Unauthorized in 157.892µs#033[0m
`
I've tried graphite 1.x, carbonapi and the graphite-mt docker container all have the same result. If I change multi-tenancy to false i get a 503 error. 
**OS**
Centos 7.4

**metrictank Version **
metrictank-0.11.0-1.x86_64

**cassandra Version**
3.11
**kafka**
10.x

**Comment by Dieterbe** [comment]
is there any more logs? can you increase the log verbosity?

**Comment by wolfman2g1** [comment]
Not sure if this is the correct way to do this. However, I was able to get everything to function by setting orgid to 1 and disabling multi-tenancy.
