### ISSUE TITLE
We should have a tool to prune the persistent storage index

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1229]
At the moment metrics accumulate without any limit in cassandra/bigtable. In use cases where there is a lot of churn this makes the index grow a lot, which slows down the startup time. It should be easy to write a tool that moves all the metrics older than X into some alternative archive-table.

**Comment by replay** [comment]
The tool should do the following:

Iterate over all present partitions and load the defs of each partition, then iterate over the defs.
For each def it has to decide whether the def should be archived or not (moved into an archive table). Metrics should be archived if all defs with the given def's NameWithTags() have a LastUpdate that is stale according to the definition in index-rules.conf, so a temporary map of NameWithTags()->def needs to be built.

Running the tool will look more or less like this:
```
mt-index-prune --no-dry-run --index-rules /etc/metrictank/index-rules.conf cass hosts cassandra:9042
```

**Comment by Dieterbe** [comment]
dup of #1069 
i suggest to close this issue and resume this topic there.

**Comment by replay** [comment]
closing this in favor of #1069
