### ISSUE TITLE
deletes in cluster with some NonReady nodes, result in 503

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1249]
i was on a cluster that was in the middle of a deployment (some new NonReady nodes gossiping with existing Ready nodes)
i wanted to delete some metrics, some i ran this command on a node
(the node was in ready state, not sure if that was even needed)
```
curl -v -H 'X-Org-Id: 17303' http://localhost:6060/metrics/delete -d query="foo"
```
this resulted in
```
< HTTP/1.1 503 Service Unavailable
< Content-Type: text/plain
< Vary: Origin
< Date: Thu, 21 Mar 2019 11:38:25 GMT
< Content-Length: 23
< 
* Connection #0 to host localhost left intact
503 Service Unavailable/ # 
```
in the logs I saw:
```
[Macaron] 2019-03-21 11:26:38: Started POST /metrics/delete for [::1]
2019-03-21 11:26:38.594 [ERROR] HTTP metricDelete error querying mt-read03-17303-large-foobarbaz-a-7899cd865-r448z/index/delete: "503 Service Unavailable"
[Macaron] 2019-03-21 11:26:38: Completed /metrics/delete 503 Service Unavailable in 4.381486ms
```

the mentioned node was clearly in NonReady state, judging from `kubectl get po` output as well as looking at `/cluster` on the node that I was on.

it looks like the delete worked, but due to fanning out to all members in the cluster specifically NonReady nodes, there will be 503 responses (due to the NodeReady middleware), and a 503 response is returned to the user.
this is a confusing experience

I do think it's a good thing to involve all peers, but perhaps we shouldn't count their 503's if we know they're not ready.

**Comment by replay** [comment]
To make it a less confusing user experience, we could easily group and count the peer responses and show them to the caller. So the response that you'd get to your request would be something like:

```
14 - success
2 - failure (503)
```

**Comment by woodsaj** [comment]
The way to properly handle this is to make delete calls asynchronous and have them placed in a queue that all nodes can consume from.
We could use Kafka for these types of messages, or we could build it directly into metrictank using Raft or similar.

In general, we need to take a step back and design how deletes should work within a cluster.  Deletes failing due to non-ready nodes is not the only issue that leads to inconsistent results when deleting.  Another major issue is that if a node restarts shortly after a delete, it will re-create the index entries when the backlog is replayed.

**Comment by replay** [comment]
If we have this kind of queue to consume deletes from, then I think we should also use it for the meta record adds/updates/deletes. Currently those would also require all MTs to be up, which is not optimal

**Comment by Dieterbe** [comment]
If MT only supported kafka ingest, then putting these delete messages in kafka (even into the same kafka topic as for metrics) seems to make a lot of sense. we would get synchronization between the metrics stream and the delete calls for free.
But MT currently also supports carbon and Prometheus ingestion. We could choose to deprecate Prometheus without too much backlash, but that still leaves carbon.
For carbon (and for Prometheus) the current api calls are good enough because there is no old data to be replayed.
So the question becomes, do we want to maintain 2 different ways of deleting data or adopt a single, but complicated, new approach.

raft would enable us to solve it for all ingestion plugins. from what i remember how raft works, we'd need to assure we always have sufficient nodes online to keep the "transaction log" online, though realistically we're already at that point of wanting a sufficient amount of cluster peers online at all times anyway, but currently even if all nodes are down, restarting them brings up a cluster with a consistent view. this wouldn't be true when we do deletes via raft.
likely we'll want to adopt raft in the future anyway to manage partition distribution across peers, so it may make sense.

OTOH we already have the clustered api calls for non-kafka plugins, and we can just say that each queued input plugin (kafka, and in the future kinesis or whatever) needs to support not only being a data transport, but also transport delete commands. this seems fairly trivial to implement. note that we'd want to publish these to all partitions of a topic.
