### ISSUE TITLE
Implementation of sub-second or millisecond resolution of metrics

### ISSUE THREAD

**Issue by mlin2** [grafana/metrictank#1258]
Hi Everyone,

we have a use case that requires us to save metrics 100 times per second. Unfortunately, the graphite ecosystem including Metrictank don't allow us to save our metrics for frequencies of more often than once per second.

How much time would it cost to implement that?

We have two proposals:
* Implement the storage in Metrictank based on Milliseconds since 1970 everywhere.
* Accept strings as values in Metrictank so we can simply save a string of 100 values for each second

Could you please tell us what you think about the proposals and if you have any plans of implementing this? Further, how long would it take to implement something like that? What are the required steps?

Kind regards

**Comment by Dieterbe** [comment]
It's something that would be a nice to have, but has never been important enough for us to dedicate resources to. (most people want >1s intervals such as 15s to 60s to reduce cost, and it's sufficient for the devops use case, BI etc)
Changing this early choice would be a quite impactful change. The assumption of the per second basis is reflected in much of the code.

**Comment by Dieterbe** [comment]
Can you describe your use case?

**Comment by mlin2** [comment]
Ideally we'd like to have a Metrictank to be able to store an array of 100 time-series datapoints every second because we need more resolution in the metric to recognise the pattern of change via data analytics.

We like Metrictank a lot because it handles Cassandra for us so our other services don't have to touch Cassandra.

**Comment by Dieterbe** [comment]
Ok but what kind of data is it ? Application monitoring ? Performance engineering ? Systems monitoring ?

**Comment by mlin2** [comment]
I'd say it's systems monitoring. But why is that relevant? I think the functionality we're searching for is still the same. It looks like one alternative would be to use Graphite vanilla + https://github.com/criteo/biggraphite and send Graphite Events. 
What do you think?

**Comment by deniszh** [comment]
IIRC Biggraphite does not support Graphite events.

**Comment by Dieterbe** [comment]
what's the overall volume of this? total amount of points per second? graphite events is not built for high throughput.

**Comment by mlin2** [comment]
The volume would be very high. it can be easily 200 nodes sending in 100 points per second.
So 20000 points per second?

**Comment by Dieterbe** [comment]
and how many metrics does each node send?

**Comment by mlin2** [comment]
only one for now. could be up to 30

**Comment by Dieterbe** [comment]
Well, sorry, we don't plan to support this case anytime soon cause it's just not common enough.
I can also tell you that Graphite events is not built for this kind of use case.
