### ISSUE TITLE
Interacting with kafka from docker host fails resolving 'kafka'

### ISSUE THREAD

**Issue by fkaleo** [grafana/metrictank#1286]
When trying to collect or receive data from the kafka instance spun up with any of the docker stacks provided in metrictank, it fails to resolve the hostname.

In metrictank do:
```
cd docker/docker-dev-custom-cfg-kafka && docker-compose up
```

Then:
```
florian@tiki ~> kafkacat -C -b localhost:9092 -t mdm
% ERROR: Local: Host resolution failure: kafka:9092/0: Failed to resolve 'kafka:9092': Name or service not known
```

```
fakemetrics feed --kafka-mdm-addr localhost:9092 
2019/04/16 13:31:32 [I] starting listener on :6764
params: metricname=some.id.of.a.metric, orgs=1, mpo=10, period=1, flush=1000, offset=0, speedup=1, stopAtNow=false
per org:         each 1s, flushing 10 metrics so rate of 10 Hz. (10 total unique series)
times    1 orgs: each 1s, flushing 10 metrics so rate of 10 Hz. (10 total unique series)
2019-04-16 13:31:33.903778578 +0200 CEST m=+1.003364697 10 metrics could not be sent as v2 MetricPoint
ERRO[0002] ProducerError 0/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 1/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 2/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 3/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 4/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 5/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 6/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 7/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 8/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
ERRO[0002] ProducerError 9/10: kafka: Failed to produce message to topic mdm: dial tcp: lookup kafka: no such host 
2019/04/16 13:31:34 [log.go:209 writerMsg()] [E] kafka: Failed to deliver 10 messages.
```

**Comment by fkaleo** [comment]
First workaround people use is adding ```127.0.1.1       kafka``` to ```/etc/hosts```

**Comment by Dieterbe** [comment]
> First workaround people use is adding 127.0.1.1 kafka to /etc/hosts

ohh.. apparently i have done this on my laptop.. probably years ago because i forgot about it :)

> A better solution would probably be to modify the ADVERTISED_HOST environment variable set in the docker compose files.

sounds good!

**Comment by woodsaj** [comment]
docker handles the DNS resolution.  The hostname will only resolve from within a container in the same docker network.

docker-compose creates a user-defined network for the containers to share based on the directory name where the docker-compose file is.  eg for the docker-dev-custom-cfg-kafka stack the network is called 'dockerdevcustomcfgkafka_default'

for more details refer to the docs. https://docs.docker.com/v17.09/engine/userguide/networking/configure-dns/

**Comment by woodsaj** [comment]
Kafka and cassandra require hostnames, as they both advertise the address that clients should connect to.  When you connect via localhost, the client then queries the node for the list of peers in the cluster.  Future interactions with the service are then done via the peer addresses.  For kafka the peer address is "kafka" and for cassandra it is "cassandra"

**Comment by fkaleo** [comment]
> > First workaround people use is adding 127.0.1.1 kafka to /etc/hosts
> 
> ohh.. apparently i have done this on my laptop.. probably years ago because i forgot about it :)
> 
> > A better solution would probably be to modify the ADVERTISED_HOST environment variable set in the docker compose files.
> 
> sounds good!

Actually changing ADVERTISED_HOST does not do any good.

**Comment by fkaleo** [comment]
Ok, so the proper solution would be to have the kakfa configuration option `advertised.listeners` in kafka's `server.properties` set to:
`PLAINTEXT://kafka:9092,PLAINTEXT://localhost:9092`

Our kafka docker image currently only does not allow that.
See https://github.com/raintank/raintank-docker/tree/master/docker/kafka

The most used kafka Docker image (`wurstmeister/kafka`) accepts the environment variable `KAFKA_ADVERTISED_LISTENERS` to be set.
See https://hub.docker.com/r/wurstmeister/kafka/

For more information on `advertised.listeners`, see:
https://kafka.apache.org/documentation/#configuration
https://rmoff.net/2018/08/02/kafka-listeners-explained/

**Comment by mariomac** [comment]
Confirmed. With:
```
KAFKA_LISTENERS: INT://kafka:9092,EXT://0.0.0.0:9093
KAFKA_ADVERTISED_LISTENERS: INT://kafka:9092,EXT://localhost:9093
```
I can interact from outside the containers via `localhost:9093` and from inside other containers via `kafka:9092`.

Example. With `kafkacat` tool,  I run inside a container:
```
# kafkacat -b kafka:9092 -t my_topic -P
pim pam trucu trucu
```
And If I run from the host:
```
^C~ $ kafkacat -b localhost:9093 -t my_topic -C
% Reached end of topic my_topic [0] at offset 0
pim pam trucu trucu
% Reached end of topic my_topic [0] at offset 1
```
