### ISSUE TITLE
/metrics/delete on query nodes: nilpointer in `api.(*Server).metricsDeleteLocal`

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1293]
saw this using v0.11.0-259-g4c92934
```
[Macaron] 2019-04-25 13:25:18: Started POST /metrics/delete for 62.228.1.72
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xb261ca]

goroutine 704 [running]:
github.com/grafana/metrictank/api.(*Server).metricsDeleteLocal(0xc00086e0c0, 0xc000001a3b, 0xc0004bca46, 0x17, 0x0, 0xc000068f70, 0x6aaf75)
        /go/src/github.com/grafana/metrictank/api/graphite.go:589 +0x2a
github.com/grafana/metrictank/api.(*Server).metricsDelete.func1(0xc00086e0c0, 0xc0004d0d40, 0xc0004bca46, 0x17, 0xc000144910, 0xc000474f00, 0xc000148a30)
        /go/src/github.com/grafana/metrictank/api/graphite.go:527 +0x69
created by github.com/grafana/metrictank/api.(*Server).metricsDelete
        /go/src/github.com/grafana/metrictank/api/graphite.go:526 +0x3ec
```

```
func (s *Server) metricsDeleteLocal(orgId uint32, query string) (int, error) {
        defs, err := s.MetricIndex.Delete(orgId, query)
        return len(defs), err
}
```
we need add nil checks on `s.MetricIndex` for query nodes, here and probably elsewhere too

**Comment by woodsaj** [comment]
Instead of a nil check, should we just have the metricsDelete call only fan out requests to peers that have data?  ie `node.Mode != ModeQuery`

**Comment by Dieterbe** [comment]
We should do the latter but it's not sufficient.

1) /metrics/delete queries may be issued against query nodes (in fact that's how we have it deployed and what caused this issue today)
2) for whatever reason, /index/foo requests may be (accidentally or otherwise, e.g. a query node starting with the ip:port of a previous data node, or other routing issues) issued on query nodes so we should add a safeguard on those too.
