### ISSUE TITLE
add 'ingest_after' flag to metrictank

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1296]
Currently metrictank has a "drop-first-chunk" flag.  This was intended to support upgrades and fail-over scenarios where we wanted a MT instance to replay the kafka backlog but not write any partial chunks to the backend store.   However this flag also prevents the first chunk for any new series from being persisted.

A more reliable approach is to add a flag to MT to have it discard all datapoints that are before a specific time (which would typically just be the next major chunk boundary).   This will ensure that the first datapoint received for each series will be the first datapoint of that chunk.

The idea is that an MT instance would start up and start consuming from kafka. Each datapoint would be decoded and idx.AddOrUpdate() still called to update the index, but if the TS of the datapoint is before the "ingest_after" timestamp, we would then just drop the datapoint with no further processing.

This feature is needed to support our "instance migration" project to give us support for 
- Resizing instances, ie changing the number of kafka partitions
- changing the partitioning schema of instances, ie migrate instances to use the new partitionBySeriesNameWithTags 
- cluster migrations
- backend store migrations
- etc...

**Comment by fkaleo** [comment]
Implemented by PR #1382
