### ISSUE TITLE
add api endpoint to add metricDefs to the index 

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1297]
There are a few scenarios where we need to be able to add metricDefinitions to the in-memory and cassandra/bigtable index without ingesting any datapoints.
eg.
- to revive series that have been archived.
- to support instance/cluster migrations where data is being migrated from a one index table to another.

Historically we have just migrated the index in the backend store then initiated a restart of all MT nodes so they reload the index.  For large instances this can be time consuming.

To support this capability we should add a simple API endpoint that MetricDefinitions (or batches) can be posted to.  MT will then take the MetricDefs and add them to the in-memory index and to the backend index store.

**Comment by Dieterbe** [comment]
> to support instance/cluster migrations where data is being migrated from a one index table to another.

can you clarify this a bit. not sure what a "one index table" means?

**Comment by woodsaj** [comment]
> to support instance/cluster migrations where data is being migrated from a one index table to another.

Index entries are persisted in a table in cassandra or bigtable.  When re-partitioning we need to create a new table (same schema) and copy the index entries to it.   You can't safely do in-place updates of all index entries in the one table.

Historically, we have:
- created a new "temporary" table
- copy the index entries to it assigning the new partition IDs.
- create a backup the original table
- truncate the original table
- copy the contents of the temporary table to the original table.
- restart MT nodes

However, it would be easier and more fault tolerant to just create a new "permanent" table. so the process would become:
- created a new "metric_idxN" table, where N is incremented for each new table version.
- copied the index entries to it assigning the new partition IDs.
- update MT configs to use new table name, causing a rolling deployment.  Or just deploy new MT cluster using new metric_idx table name.
