### ISSUE TITLE
docker-dev fails to start when MT is compiled on Mac

### ISSUE THREAD

**Issue by DeleurApps** [grafana/metrictank#1298]
When trying to compile Metrictank on Mac via the `make` command, the compilation is successful, but the docker image fails to start.

Steps to recreate:
1. `cd $GOPATH/github.com/grafana/metrictank`
2. `make`
3. `cd docker/docker-dev`
4. `docker-compose up`

Expected error:
```metrictank_1   | /usr/bin/metrictank: line 4: syntax error: unexpected end of file (expecting ")")```

Quick Fix:
By adding flags before the compilation and running the build script directly, the issue gets resolved. Seems like Metrictank is automatically being compiled with wrong architecture:
`GOOS=linux GOARCH=amd64 ./scripts/build.sh`

**Comment by Dieterbe** [comment]
@fitzoh ^ FYI
