### ISSUE TITLE
improve kafka-mdm lag measurements

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#1302]
Right now we determine lag as the time it would take to drain the queue.  This time is calculated based on the current rate of ingestion and is not very accurate.

Kafka messages (since kafka 0.10.0) include a timestamp of when the message was created.
https://godoc.org/github.com/Shopify/sarama#ConsumerMessage

We should just use that as the lag measurement.

**Comment by Dieterbe** [comment]
pro: allows us to remove all the laglogger/lagmonitor stuff.
con: makes it critical that wallclocks are always in sync.

i'm a bit hesitant to rely on wallclocks for something this critical TBH. if the clock of tsdbgw (or whichever other producer) is ahead by 10s or more, all MT's would mark themselves as non-ready.

**Comment by Dieterbe** [comment]
for the record, we recently did some refactoring to this code: #1022

**Comment by woodsaj** [comment]
> i'm a bit hesitant to rely on wallclocks for something this critical TBH

Having consistent wall clocks is a necessity for any distributed system. If you cant keep clocks on your servers within 1second of each other, you are going to have lots of problems.

**Comment by Dieterbe** [comment]
as far as i know some systems implement their own abstract clocks (https://en.wikipedia.org/wiki/Vector_clock maybe?) precisely because wallclock is unreliable.

**Comment by woodsaj** [comment]
More complex `abstract` clocks, such as Vector clocks, are for ensuring correct ordering of events. They are of no use for measuring time between events.

We have no need for anything more then NTP synchronised clocks (which has a precision in the order of a few milliseconds when run over the internet)

**Comment by Dieterbe** [comment]
> Right now we determine lag as the time it would take to drain the queue. This time is calculated based on the current rate of ingestion and is not very accurate.

as of #1022 this is no longer true. We're not aware of issues with the lag calculator at this time, so I suggest to close this.
