### ISSUE TITLE
Review HTTP error codes

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1304]
While trying to track down all 5XX errors I see some dashboards that show 

```
"error:"Internal Server Error"
response:"need 1 divisor series, not 0"
```

This seems like it should be a 400. I'm wondering if there are other places where this can happen.

**Comment by Dieterbe** [comment]
I think we did this a while back

**Comment by Dieterbe** [comment]
we've been working the last 2 quarters on reducing our error rates.
during this process we've made good progress on validation and accurate response codes. there's a couple PR's that were merged. this should not be an issue anymore.
