### ISSUE TITLE
should we not call m.findCache.InvalidateFor() when adding new entries in UnpartitionedMemoryIdx.add()

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1305]
https://github.com/grafana/metrictank/blob/b3728f021e9221d0700c480ec6b91b1b9e6f921a/idx/memory/memory.go#L474-L481

why do we skip invalidateFor in this case?

**Comment by woodsaj** [comment]
The findCache caches searches of the tree.  So if nothing is being added to the tree, as is the case here, we dont need to invalidate any cached searches
