### ISSUE TITLE
metrictank should probably handle backfill retry itself

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1314]
i have to type this in a rush. didn't fact check yet, but afaik:
* MT does some heavy initialisation (e.g. loading index)
* MT starts consuming all kafka partitions (backfill)

in case kafka clears a segment and we get a "offset no longer exists" error (even just for 1 partition), MT exits, and we restart it, losing all the work we had already done. we have to reload the index, and reconsume data we had already consumed, etc.

seems that MT should be able to handle this by itself.
maybe a configuration flag to control how it should handle this case (exit or retry) ?

**Comment by woodsaj** [comment]
The only safe response to MT not being able to read the next offset is to drop all data and start consuming from oldest again.  The easiest way to do that is to just restart MT.  

Dropping all the data ingested for the problematic partition is required to prevent gaps in data. eg, MT starts consuming from TS=100,  when MT has only consumed up to TS=150, kafka drops data older then TS=200 .  If MT were then just start consuming from TS=200 chunks would have missing data between TS=150 and TS=200.

If we make AggMetrics partition aware (and used the PartitionedIndex), then we could just drop all of the data for just the affected partition and start consuming again.
