### ISSUE TITLE
When there is no backlog to process, NotifierKafka waits until timeout

### ISSUE THREAD

**Issue by fkaleo** [grafana/metrictank#1316]
When starting metrictank NotifierKafka processes a backlog of 'persist' messages in Kafka. When that queue is empty (which is typical when spinning up a new instance), the notifier hangs in there until the configured timeout, by default 60s, configured to 5 minutes in GrafanaCloud.

**Comment by woodsaj** [comment]
To be clear, The intent is call `processBacklog.Done()` when we have consumed all messages up to what was the newest message when we started.  The problem, is that we dont check if we have consumed up to newest until we receive the first message.  So if there are no messages, we end up waiting until the timeout before calling `processBacklog.Done()`, when we should just call it immediately.
