### ISSUE TITLE
seriesByTag expression parsing can't handle certain characters that are allowed in tags

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1321]
There are two issues, but they are both related to the `seriesByTag` parsing so I put them in the same issue:

This trims certain characters from the end of the value that gets passed into `seriesByTag`. So tag values which end in those characters get trimmed too (f.e. space): https://github.com/grafana/metrictank/blob/master/api/graphite.go#L662

This splits by `,` to split the expression string into the single expressions, but a tag value may contain a `,` in which case this breaks: https://github.com/grafana/metrictank/blob/master/api/graphite.go#L660

This is related to https://github.com/grafana/grafana/issues/15261

**Comment by DanCech** [comment]
It looks like that whole block needs to be updated to parse the tag specifiers in a more robust way, likely by walking the string similar to https://github.com/raintank/schema/blob/master/metric.go#L249

**Comment by replay** [comment]
Yes, and the implementation should be generic so it also helps with this issue: https://github.com/grafana/metrictank/issues/1322
