### ISSUE TITLE
Package level stats with Partitioned Index

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1327]
We currently use a lot of package level and project global stats in Metrictank. This has worked fine in the past because we have been using the Unpartitioned Index. When we switch over to using the Partitioned Index more often I think this will be a problem and stats will be reported / recorded incorrectly. There will more than likely be race conditions in reporting as well.

There are multiple solutions to the problem. It really depends on the nature of the stat. If we are dealing with a counter that we are adding to and subtracting from then it should already work, but if we are looking at a single number that is updated, then it will always reflect the latest Unpartitioned Index that updated it. Instead, we may need to do some kind of moving average internally. I think that is part of a larger discussion on how we want to report our own internal stats.

**Comment by woodsaj** [comment]
The only issue with the stats in the idx.Memory package is the use of gauges where the value is "set". 
 But the only gauge where this is done is`statMetricsActive` .  `Set()` is used 3 times (in deleteTaggedByIdSet(), Delete() and Prune()) and these can be easily changed to just call `Dec()` instead.


All other stats are counters or histograms and so work across multiple partitions.

As a priority we should fix `statMetricsActive`.   

However, i would also prefer to move away from package level stats, but that is less of a priority

**Comment by robert-milan** [comment]
`statsMetricsActive` should now be fixed. I'll look at another PR for the rest of them in a few weeks.
