### ISSUE TITLE
Ensure that data in Kafka does not get expired before being flushed to store

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1331]
We currently always need to ensure that data does not get expired in Kafka before it was flushed to the backend store, we do that with alerts and manually increasing the Kafka retention when necessary. It would be nicer if we could automate that.

Sarama allows us to delete records from Kafka up to a specified offset by sending `DeleteRecords` messages. If we could keep track of which offset is the oldest offset of a given partition that has not been flushed to the store yet, then we could make MT delete the older offsets from Kafka, then we could disable to automatic expiration in Kafka.

This can be done by creating one chunk counter per partition and per time window, where a time window would be the highest chunk span of all aggregations 
f.e. from `now - ( now % maxChunkSpan) - maxChunkSpan` until `now - ( now % maxChunkSpan))`.
This counter keeps track of how many chunks which have their first TS inside that time window are currently kept in MTs memory. Every time a new chunk gets created we increase the according counter by `1`, every time a chunk was flushed to the store we decrease it by `1`. If the counter reaches zero and all older ones are zero, then all records up to the beginning of that time window can be deleted from Kafka.

These are the relevant Kafka/Sarama docs:
- https://kafka.apache.org/protocol#The_Messages_DeleteRecords
- https://godoc.org/github.com/Shopify/sarama#DeleteRecordsRequest

**Comment by Dieterbe** [comment]
> We currently always need to ensure that data does not get expired in Kafka before it was flushed to the backend store, we do that with alerts and manually increasing the Kafka retention when necessary.

to clarify, he's talking about what happens when write nodes restart (due to a crash or upgrade), and specifically the failure mode when a write node restarts a few times before it becomes stable. for example due to OOM during index loading, #866, etc.

**Comment by Dieterbe** [comment]
I like this idea. But if there is a bug in it it (deleting a segment too early) it could easily lead to data loss.
So perhaps we should add an extra condition that we only delete segments based on the proposed logic *and* also if they're more than 7.5hr (our current retention) old.
