### ISSUE TITLE
Cannot query for globbing patterns where the first node is `*`

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1364]
When querying for globbing patterns we currently don't support patterns where the first node is `*`, only later nodes can be `*`. 
Here `startNode` ends up being `""` if the first node in the pattern was `*`: https://github.com/grafana/metrictank/blob/master/idx/memory/memory.go#L1190

**Comment by woodsaj** [comment]
startNode should be using "", that is the root node.  https://github.com/grafana/metrictank/blob/master/idx/memory/memory.go#L593

**Comment by replay** [comment]
closing this again because it's a non-issue
