### ISSUE TITLE
Links in CHANGELOG.md

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1368]
We currently reference `pull requests` and `issues` in the `changelog`, but don't actually provide `links` in the markdown file.

We should update the `changelog` to use `links` instead of just text when referencing `issues` and `pull requests`

**Comment by Dieterbe** [comment]
hmm. on https://github.com/grafana/metrictank/releases github does this automatically, but not on https://github.com/grafana/metrictank/blob/master/CHANGELOG.md
perhaps there's a way to make it do it automatically.

**Comment by robert-milan** [comment]
> hmm. on https://github.com/grafana/metrictank/releases github does this automatically, but not on https://github.com/grafana/metrictank/blob/master/CHANGELOG.md
> perhaps there's a way to make it do it automatically.

I think it is because it is a `markdown` file, we will need to manually create the links.
