### ISSUE TITLE
should CCacheMetric.searchBackward() set the Complete flag when it hits ts < from ?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1377]
mc.searchForward sets complete attribute, but searchBackward does not.
not sure if intentional. does searchBackward reaching ts < from (and it reaching a complete result) even make it sense, or does that mean the searchForward call should have worked completely?

it's especially strange since we check Complete before and after calling searchBackward: https://github.com/grafana/metrictank/blob/5379703b397c794a37f9322a6d6541944ff1dfc4/mdata/cache/ccache_metric.go#L407-L411

**Comment by shanson7** [comment]
IIRC `searchBackward` should never be able to complete the search. That's why the second block is there, to warn that some corruption happened in the cache.  The second block could / should be moved into the block with `searchBackward` (and drop the `!res.Complete` check).

**Comment by replay** [comment]
right, IIRC that's just to detect corruptions. Although, AFAIK we've never seen such a corruption actually happen over the last year, right @Dieterbe ? I've also just browsed through a lot of metrics that we collect from various instances, and I haven't found one where this counter is `>0`. So maybe we should just remove that

**Comment by shanson7** [comment]
@replay Which counter? I see 50 occurrences of this line https://github.com/grafana/metrictank/blob/5379703b397c794a37f9322a6d6541944ff1dfc4/mdata/cache/ccache_metric.go#L412 in our deployment logs in the last 30 days. And 350k occurrences of this https://github.com/grafana/metrictank/blob/5379703b397c794a37f9322a6d6541944ff1dfc4/mdata/cache/ccache_metric.go#L113

So, I think this cache is still not quite foolproof.

**Comment by replay** [comment]
@shanson7 sorry for editing my comment before you posted yours. I conflated it with the bug tracked by this metric: https://github.com/grafana/metrictank/blob/master/mdata/cache/ccache.go#L22

this is very interesting though that you see so many occurrences of that log statement, i wasn't aware that's that common

**Comment by shanson7** [comment]
> i wasn't aware that's that common

TBF, in the last 30 days we've handled ~300 million queries, so 50 is only `~0.0000167%` of queries. 1 in 6 million is pretty good :) Also, I expect they are correlated in some way, as several of them seem to be clustered together.

**Comment by Dieterbe** [comment]
ok so #1378 , anything else to do here? @replay ? searchBackward should never set Complete right?

**Comment by replay** [comment]
yes, it looks to be certain that `searchBackward` never sets `Complete`. iirc it used to at some point, but not anymore.
