### ISSUE TITLE
Add API call to delete by tag query

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1426]
We need to add a new API call where a user can delete series from the index by specifying a tag query in the same format as in the `/tags/findSeries` endpoint.
There already is a delete endpoint which is compatible with https://graphite.readthedocs.io/en/latest/tags.html#removing-series-from-the-tagdb
but this doesn't provide enough flexibility for users who want to do large deletes based on tags

**Comment by Dieterbe** [comment]
related: #1023

**Comment by shanson7** [comment]
Another request for this endpoint: Support only deleting series older than a certain time. 

The rationale is that we might have had a new deployment at say 8am or something and we just want to delete any series from before that. This helps to avoid deleting series that are still being published (which would then be 'unknown' until the next 'full' metricdata point comes in).

**Comment by replay** [comment]
Great idea. If we implement [this suggestion](https://github.com/grafana/metrictank/issues/1023#issuecomment-590909825) we could also add the `from` as a filter so it can get applied to both, deletions of tagged and non-tagged metrics

**Comment by shanson7** [comment]
Sure, but this is like the reverse of `from`

**Comment by shanson7** [comment]
Still something that would be useful.

**Comment by replay** [comment]
True, it's still in my current sprint as well, just didn't get to it yet
