### ISSUE TITLE
missing metrics in graphite-web/grafana, displayed "randomly"

### ISSUE THREAD

**Issue by kennux75** [grafana/metrictank#1440]
Hello all,

I have set up an architecture to collect our system metrics. I've already asked a few questions on slack, talked with Dieter or received the advises of Sean, I tried several configurations, but I cannot figure out what is my problem, so my apologies for this long message.

The symptoms are: on grafana, or graphite (in the web interface), between two reloads of dashboards or a refresh on the graphite web page, I miss some metrics. I know/think (sure 99..%) they are present, because they can display sometimes.

I have another weird behavior: sometimes only the last "20mn old"? "40mn old" or "1h old" metrics are displayed:
below, 2 screenshots of the same graph, but with a different time range (when I made those screenshots, it was 7:40pm)
those 2 graphes come from a grafana datasource made with 2 graphite-web, with httpd and uwsgi mod.
the timerange displayed is -40mn
![Screenshot from 2019-08-22 19-38-28](https://user-images.githubusercontent.com/54410971/63536750-83a29980-c514-11e9-81a9-904198044cca.png)
![Screenshot from 2019-08-22 19-38-39](https://user-images.githubusercontent.com/54410971/63536802-a46aef00-c514-11e9-890c-b201ecc25d32.png)

below, same illustration, but the datasource is now a graphite-web, with gunicorn and nginx:
the timerange displayed for a metric is -20mn
![Screenshot from 2019-08-22 19-41-15](https://user-images.githubusercontent.com/54410971/63536986-09264980-c515-11e9-9dc7-56ccaf7e46e7.png)
![Screenshot from 2019-08-22 19-41-30](https://user-images.githubusercontent.com/54410971/63536995-0c213a00-c515-11e9-8251-52eb3ddafc43.png)

some graphes behave correctly, or other ones, I can have some metrics for server1, 2 and 4, I reload, it will be server2, 3 etc etc.

So now let me describe my infrastructure (I have to precise that all the machines are vmware VMs):

- I have 6 cassandra nodes, I'm not an expert in cassandra, our DBAs handle the cluster, but I can provide more precise information if needed.
- Abose this, I have a couple of metrictanks. A few couples (according the test env or production one) of primary/secondary nodes in shard mode, each couple consuming a set of kafka partitions.
- This kafka cluster is alimented with a couple of carbon-relay-ng.
- Those relays are behind an HAProxy loadbalancer in round robin.
- we are not multi-tenant.

So metrics are sent like this:
\<collect system\>  -> haproxy carbon port -> carbon relay ng -> kafka -> metrictank -> cassandra.
We usually send it with collectd, statsd, but we can use logstash, or other systems to send datas in the carbon format.

I added metrictank instances in query mode, to be the "querying" part (read only nodes).
But it seems that only querying the "query" nodes, I miss some metrics too (but I can see in the logs that they receive metrics from other nodes)

Finally, I have set up a few graphite servers with: 
- graphite-web 1.1.0 installed with pip (with puppet - a bit complicated)
- httpd 2.4, with WSGI mod
This solution is now problematic, and we have a lot of "missing metrics" issues.
I tried another solution:
 - nginx, with graphite-web 1.1.5, and gunicorn.
This solution seems to be much better, I have only a test server, but it can handle more that the other solution.

Those graphite servers are behind the haproxy loadbalancer.
We received around 100k-150k metrics/sec.

Here is what I tried:
- I was thinking a problem with the storage-schemas. I tried the use the chunkspan, and numchunks parameters, but apparently, no big changes.
- I played with the graphite local_settings file, changing timeouts, fetch, cache etc.. but nothing really efficient.
- I set up the read only instances in debug mode, I don't really see errors, but some "0 results from.." but "xx series found on cluster". 
- Sean told me about the "deadlocked" state of MT instances, but did not see anything particular on the dashboards, I can share some snapshots if needed, tried to increase the write queue. 
- the fact that only the last 20mn, or 40mn or 1h old metrics are displayed made me think to a buffer size, or a cache, or the storage schemas.. but I start to be a little bit lost at this point.
-  I tried enabling or disabling the memcache option in graphite
- I tried to change the CLUSTER SERVERS (graphite local_settings file) parameters to all the MT instances, only the "query" ones, the VIP with the haproxy LB. 
- I've watched this issue, but I'm able to query, it's not really my pb here: [https://github.com/grafana/metrictank/issues/1401](1401)

I could have a lot of questions or suppositions, but I will just ask here a few ones:
- Do you see something is my infra which can be a problem?
- I still have some metric loss when I restart a secondary instance, or "reducing" a master to secondary, promoting the secondary to primary, and restarting the "old" primary.. maybe I don't wait long enough? 
- I read that you got better results with graphite-web than api? Is it still the case? or do you want to do some benchmarks? :)
- Would it be better to put a graphite instance in localhost with the MT one? 
- I was thinking to set up a direct grafana datasource to metrictank VIP on 6060, with a fallback graphite server, but It wasn't working, I think I missed something. Do you advice to use a graphite datasource, or a MT one with a fallback server (we use a lot of graphite functions)

I have a full 'virtual' testing stack, not a docker one. We are working to move it into kubernetes, but it will be in the next few months.

I hope this is the right place to ask those kind of questions, it's maybe not a proper MT issue, but graphite or cassandra, but I would be curious to have your opinion or ideas to make my boss smiles :)

Thanks a lot
Remi

**Comment by woodsaj** [comment]
This definitely looks like a configuration issue.

Different series being shown when you refresh a dashboard typically means that the metrictank node the receives the request from graphite is not aware of all of the metrictank nodes in the cluster.     The metrictank nodes use a gossip protocol to discover all nodes in the cluster and each node reports the partitions that they own.  
To check everything is working and discovered, you can query the "/cluster" api endpoint on each metrictank node.  This will return that nodes view of the cluster.  Each node should have the same view (ie it should be aware of all nodes in the cluster).

eg on each metrictank node run
```
curl http://localhost:6060/cluster | json_pp
```

For the issue of only the last 20mins of data showing up for some series, that will be due to there either being no primary node for some partitions, or the primary node is unable to write to chunks to cassandra fast enough.  The issue could also be due to secondary and primary nodes using different  storage-schemas configs, which would lead to the secondary nodes trying to read from different cassandra tables to what the primary nodes are writing data to.

so, 
- check that the  storage-schemas are consistent on all nodes in a cluster.
- check that there is a primary node for all partitions
- check that the primary nodes are flushing their write queues fast enough

**Comment by kennux75** [comment]
Thanks a lot Anthony for your reply.

I checked the cluster state on all the nodes, and I have the same output:
node1
cluster = {
  "clusterName": "mt cluster name",
  "nodeName": "node1",
  "members": [
    {
      "name": "node1",
      "version": "v0.12.0-128-g394cfc9",
      "primary": true,
      "primaryChange": "2019-08-22T16:35:36.228469031+02:00",
      "mode": "Shard",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-22T16:35:36.226156786+02:00",
      "stateChange": "2019-08-22T16:36:24.537729759+02:00",
      "partitions": [
        0
      ],
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-22T16:36:24.537729759+02:00",
      "remoteAddr": ""
    },
    {
      "name": "node2",
      "version": "v0.12.0-128-g394cfc9",
      "primary": false,
      "primaryChange": "2019-08-22T17:05:52.851550586+02:00",
      "mode": "Shard",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-22T16:18:25.752634924+02:00",
      "stateChange": "2019-08-22T16:34:02.465788952+02:00",
      "partitions": [
        0
      ],
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-22T17:05:52.851550586+02:00",
      "remoteAddr": "<node2 ip>"
    },
    {
      "name": "node3",
      "version": "v0.12.0-128-g394cfc9",
      "primary": true,
      "primaryChange": "2019-08-22T16:41:36.109591391+02:00",
      "mode": "Shard",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-22T16:41:36.107136363+02:00",
      "stateChange": "2019-08-22T16:42:23.17355761+02:00",
      "partitions": [
        0
      ],
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-22T16:42:23.17355761+02:00",
      "remoteAddr": "node3 ip"
    },
    {
      "name": "node4",
      "version": "v0.12.0-128-g394cfc9",
      "primary": false,
      "primaryChange": "2019-08-22T17:06:08.546581987+02:00",
      "mode": "Shard",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-22T16:25:08.793608662+02:00",
      "stateChange": "2019-08-22T16:40:48.666545474+02:00",
      "partitions": [
        0
      ],
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-22T17:06:08.546581987+02:00",
      "remoteAddr": "node4 ip"
    },
    {
      "name": "node5 - 1st read only",
      "version": "v0.12.0-128-g394cfc9",
      "primary": false,
      "primaryChange": "2019-08-23T10:35:15.139519378+02:00",
      "mode": "Query",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-23T10:35:15.137299348+02:00",
      "stateChange": "2019-08-23T10:35:25.224560294+02:00",
      "partitions": null,
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-23T10:35:25.224560294+02:00",
      "remoteAddr": "node5 ip"
    },
    {
      "name": "node6 - 2nd read only",
      "version": "v0.12.0-128-g394cfc9",
      "primary": false,
      "primaryChange": "2019-08-23T10:35:24.146008962+02:00",
      "mode": "Query",
      "state": "NodeReady",
      "priority": 0,
      "started": "2019-08-23T10:35:24.143765862+02:00",
      "stateChange": "2019-08-23T10:35:34.240962947+02:00",
      "partitions": null,
      "apiPort": 6060,
      "apiScheme": "http",
      "updated": "2019-08-23T10:35:34.240962947+02:00",
      "remoteAddr": "node6 ip"
    }
  ]
}

- node1 and node2 consume the same kafka partitions, and same for node3 and 4. 
I don't really know why it's written "partitions 0". Maybe it counts the partitions for carbon-in? (it's enabled on our nodes, but we don't really use it)
I usually set node1 as primary, node2 secondary (and same for node3 and 4)
- Regarding the storage schemas, it is automatically deployed, so it is consistent on all MT nodes.
About the flush in databases, how can I check this? 
On the MT dashboard, I cannot see any "cassandra store errors", the "op durations" are a few ms, maximum 10-20ms. The write queue limit is 100k, there are 20 write workers, but none of the queues reach this limit.

Thanks for you help
Remi

**Comment by kennux75** [comment]
Hello,

I continue to debug my problem, and I queried the different metrictank nodes, and it seems there is an issue reading cassandra, or getting the metrics.
The behavior I observe is that:
I "curl" several times the same MT node (primary or secondary) with a precise metric (there are normally 6 results for memory-*):
curl -s -vv -d "target=<metric path>.memory-*&from=-12h&untilnow&format=json" localhost:6060/render | jq '.[].target'
I get partial results after each executions:
<metric path>.memory-cached
<metric path>.memory-slab_recl
or
<metric path>.memory-used
<metric path>.memory-free
<metric path>.memory-slab_unrecl
<metric path>.memory-buffered

Everytime grouped together.
I try to find a precise metric with:
curl -s  -vv -d "query=<metric path>.memory-used" localhost:6060/metrics/find

I can see in the logs, the resulting "/index/find" query done by MT, and sometimes I get a null result, or I get a json witth the metric found, a leaf from the index tree I guess. 
But I never have all the metrics together. 

When I made the query on the query nodes, I can see in the debug logs:
"HTTP findSeriesRemote across 1 instances", but never on several instances.
and I get either:
"HTTP findSeries 2 matches " or "HTTP findSeries 4 matches " (according to the previous series)

I observe this same behavior on every nodes of my cluster. 
Does that mean the metrics are in different tables in cassandra or a replication problem? Or there is an issuie with my index? Or there is a problem with sharding?
I tried to increase the warm-up period to have enough data, but no changes.. 

If you have a clue on what's going on.. I would be really grateful :)

Thanks a lot
Remi

**Comment by woodsaj** [comment]
> node1 and node2 consume the same kafka partitions, and same for node3 and 4.
I don't really know why it's written "partitions 0". Maybe it counts the partitions for carbon-in? (it's enabled on our nodes, but we don't really use it)

This sounds like your problem.  I suggest you try disabling the carbon-in plugin

**Comment by kennux75** [comment]
Thanks Anthony. 
Unfortunately, I have already tried this solution. But even after disabling the carbon-in input, all nodes restarted and ready, but still partitions [ 0 ] in the /cluster. And same behavior.
But the weird thing is that each node seems to be aware of all the metrics, but "separated" by shard group, but returned randomly the metrics belonging to one shard group at a time..

**Comment by kennux75** [comment]
Moreover, I activate the speculation-threshold, set it to 0.8.

Sometimes, I can get the full series when my first query node receive the first part of the serie by a one of the shard node, and the second query node received the other part of the serie, the merging part in graphite works correctly.
graphite.render.datalib.fetchData :: lookup and merge of "\<metric path\>*.memory.memory-*" took 0.000830889s

But on many graphes, we always have missing metrics.

**Comment by kennux75** [comment]
Hi guys,

I think I have found my issue. I just disabled the both input plugin carbon-in and prometheus in.
After a restart, the /cluster shows correctly the kafka partitions consumed. 

I can reproduce the bug if I reactivate the plugins with one partition and several partitions in kafka input.

Sorry for the inconvenience and thanks for your help.
Remi
