### ISSUE TITLE
remove promql support

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1454]
prometheus on top of metrictank has never really worked great, due to minor design differences between graphite and prometheus.
and our prometheus integration uses an old version of the library that results in vendoring conflicts when we want to use prometheus elsewhere (e.g. the instrumentation of the jaeger library), which is annoying
Since Cortex or Thanos are better solutions for prometheus users, we will remove the prometheus ingest/query functionality out of the metrictank platform.

**Comment by Skunnyk** [comment]
Hello,

We are using the prometheus ingest/query functionality with metrictank. Even if it has some limitations, it works fine for our usage (btw, we have started to look at alternatives to suits our scale).
We were looking at the upgrade of the prometheus lib in metrictank (switch from the old 2.1.0 vendor to the latest 2.13).
Are you interested, or the removal of promql from metrictank is non-negotiable?

Thank you,

Note: ping @beorn-

**Comment by Dieterbe** [comment]
Our main issue is that we can't jusitify spending time on that ourselves right now as almost no-one is using the prometheus integration of metrictank (or paying for support for it).
I would welcome a PR that updates the prometheus libraries within metrictank and removes the conflicts that arise when trying to use the jaeger client metrics (which need a new version of the prometheus client)

@woodsaj thoughts?
