### ISSUE TITLE
 metric-tank cpu usage spikes

### ISSUE THREAD

**Issue by electron0zero** [grafana/metrictank#1467]
We are seeing sudden CPU usage spikes in our metrictank instance,

Avg CPU usage is around 13-15% but it spikes to 100% every so often, when CPU usage spikes metric tank becomes unresponsive, and due to that our grafana and downstream alerting engine (Nagios) fails to get data, which results in lots of alerts :-(

**Setup Details:**
Single node metric-tank, with 3 node Apache Cassandra cluster, it's running on single VM (*Machine type: custom (8 vCPUs, 20 GB memory)*)
we are pushing data to metrictank via carbon input method

I am attaching few graphs from our monitoring setup.
**metrictank VM CPU Usage:**
![image](https://user-images.githubusercontent.com/9503187/65188994-60c0c200-da8d-11e9-9ce8-b3139d78f741.png)

**metrictank mem. usage**
![image](https://user-images.githubusercontent.com/9503187/65189457-a92caf80-da8e-11e9-8cb2-46dc9f75d24a.png)

**metrictank load**
![image](https://user-images.githubusercontent.com/9503187/65189495-bfd30680-da8e-11e9-92ef-7f407c77ea4c.png)

**metrictank Metrics received / min**
![image](https://user-images.githubusercontent.com/9503187/65189358-54893480-da8e-11e9-97f8-da7850e35d74.png)

Please let me know if you need more details.

**Comment by replay** [comment]
Did this issue start with a recent update, or has it always been like that? Sounds a bit like the memory index pruning might be the issue, does the pruning interval align with the interval of those cpu spikes?

**Comment by Dieterbe** [comment]
Can you share a snapshot of the entire dashboard?

**Comment by electron0zero** [comment]
> Did this issue start with a recent update?

We haven't updated metrictank, here is version info
```bash
$ /usr/bin/metrictank --version
metrictank (version: v0.11.0 - runtime: go1.11.4)
```

> Sounds a bit like the memory index pruning might be the issue, does the pruning interval align with the interval of those cpu spikes?


I am assuming you are talking about prune interval config under `[cassandra-idx]` block, which is 3h in our case.
```
#Interval at which the index should be checked for stale series. valid time units are 'ns', 'us' (or 'µs'), 'ms', 's', 'm', 'h'
prune-interval = 3h
```
Spikes does not align with prune-interval

> Can you share a snapshot of the entire dashboard?

@Dieterbe here you go 
- VM Stats - http://monitoring.clarisights.com/dashboard/snapshot/Esoigt74yO6kUN23Jc4arlo5TdNp8VTw
- Metrictank - http://monitoring.clarisights.com/dashboard/snapshot/Ss9SH2V9MPYcqbiI5VWu4GZsPxDyQ7jC

**Comment by Dieterbe** [comment]
i meant https://grafana.com/grafana/dashboards/279

**Comment by electron0zero** [comment]
Getting 500 when importing https://grafana.com/grafana/dashboards/279 :-(

I am running  Grafana v6.2.4 (commit: ee01897)

**Comment by electron0zero** [comment]
@Dieterbe here you go: http://monitoring.clarisights.com/dashboard/snapshot/ck5U6VZ3avF7kHTs7du09LapVF6RSmEN
