### ISSUE TITLE
write down product idea regarding graph-explorer style functionality, metrics2.0

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1487]
Dieter has some thoughts and wants to write them down

**Comment by fkaleo** [comment]
That will be broken down into multiple design docs, therefore tickets :)

**Comment by Dieterbe** [comment]
1) https://docs.google.com/document/d/1xW_VxtNHoVo2FzUWk0R74YJjokF4kPeN7ULAtOJcXas/edit#

2) and maybe 3) will be about the exploration interface and probably tag enrichment/abstraction to allow the exploration on legacy metrics
