### ISSUE TITLE
clarify consolidation, esp wrt "special functions"

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1490]
the notes around "special" functions resetting consolidateBy settings need further clarification.

dieter:
https://gist.github.com/Dieterbe/65e27ce645653c9ec481fc909074d582

awoods 5:34 AM
I think i get what you are saying.  I think some of the confusion is mostly due to the lack of consistent terminology that can be used to describe the interactions of consolidateBy, combined with the fact that what MT is doing is very different to how Graphite works. I also think that there are a large number of flaws in how consolidateBy is currently being handled.  And overall the "rules" for how consolidateBy is handled are vague and ill defined.
I think we could describe it better by first explaining when consolidateBy is used:
1) consolidateBy is used to reduce the final result to maxDatapoints.
2) consolidateBy is used when normalizing series that need to be combined so they all have a consistent interval
3) consolidateBy is used to instruct Metrictank which aggregation to select if rollups are being used.  Rollups are used instead of raw data when the time range extends beyond the retention period of raw data, or if using raw data would exceed the MAX_POINTS_PER_QUERY limits.

From what you have described, it appears that the following rules are in place:
1) When reducing the final result to maxDatapoints, the outer most consolidateBy is used.  However, if the outer most consolidateBy is within a 'special' function, 'avg' is used instead.
2) when normalizing series, the inner most consolidateBy is used.  However, if the inner most consolidateBy is above a 'special' function in the call stack, then 'avg' is used instead.
3) when selecting rollups, the inner most consolidateBy is used.  However, if the inner most consolidateBy is above a 'special' function in the call stack, then 'avg' is used instead.
Does this sound accurate to you?

awoods 5:45 AM
Also, once we have this clear, it would make a great blog post.
dieter 10:55 AM
yep, this sounds right.
> I also think that there are a large number of flaws in how consolidateBy is currently being handled

@woodsaj can you explain this a bit more. which flaws do you see?

**Comment by woodsaj** [comment]
> can you explain this a bit more. which flaws do you see?

The major 'flaw` is that from a user perspective it is impossible/difficult to understand how the datapoints are being consolidated.

We have `special` functions that change the way consolidateBy is interpreted, but there is no way for a user to know what functions are 'special'.    We discussed that 'special' functions are ones that change the nature of individual series, eg `summarize` or `perSecond`.  But based on that definition,  functions like `scale` and `offset` would be considered 'special', but they are not.    What i suspect is that functions are only special if the output point is derived from multiple input points. eg summarize combines multiple points together and perSecond calculates a rate based on previous and current point.  However, even this definition is not specific enough as it would match functions like `movingAverage`,  and `derivative`.

In addition to not knowing what functions are 'special' i am 99.9% confident that the special behaviour  of these functions wont generalize to all use cases.

Finally, educating users about how consolidateBy works will be extremely difficult, but without this education users will continue to do the wrong thing and get bad/misleading results from their queries.


I think that metrictank should just remove this special handling and just treat all functions the same. eg

1) When reducing the final result to maxDatapoints, the outer most consolidateBy is used. 
2) when normalizing series, the inner most consolidateBy is used. 
2) when selecting rollups, the inner most consolidateBy is used. 

Users should then be educated about when they should use additional consolidateBy's in their queries.  I think there is a greater chance of users being successful if the rules are simple, even if that means that they need to be a little more explicit with their queries.
