### ISSUE TITLE
mt-whisper-importer writer needs a way to turn off auth

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1497]
for (on-prem) deployments where:
1) we don't go through tsdb-gw
2) the environment is secure, and we know that whatever orgid we specify is the correct one for the data

**Comment by woodsaj** [comment]
the mt-importer-writer does not really have auth. It just requires the requests to have a 'X-Org-Id' header.

Sounds like what you want is for mt-whisper-importer-reader to support just setting the x-org-id header instead of using basicAuth

**Comment by Dieterbe** [comment]
that would be better, as it allows to run different imports with different orgid's targetting the same writer.
