### ISSUE TITLE
Uneven partition distributions can lead to inconsistent results

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1506]
While a cluster of Metrictanks is in a state where its partitions are distributed unequally between instances, there can be situations where finds using speculative query execution result in incomplete results.

We're currently using the first partition of each Metrictank as an identifier for its partition group, assuming that all Metrictanks which have the same first partition have all the same partitions https://github.com/grafana/metrictank/blob/431b6c98e78691203289a3526b913056155d3f8c/cluster/cluster.go#L182
In a situation where the partition distribution is unequal, this can result in partitions being omitted when executing cluster wide finds. 
For example:
```
Metrictank0: 4,5,6,7
Metrictank1: 4,5
```
It is possible that a `/find` call would end up on Metrictank1 and the partitions `6,7` would get omitted.

**Comment by shanson7** [comment]
Yes, this was brought up during the implementation. See https://github.com/grafana/metrictank/pull/956#issuecomment-406676801

**Comment by replay** [comment]
Good point. In the meantime our requirements have changed, so we're now looking for a way to make that work.

**Comment by Dieterbe** [comment]
This is not an actual issue. Just something we'd like to improve
