### ISSUE TITLE
"Writeback RAM cache" documentation

### ISSUE THREAD

**Issue by mj41-gdc** [grafana/metrictank#1509]
Please elaborate on what "Writeback RAM cache" ([README.md - Features](https://github.com/grafana/metrictank/blob/master/README.md)) means. I tried to Google that and didn't found answer. Thank you.

**Comment by Dieterbe** [comment]
https://www.webopedia.com/TERM/W/write_back_cache.html
basically it means we only flush chunks periodically and write to the storage system as little as possible, but have a cache in RAM of all current data.

**Comment by mj41-gdc** [comment]
Thank you. There is good explanation https://en.wikipedia.org/wiki/Cache_(computing)#Writing_policies
Feel free to close this issue if you consider the Readme good enough.
