### ISSUE TITLE
groupByTags() doesn't recognize all callback functions

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1528]
https://graphite.readthedocs.io/en/latest/functions.html#graphite.render.functions.groupByTags
graphite allows many more than MT.
We validate using `getCrossSeriesAggFunc` which doesn't recognize "count" for example

**Comment by replay** [comment]
Is the goal of this to support all aggregator functions of graphite which have specifically been written as aggregator functions, or do we also need to support all other functions that can also be used as aggregators? in the second case that's going to be quite a list

**Comment by Dieterbe** [comment]
first step sounds good I think. for the record, can you provide a list of both categories.

**Comment by replay** [comment]
yep, quite a few of them are just aliases to each other

aggregator functions which have been added specifically as aggregators:
* max
* multiply
* diff
* count
* last
* min
* average
* median
* range
* stddev
* avg_zero
* sum
* total
* current
* avg
* rangeOf

series processing functions which may also be used as aggregators:
* multiplySeries
* powSeries
* rangeOfSeries
* diffSeries
* minSeries
* multiplySeriesWithWildcards
* averageSeriesWithWildcards
* stddevSeries
* sumSeriesWithWildcards
* avg
* sumSeries
* countSeries
* sum
* maxSeries
* averageSeries

**Comment by Dieterbe** [comment]
is it true that all of the `<foo>Series` are aliases for `<foo>` ? In that case, we may as well implement those aliases too in the first pass.

**Comment by replay** [comment]
These names that i posted are the "original" names of the functions in the list of series processing functions and aggregator functions. Some of them are separate functions which call each other, like for example there's the aggregator `sum` and then there's a separate series processing function called `sumSeries` which internally just uses the `sum` aggregator, so i guess you could call this an alias. Some of them are completely separate implementations, like for example the aggregator `count` and the series processing function `countSeries` don't use each other.

Additionally to that, the `aggregate()` function allows the user to append the string `'Series'` to any of the function names of the first category in its callback, then it just drops that part and looks up the aggregator function with the resulting string, so in this case for example `lastSeries` is also valid even though there's no alias for `lastSeries` defined. But some are different, like for example there's a series processing function `powSeries` but no aggregator function `pow`, so for example `powSeries` could not be used with `aggregate()` but it could be used with `groupBy*`.

Anyway, it's complicated, I think each case would need to be looked at separately to implement the same functionality.

**Comment by replay** [comment]
If we implement that in MT i suggest we look at all the series processing functions and aggregator functions, if they end with `'Series'` we remove that string, then we unique the list and implement these aggregators. Then in MT we just create an alias for each of the resulting functions which has the same name `+ 'Series'`. That way we should support more functionality than Graphite, but not less
