### ISSUE TITLE
re-allow point updating with reorder buffer

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1531]
We need to revise https://github.com/grafana/metrictank/issues/1201

There is a legitimate use case for wanting to overwrite the last point. we have a customer who has points that are composed of aggregates of jobs, and they can't predict the number of jobs or when they'll complete, so the most practical and useful thing is to send a point (and update if necessary) each time a new value comes in

Awoods suggested adding a config flag to control whether MT should use the first or last value.

**Comment by replay** [comment]
just for clarification, with the rob it used to be possible to update any datapoint in the rob, not only the last one.

**Comment by Dieterbe** [comment]
this is now high priority.
