### ISSUE TITLE
If Meta Tag index is used, take it into account when determining order of expression evaluation

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1534]
When MT receives a tag query involving multiple expressions it estimates each expressions cost and then tries to sort them so the total query evaluation time is as short as possible. Currently this cost estimation does not take the meta tag index into account, only the metric tag index, it should be pretty simple to change that so both indexes are taken into account and certain large queries could benefit a lot from it.

**Comment by replay** [comment]
done

**Comment by robert-milan** [comment]
Complete
