### ISSUE TITLE
Clean up `idx/memory` namespace by moving components into their own packages

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1535]
We currently have a lot of independent components mixed together in the `idx/memory` package. This leads to quite a lot of unnecessary namespace pollution in the index package. It should be simple to move many of these components into their own packages. 
There could be a hierarchy like 
* `idx/memory/tags`
* `idx/memory/tags/metaTags`
* `idx/memory/tags/metaTags/enricher`
* `idx/memory/tags/metaTags/metaRecords`
* `idx/memory/tags/metaTags/metaTagIndex`

**Comment by Dieterbe** [comment]
good luck :sunglasses:

**Comment by Dieterbe** [comment]
looking at https://godoc.org/github.com/grafana/metrictank/idx/memory , it actually looks quite reasonable to me. but this only shows public types.
grepping in idx/memory, i see 28 types declared (public+private)
looking at https://godoc.org/net/http for inspiration, I note that they also have many things related to http together in one package (e.g. servemux, client, request, response, ...)
net/http has 48 .go files, idx/memory has only 20.

Perhaps we could reorganize the code a bit, but i don't see a big problem here.

**Comment by Dieterbe** [comment]
related: #1510

**Comment by replay** [comment]
If we don't break it up into small sub-packages, we should at least re-organize the tests a bit because at the moment they're kind of messy and all mixed together. I think this could be improved by moving them into specific files where each file has a defined purpose.
