### ISSUE TITLE
Create detailed description of testing scenarios that are used to test the meta tag feature

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1537]

**Comment by Dieterbe** [comment]
can we script it such that it becomes a reproducible stacktest/benchmark?

**Comment by replay** [comment]
@Dieterbe for the purpose of this task i think this would be out of scope. We really just want to show some examples of how the meta tag queries are working, together with some timing numbers.

I created a description in this public gist for now:
https://gist.github.com/replay/7a9b97557cb5cb4e5fc51ed46b12f296

**Comment by replay** [comment]
handed that description off as agreed on, so i'm closing this issue
