### ISSUE TITLE
Implement Metrictank query logging

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1538]
This is the current plan:

Query Logging in Metrictank

Goals to consider:
We have often encountered situations where a user was overloading their metrictank cluster with queries, and we saw that the issues were caused by their queries, but we didn’t know what the exact queries were. When we tell a customer that their queries are overloading their instance, the first question often is “which query”. So we need logging that allows us to answer this question for them and for ourselves
We want to analyze which metrics are getting queried by customers, so we need to log the queries in order to then analyze them and extract the metric names.
The resulting utility will be closed source, so it must not be in the Metrictank repo

What needs to be logged
Trace id. This allows us to correlate logs across multiple mt instances
OrgId. We need this for multi-tenant clusters so we know who made the request
Query params: Everything in the request payload. targets, maxDatapoints, etc...
Referrer: Super useful to track down where bad requests are coming from.
Source ip: From x-forwarded-for header if there is one, otherwise the actual source IP
Status code
Request timing info: How long the request took to complete
Error messages: If the request was not 2xx, we should include the error message for why it failed.

Log Format
We need a specific prefix based on which we can filter these new query log lines, this will allow us to directly label them in promtail and enable efficient querying.
We’re going to URL encode all the request params and headers into a string, in a similar fashion to what Loki and Cortex are doing:

query: ip=? orgID=? sourceIp=? status=? duration=? traceID=? request=”?” headers=”?” duration=? error=“?”

In error / traceId all “ characters get replaced by ‘ for parsability of the log format.
The value of request is a url encoded string containing all the request params.
The value of headers is also a url encoded string with the received headers & values, but before logging them we will filter them by a configurable blacklist to remove authentication headers etc

**Comment by replay** [comment]
Additionally, we also want to disable Macaron logging

**Comment by fkaleo** [comment]
See https://github.com/grafana/deployment_tools/pull/2386

**Comment by fkaleo** [comment]
Add ability to get logs from loki
