### ISSUE TITLE
[Question] Distributed index and sending old metrics

### ISSUE THREAD

**Issue by Nuadvocate** [grafana/metrictank#1548]
_This is more of a question than an issue. _

We recently migrated graphite to metrictank. And need some pointers:

1) How do you deal with growing index, especially due to Kubernetes and containers metrics that's ever changing? Is there a way to distribute the index since Metrictank doesn't use an external memory datastore like memcached or redis. These are known as inactive metrics and most commercial SaS monitoring services provider usually deletes them to avoid further growth. For our use case, we don't want to delete them since we need these for historical data.

2) Most of  our environment is behind a firewall and loadbalancer, and sometimes the underlying services gets block if that firewall/lb goes down or has issues. We save metrics in a file format in case we run into these issues to resend them. How do I send metrics that are over 1 day, or even 30 days to Metrictank (mt-whisper tools is out of question, since these aren't whisper but just zipped text files). It seems like Metrictank drops these data before persisting to cassandra when being resent. Do we need to set the max-stale setting to something greater?

**Comment by Dieterbe** [comment]
1. metrictank does have persistent index plugins, that use cassandra or bigtable for storage. but with the current index design, each process keeps a copy of all index data in memory (for those shards that it owns). we do have an index pruning mechanism - https://github.com/grafana/metrictank/blob/master/scripts/config/index-rules.conf

the way we deal with this currently is to simply anticipate future workload when provisioning the cluster, such that there's enough partitions/shards that can be split across processes in a cluster (typically a process owns many partitions at first, but as the system grows, you'd create more separate processes that own fewer shards).
we do plan to make this process smoother, and are thinking about new index designs that don't need to load a copy of data in memory.

2. you can do a workflow like this if you don't send a chunk`s worth of data until you have the full chunk to be sent. then, regardless of max-stale, you can send data no matter how old, if you always start from a chunk boundary. another option would be to create a reader that can read from your data files. the importer framework is actually fairly pluggable - we have some api tweaks in the works though - but, reading from any non-whisper storage system should be a matter of simply writing a reader plugin.

**Comment by Nuadvocate** [comment]
Yes, I'm currently using the cassandra plugin for the index. When we first started we only had a few metrics series count, and did not accounted sharding the index, so as of current the index loads everything on startup. I think that is fine as long we have the memory capacity, only downside is if someone tries to load the full index on graphite endpoint, it can double the memory usage and lead to OOM.
Please do update us on the new index designs, would be nice if you can setup the idx to sync with servers in the cluster using some sort of hashing algorithm to balance series count, and allow new servers to be added on the fly and resync similar to how cassandra network topology works.

**Another question** : Does the index still persist to cassandra_idx even though it is not a primary. Since we have writers that doesn't fan out reads, I don't think its necessary to pull the index every startup, and using the memory_idx would be more efficient.  Reason is if thats the case, we don't want emphasis memory increased/upgrades on these writers, and focus more on the indexer.  

Thanks

**Comment by Dieterbe** [comment]
see
```
# synchronize index changes to cassandra. not all your nodes need to do this.
update-cassandra-index = true
```
if you have multiple replicas that receive the same data, only one of them needs to have this set to true.

**Comment by Nuadvocate** [comment]
Got it. Thanks. Closing this request.
