### ISSUE TITLE
Support useful tag-based metadata endpoints

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1573]
We currently maintain a separate Elasticsearch endpoint with all metric metadata:

1. lastUpdate (approximate to 3 hours)
1. Metric name and tags
1. interval

We do several things with this data:

For a given expression:
1. Get count of time-series
1. Get count of distinct values for a tag
1. Get distinct values for a tag
1. Dump of series (scroll API supports millions of series in response)
1. Get the count of series *per* *value* for a given tag

Query (3) is supported via autocomplete (with a limit) and query (4) can be sort of worked around with the `/tags/findSeries` endpoint. Efficient versions of the other queries would allow us to retire our external metadata storage.

I am prepared to implement, this issue is to gauge interest/design in moving metadata operations into metrictank.

**Comment by Dieterbe** [comment]
>  this issue is to gauge interest/design in moving metadata operations into metrictank.

I think we need to figure out in a bit more detail exactly what our limitations are. Are they purely functional or is the index too slow for what you want to do?

I think it's safe to say we're eager to accept improvements to the index - functional and performance wise. Some of these items may need a broader design conversations, like the scroll api. We have internally had some conversations and brainstorming around an index redesign. The main goals for those was better handling of series churn. Not sure to which extent this is an issue for you too (?) but we would be happy to provide you with our notes on that.

**Comment by replay** [comment]
It sounds to me like a few of the described use cases should already be covered by the current API, specifically the calls described in https://graphite.readthedocs.io/en/latest/tags.html#exploring-tags

Via the URL `/tags/<tag>` you can get the list of distinct values per tag, plus the metric count matching each value. Is this endpoint not efficient enough for what you are trying to do?

**Comment by shanson7** [comment]
> I think we need to figure out in a bit more detail exactly what our limitations are. Are they purely functional or is the index too slow for what you want to do?

I think the index is fast and inexpensive enough. It's just about what methods to expose to keep it fast. For the "Counting" queries (in my tests), pulling back all the raw data significantly slows down the query.

> Some of these items may need a broader design conversations, like the scroll api.

The scroll api isn't necessary if we can make the dump cheap enough to support a million or so results. 

> The main goals for those was better handling of series churn.

Series churn isn't a huge issue for us now that we have pattern-based index pruning. Better support for it could allow us to prune less aggressively maybe

> Via the URL /tags/<tag> you can get the list of distinct values per tag

These endpoints (aside from `/tags/findSeries`) don't seem to support filtering expressions. They also don't support efficient "Counting" versions.
