### ISSUE TITLE
create talk proposal for gophercon

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1584]
we would like to create a talk about the whole story of how we tried to do string interning and why it failed, the goal is to submit that proposal to gophercon in florida and potentially also others.

**Comment by replay** [comment]
This is the document where I'm preparing the CFP submission, please feel free to comment https://docs.google.com/document/d/1joQkPaSNlUYegRwsSWH_XGQw9kWE7BLXZrrE0dsAXgY

**Comment by Dieterbe** [comment]
looks pretty good

**Comment by replay** [comment]
done
