### ISSUE TITLE
meta tag support on bigtable

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1588]
continuation of #1457 
* @replay thinks it should not be much work (1/2 days I think?)
* Dave R and Eldin think it would be good to have this functionality on the platform....
* ... I agree, that enables us also to properly announce it at Grafanacon.
* we need feature parity between our different plugins anyway.

**Comment by replay** [comment]
This is the PR, it is currently blocked on waiting for review: https://github.com/grafana/metrictank/pull/1646

**Comment by replay** [comment]
done
