### ISSUE TITLE
Document how to calculate the minimum kafka retention / replay offset

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1597]
There are a lot of factors which need to be considered when calculating the minimum offset to replay on startup. We should document them somewhere, because it's really easy to forget about one. 

* Time window for restarts due to maintenance
* Max chunk span
* Chunk stale time
* GC Interval
* Reorder buffer duration

Did I forget one?

**Comment by Dieterbe** [comment]
the two places that I know of where we describe this are:
* https://github.com/grafana/metrictank/blob/master/docs/operations.md#data-doesnt-show-up
* #614 

I agree. a dedicated place in the docs to explain this, would be nice.
