### ISSUE TITLE
enforce divisibility of rollup sequences

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1599]
spotted in https://github.com/grafana/metrictank/pull/1594#discussion_r365266313 

per https://graphite.readthedocs.io/en/latest/whisper.html#archives-retention-and-precision

> To support accurate aggregation from higher to lower resolution archives, the precision of a longer retention archive must be divisible by precision of next lower retention archive

we should enforce this.
I don't think there's a hard technical reason to do it, but it would lead to confusing results that are hard to reason about, and i don't even have the energy right now to reason through all these edge cases, so let's save everyone some confusion and enforce it.

**Comment by replay** [comment]
i thought we already do this here https://github.com/grafana/metrictank/blob/12caf3ed2f72639e6a5463c18fd8b50b73f42337/conf/retention.go#L68

**Comment by Dieterbe** [comment]
you're right
