### ISSUE TITLE
include query ID in response data

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1600]
2 use cases in Grafana:
1) set y-axis (or any other viz setting really), based on the query, rather than the returned data (see https://github.com/grafana/grafana/issues/2881)
2) return errors per query. e.g. if you fired 15 similar targets and one of them has a bad argument, it's useful to know which ones.

Note that Grafana does not specify its query id's, and AFAIK it has flexibility in how it assigns metric id's to targets. You can have gaps, they may be out of order, etc.

a query like 'render?target=foo&target=bar` may have had a query F 'foo' and a query C 'bar', I think. (can someone on Grafana team confirm this?)

PS this is something that would be nice in Graphite as well

**Comment by torkelo** [comment]
yea, the query refIds (letters) can be in any order. So the best thing is if the response could just have a query index so Grafana could know which query generated it
