### ISSUE TITLE
flag for limit on auto-guessed chunkspan?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1605]
metrictank guesses chunkspans if not specified. it picks the smallest chunkspan that is still large enough to hold >=100 points.

but this should be constrained based on kafka retention.
e.g. with 7.5h kafka retention, it should not pick chunks bigger than 6h

**Comment by replay** [comment]
this is talking about the situation where metrictank has to create a chunk, and there is no span specified, correct? or when does it guess chunkspans?

**Comment by Dieterbe** [comment]
yes
