### ISSUE TITLE
request deduplication

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1612]
tested master. 045e2f9cd0156e814a582c249a401ef45c5cc732
I spun up docker-dev-custom-cfg-kafka, then ran this:
```
m=metrictank.stats.docker-dev-custom-cfg-kafka.default.input.carbon.metricdata.received.counter32
curl -X POST http://localhost:6060/render -d target=$m -d target=$m
```
it does 2 data requests. the jaeger trace says `num_reqs 2`
also with a small patch to dump out the models.Req
```
diff --git a/api/graphite.go b/api/graphite.go
index ea5cb78d..4c1a04d2 100644
--- a/api/graphite.go
+++ b/api/graphite.go
@@ -11,6 +11,7 @@ import (
        "sync"
        "time"
 
+       "github.com/davecgh/go-spew/spew"
        "github.com/grafana/metrictank/schema"
        macaron "gopkg.in/macaron.v1"
 
@@ -757,6 +759,7 @@ func (s *Server) executePlan(ctx context.Context, orgId uint32, plan expr.Plan)
        span.SetTag("num_reqs", len(reqs))
        span.SetTag("points_fetch", meta.RenderStats.PointsFetch)
        span.SetTag("points_return", meta.RenderStats.PointsReturn)
+       spew.Dump(reqs)
 
        for _, req := range reqs {
                log.Debugf("HTTP Render %s - arch:%d archI:%d outI:%d aggN: %d from %s", req, req.Archive, req.ArchInterval, req.OutInterval, req.AggNum, req.Node.GetName())

```
 I see:
```
metrictank_1    | ([]models.Req) (len=2 cap=2) {
metrictank_1    |  (models.Req) 1.495420973d8914d9b658096f56e442ff 1579199551 - 1579285951 (16 18:32:31 - 17 18:32:31) span:86399s. points <= 800. AverageConsolidator.,
metrictank_1    |  (models.Req) 1.495420973d8914d9b658096f56e442ff 1579199551 - 1579285951 (16 18:32:31 - 17 18:32:31) span:86399s. points <= 800. AverageConsolidator.
metrictank_1    | }
```

**Comment by shanson7** [comment]
This is still an issue and I actually just brought this up in the chat yesterday. The duplication happens in several spots:

1. When resolving a pattern to the underlying series
2. When Fetching the target data (even with PNGroups set)
3. When Fetching the target data, the PNGroup probably doesn't matter (after planning anyway)

**Comment by Dieterbe** [comment]
This is an interesting case, and can manifest itself in a myriad of ways.

Some examples:

* `target=foo&target=foo`: exact same request. seems pointless and unlikely anyone would do this.
* `target=foo.bar&target=foo.*` :one is a subset of the other. still seems rather unlikely, though something like `target=foo.bar&target=sum(foo.*)` seems more likely
* `target=foo&target=sum(foo,bar)`: note that here foo may be fetched twice with different resolitions. E.g. if `bar` has a low raw interval corresponding to a rollup interval of foo. It's arguable here which is better: fetch foo once at high-res and normalize at runtime, or fetch it twice at different resolutions. depends on what's already in the cache..
* `target=foo&target=movingAverage(foo,"10min")` or `target=foo&target=movingAverage(foo.*,"10min")`

For find requests, we can probably trivially dedup identical requests.
For the subset case, we can omit finds for sub-finds (e.g. omit `foo.bar` find if we already have `foo.*` ) but then we'd need to extract the former out of the resultset for the latter. This gets more complicated because we may have multiple layers of redundancy (though, seems unlikely).
For our team at Grafana Labs this is not a priority anyway.

For data requests, we can similarly address the most obvious case easily: as long as plan.Reqs is deduplicated before planning we can elide some of the identical requests (exact same query, from/to, PNGroup, consolidator, etc). Note that if the PNGroup field differs for otherwise identical requests, the requests might still end up being practically identical, but we only know that when we're in the midst of the already complicated planRequests.
This also doesn't solve the cases like where you request the same data twice, but with different froms, such that one is a subset of the other (unless the modified `from` pushes it into a different archive)

Anyway, we haven't tackled this because we haven't seen evidence we would benefit from it.
Perhaps a good first step would be generating some stats that would clue us into which of these cases are actually being hit.

**Comment by shanson7** [comment]
Note: I went down this path a few days ago and have a (hacky) working change for some of this. Deduplicating findSeries is very trivial. Deduplicating the fetch requests is quite a bit harder and has to come after we plan (since planning might mean we do some remote normalization / archive fetching). I similarly ended up stopping where I was since I wasn't sure how many requests actually would benefit from these optimizations and they were non-trivial. 

I think detecting duplication and publishing a few metrics could be done easily enough, though.

**Comment by shanson7** [comment]
I think metrics that would be useful (for both `find series` and `get data` requests):

1. How many requests have duplication
1. How much duplication (i.e. how many requests could we remove or maybe as a percentage of requests?)
1. How much extra data is pulled in (extra `series` and/or extra `points`)
