### ISSUE TITLE
When deleting tagged metrics, delete might also delete more metrics than expected if they have the same name and tags

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1658]
The endpoint to delete tagged metrics takes a name with tags as arguments, such as:

```
curl-d "path=some.series;key=value" "http://localhost:6060/tags/delSeries"
```

This name with tags gets broken down into a tag query, which in this case would be `name=some.series && key=value`. The metrics yielded from that query then get deleted. This means if there's another metric with the same tags, plus additional ones, like for example `path=some.series;key=value;another=tag` it would get deleted too. So we need to filter the results of the tag query to exclude such that have additional tags.

**Comment by Dieterbe** [comment]
Both approaches seem useful.  Maybe we should expose a flag such that users can choose the behavior they want

**Comment by replay** [comment]
I think it's better to just stick to the behavior which graphite implements, this behavior is also more conservative (much less risky) and more intuitive

**Comment by Dieterbe** [comment]
how is adding a flag to enable an optional behavior which is disabled by default "more risky" ? 
also I don't agree with "more intuitive". if i issue a delete for "path=some.series;key=value" then i want all metrics matching that to be deleted. the fact that they are broken down further by other tags doesn't change that. e.g. if i want to delete all metrics for a given datacenter, then the fact that they are broken down further by other tags such as host or OS doesn't change that.

**Comment by shanson7** [comment]
We use this all the time. We have a tag `namespace` and we frequently want to delete all metrics from the namespace. Having to specify all tags makes this very onerous.

Like Dieter mentions, I find the current behavior intuitive. It behaves like all other tag queries (e.g. seriesByTag).

**Comment by replay** [comment]
1) I'm worried somebody reading the graphite docs would assume that this endpoint behaves the same way, only to later find out that it deleted way more than they expected. That's a risk.
2) I think when the argument name is `path` and it takes a `name-with-tags` string, this format implies that the value isn't a query, but a specific path to a metric. It currently doesn't even allow all the normal query operators, only `=`. If we want to allow delete by tag expressions then we should just implement that in the normal way.

We can't just change it to the more conservative behavior without at least offering another endpoint that implements the same functionality, because some users like @shanson7 already depend on it. So I think the best solution would still be to implement `seriesByTag()` in `/metrics/delete`, which would behave like `seriesByTag()` normally does. But after that we can then change this endpoint to only delete the specific metric name with tags that was specified. 
The reason why in our discussion (with @robert-milan and @fitzoh) we came to the conclusion that this endpoint is risky because it technically allows a user to wipe their whole index in one call, but I guess we just have to accept that risk then.

**Comment by woodsaj** [comment]
I think the current behavior for /tags/delSeries is the very close to the behaviour for /metrics/delete, which is that deletes are recursive.  ie. if you pass "some.metric" to /metrics/delete it will delete "some.metric" and "some.metric.foo.bar.baz" and anything else that starts with "some.metric."

so in my opinion, passing `some.metric;key=val` to /tags/delSeries should delete all series that have name=some.metric and key=val.  Though i do acknowledge that for hierarchical series name, you cant/shouldnt have series that are leaf and branch nodes.  ie, if there is a series called "some.metric" there should not be any series called "some.metric.something.else".

With that said, i do feel that we should have a single delete endpoint, '/metrics/delete' and it should support seriesByTag() expressions.   In addition, i think we should add a query param to control whether deletes should consider series that have additional tags that are not used in the query expression.   This would allow you to delete `foo.metric;key1=val1` without also deleting `foo.metric;key1=val1;key2=val2`

**Comment by fitzoh** [comment]
>With that said, i do feel that we should have a single delete endpoint, '/metrics/delete' and it should support seriesByTag() expressions.

Just to make it explicit, removing the `/tags/delSeries` endpoint means an intentional break with the Graphite API.

**Comment by replay** [comment]
We're going to have a larger discussion about what to do about this, because there are a bunch of aspects that all need to be considered
