### ISSUE TITLE
planRequests does not support metrics where rawInterval != interval of first archive in schema

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1679]
consider this schema rule:
```
[foo]
pattern = foo
retentions = 1s:1d,1m:21d,15m:5y
```

a metric may come in and self-declare its (raw) interval to be 5 minutes.
In that case in conf.Schemas it will match the rule `1m:21d,15m:5y` and have a 5min raw retention of 21 days and 1 rollup of 15min:5y.

I believe our current planRequests does not handle cases like this well. Pretty sure the same was true for the older alignRequests code.

**Comment by fkaleo** [comment]
Dieter: one more quick test before merging the PR
