### ISSUE TITLE
Add an option to reject all non-utf8 data

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1728]
We want to be able to reject all data where the metric name or associated tags / values contain non-ASCII chars. Some backends such as Cassandra don't accept all byte values as string chars, which can lead to MT "hanging" because Cassandra keeps rejecting the insert query while MT keeps retrying it.

There should be a flag which makes the input validation stricter and which makes it reject all non-ascii chars.

**Comment by replay** [comment]
Another option would be to only reject data which does not pass the validation by `unicode/utf8.Valid()`: https://golang.org/pkg/unicode/utf8/#Valid
This would be more permissive and it would likely solve the issue of cassandra rejecting strings, although I'm not 100% sure about that.

**Comment by tehlers320** [comment]
@replay i have a question on how this works, more specifically why the archive code block looks like it has a limiter on the amount of retries but the main block does not.

Would something like this be better?
https://github.com/tehlers320/metrictank/commit/abd4d0e11c0ecfecf89935996dd99ee4347afa96

I think its just spinning forever on failures i put a test in just for my sanity with how the code block is today and it goes a long long time on bad data.
https://github.com/tehlers320/metrictank/commit/5b0f9496e51f174722587feee80c0a7d7f438d3d

attempt   914220
attempt   914240
attempt   914260
attempt   914280
attempt   968440
attempt   914300

i took out the sleep but this would block the entire write channel if it made it to 914300 attempts.

**Comment by tehlers320** [comment]
Yeah, i think this confirms it. As soon as the index is spinning its wheels on a bad chunk of data everything else stalls.  _scaled the error to highlight when the rest of metrictank stops operating_
![Screenshot from 2020-04-13 16-09-24](https://user-images.githubusercontent.com/16598119/79161515-3b84ff80-7da1-11ea-8217-2b6ffce118d3.png)

**Comment by Dieterbe** [comment]
We think that we can most likely address this by simply always rejecting non-utf8 identifiers.
Maybe make it optional, but seems like that should always be sane. 
Ascii is suposed to be a subset of utf-8 anyway.

Thoughts anyone? @shanson7 maybe?
