### ISSUE TITLE
release a new docker image

### ISSUE THREAD

**Issue by or-shachar** [grafana/metrictank#1729]
When pulling `raintank/metrictank:latest` image I get the following warning:
```
$ docker pull raintank/metrictank:latest
Image docker.io/raintank/metrictank:latest uses outdated schema1 manifest format. Please upgrade to a schema2 image for better future compatibility. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
```
(docker client 19.03.8)

Is there a place where this image published with schema v2? 
Not sure I'm opening this issue in the right place - who's in charge of publishing the docker image?

**Additional context**
https://docs.docker.com/registry/spec/deprecated-schema-v1/

Thanks!

**Comment by Dieterbe** [comment]
we use ./scripts/build_docker.sh in this repo to build the docker image.

**Comment by Dieterbe** [comment]
this will be fixed as we upgrade our CircleCI images to use newer versions of Go (and at some point, that will include the relevant docker update), which is planned
until then, this doesn't seem like a problem

**Comment by Dieterbe** [comment]
See #1484
