### ISSUE TITLE
panic when a peer is temporarily unavailable

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1740]
We've seen multiple instances of an MT panicking when it got queried while some of its peers were temporarily unavailable. This is one of the messages I saw:

```
2020-03-31 21:30:57.829 [INFO] Proxying to Graphite because of error: unknown function "groupByNode"
2020/03/31 21:30:57 [WARN] memberlist: Was able to connect to <pod name> but other probes failed, network may be misconfigured
2020/03/31 21:30:58 [DEBUG] memberlist: Failed ping: <pod name> (timeout reached)
panic: runtime error: index out of range

goroutine 2765795 [running]:
github.com/grafana/metrictank/api.queryPeers.func1(0xc0317d6660, 0xc02898c480, 0x117d600, 0xc0025e80c0, 0xc0006d25a0, 0xc0006fc560)
        /go/src/github.com/grafana/metrictank/api/cluster.go:559 +0xd20
created by github.com/grafana/metrictank/api.queryPeers
        /go/src/github.com/grafana/metrictank/api/cluster.go:526 +0xb1
```

The running version was `v0.13.1-458-ged6257f`. 

Probably the code shouldn't assume that each group has at least one ready member here: https://github.com/grafana/metrictank/blob/bdd9d1e4de447e11633ba53ee557fbcb5ffe470e/api/cluster.go#L559

**Comment by shanson7** [comment]
Hmm, that code could be more defensive on the inputs, but it's strange that the map passed in had an empty values there (rather than just not having that key).

It's probably coming from here: https://github.com/grafana/metrictank/blob/3e584a8a0869386bdd68f2f1211e8c5475359969/api/dataprocessor.go#L243

In this case, there is a request that needs to go to that shard, but no peer to handle it. I would imagine this *should* fail the request, otherwise we would return partial data.

**Comment by Dieterbe** [comment]
> In this case, there is a request that needs to go to that shard, but no peer to handle it. I would imagine this should fail the request, otherwise we would return partial data.

i haven't dug into the code, but i will say that this is why the `min-available-shards` setting exists.
sidenote: in the case of partial data in the response (due to shards being down but being allowed by the above setting), i'ld like to add a warning to the response metadata (se #1591)

**Comment by replay** [comment]
The `min-available-shards` gets checked in `MembersForSpeculativeQuery()`, so at the time when we're in `getTargetsRemote()` we know that this requirement is satisfied. Considering that it is satisfied I think we should then just not assign that `shardID` to `requiredPeers` and move on.

**Comment by fkaleo** [comment]
Rollout that fix ASAP.
