### ISSUE TITLE
override warmup at runtime

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#175]
sometimes during incidents it can be nice to be able to adjust the warmup period at runtime. for example if long run instances crashed and you have instances running that could serve data, but they refuse to take in requests because they aren't warmed up yet. in that case it may make sense to override warmup to be something lower.

**Comment by woodsaj** [comment]
Can we have runtime confg with as many config options as possible.  Also a simple WebUI for viewing/setting the values would be awesome.

**Comment by Dieterbe** [comment]
another related problem is that sometimes it's hard to tell what the config was an MT instance was launched with, i always end up comparing timestamps of process start and of the config file, but when the file has been changed after start it's hard to tell.
solutions? write config to log is a bit messy, i rather just show current config over http.

**Comment by Dieterbe** [comment]
> Can we have runtime confg with as many config options as possible

one concern i have with this is drift between runtime config and config file, which may lead to issues down the road.  I think i'm more inclined to support config-file reloading so that runtime config is more in sync with what's on disk.  though a lot of parameters cannot be easily reloaded through config file. like chunkSpan, aggSettings, etc so after reload, running config may be != config on disk but that's already the case anyway and it seems less bad then making changes to runtime config through webui that aren't reflected in the chef config.

the only real exception is cluster state: we have to be able to change this value at runtime independently from what's in config file. all the other parameters can go through config file.

**Comment by Dieterbe** [comment]
since we use backfilling, this is not interesting anymore.
since the recommended deployment model now is k8s and env vars, reloading config files doesn't make sense anymore. also k8s has a strong concept of metadata reflecting what is running.
