### ISSUE TITLE
Meta tag inverted filtering not working

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1765]
**Describe the bug**

When trying to exclude certain values of a metatag from a query, the expression seems to be ignored.

Example:
`seriesByTag('namespace=os', 'name=cpu.percent.idle.g', 'stage!=sn2')` returns the series:

```
cpu.percent.idle.g;host=nyalpha1;namespace=os;stage=sn1
cpu.percent.idle.g;host=njalpha1;namespace=os;stage=sn1
cpu.percent.idle.g;host=nyalpha1-temp;namespace=os;parenttimezone=America/New_York
cpu.percent.idle.g;host=nybeta1.bloomberg.com;namespace=os;stage=s0
cpu.percent.idle.g;host=njbeta1.bloomberg.com;namespace=os;stage=s0
cpu.percent.idle.g;host=nydev1;namespace=os;stage=sn2
cpu.percent.idle.g;host=njdev1;namespace=os;stage=sn2
cpu.percent.idle.g;host=ny1;namespace=os;stage=s1
cpu.percent.idle.g;host=ny2;namespace=os;stage=s4
cpu.percent.idle.g;host=nj1;namespace=os;stage=s3
cpu.percent.idle.g;host=nj2;namespace=os;stage=s2
```

Which clearly include series with stage=sn2. The equality query (`stage=sn2`) seems to work just fine:

`seriesByTag('namespace=os', 'name=cpu.percent.idle.g', 'stage=sn2')`

```
cpu.percent.idle.g;host=nydev1;namespace=os;stage=sn2
cpu.percent.idle.g;host=njdev1;namespace=os;stage=sn2
```

And interestingly, a query with both `!=` and `=` behave as if the `!=` weren't there:

`seriesByTag('namespace=os', 'name=cpu.percent.idle.g', 'stage!=sn2',  'stage=sn2')`

```
cpu.percent.idle.g;host=nydev1;namespace=os;stage=sn2
cpu.percent.idle.g;host=njdev1;namespace=os;stage=sn2
```

Changing `!=` to `!=~` still does not fix it.

**Additional context**
We have a meta record per host, if that matters.

**Helpful Information**
Metrictank Version: master
Golang Version (if not using an official binary or docker image): 1.12
OS: RHEL 7

**Comment by replay** [comment]
I'll try to reproduce that. Just to be sure I understand your description correctly:
In your example the tags `host`  and `namespace` are normal tags, the tag `stage` is a meta tag. correct?

**Comment by shanson7** [comment]
>In your example the tags host and namespace are normal tags, the tag stage is a meta tag. correct?

Correct.

**Comment by replay** [comment]
If you get a chance, could you verify that this fixes the issue you saw? https://github.com/grafana/metrictank/pull/1766
