### ISSUE TITLE
groupByNodes() does not return series in a consistent order, Graphite does

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#1768]
When using `groupByNodes()` in Metrictank the order of the returned series is randomized because the order is determined by the order in which keys get read from this map, and Go randomizes the map key order:
https://github.com/grafana/metrictank/blob/487e2d4073ef0e5f332185c311e9988315a4e8ba/expr/func_groupbynodes.go#L73

**Comment by Dieterbe** [comment]
dup of #1767
