### ISSUE TITLE
aliasSub does not support perl-style regex

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1776]
Apparently Graphite supports a query like:

```
aliasSub(metrictank.stats.docker-env.default.api.request.*.latency.median.gauge32,'(?!-[0-9]*-)-[0-9]','')
```
But metrictank does not.

It returns an error `error parsing regexp: invalid or unsupported Perl syntax: '(?!'...`

**Comment by woodsaj** [comment]
PCRE cant be used safely with untrusted users.  Regex queries can be used to cause denial of service attacks (basically consume all the resources on the node handling the regex).

Golang uses RE2.
https://github.com/google/re2/wiki/WhyRE2

RE2 is safe, and significantly more performant than other regex implementations.

**Comment by Dieterbe** [comment]
Note that as of #1778 this error is correctly classified as "bad request", and as such invokes the proxy to graphite (if enabled), and graphite handles it seamlessly, so the user doesn't have to notice anything.
