### ISSUE TITLE
consReq not used for uniqueness in mergeSeries

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1806]
**Describe the bug**

[mergeSeries](https://github.com/grafana/metrictank/blob/75884f2f5f73ccb8010a9f4e9a4561eccb838a47/api/dataprocessor.go#L629) is responsible for taking (functionally) identical series and merging them into a single series. It uses a `segment` as the key. However, this `segment` doesn't include the requested consolidation (from `consolidateBy`). `consReq` can be different from the rollup consolidation used in the case that the configured rollups don't include the requested runtime consolidation. 

For a concrete example, say you had a metric `a` with rollup of `avg` and issue a render request with `target=a&target=consolidateBy(a, 'sum')`.

This should result in 2 series, running on similar fetched data but with different runtime consolidation. However, `mergeSeries` incorrectly merges these together and we get a single series output.

**Comment by Dieterbe** [comment]
I suspect this might also overeagerly merge `target=a&target=a` together

**Comment by shanson7** [comment]
> I suspect this might also overeagerly merge target=a&target=a together

Sure, but in that case the merge is expected since those 2 targets *are* identical. IMO, the fetch layer should be deduplicating those so that shouldn't be an issue.

**Comment by Dieterbe** [comment]
Graphite returns both of them separately, and we try to be compatible with Graphite.
Also, if a user requests the same target twice, I don't think we should try to outsmart them.
IOW we should do the same as graphite and return both of them separately (nothwithstanding that we may choose to optimize the fetches, but that's another story.)

now interestingly, metrictank already does this (not merge them), today...

**Comment by shanson7** [comment]
Right...I was suggesting not fetching them twice, not ignoring the request and returning one result.

**Comment by shanson7** [comment]
I suspect it does merge them, but then the funcs are run independently producing the same result.

**Comment by shanson7** [comment]
Fixed in #1819
