### ISSUE TITLE
Identical series causes double consolidation

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1807]
**Describe the bug**

When processing a query with multiple targets that resolve to the same series and neither modify the datapoints, double consolidation occurs causing very stange graphs.

The issue seems to be that 2 reqs can map to the same series in [executePlan](https://github.com/grafana/metrictank/blob/75884f2f5f73ccb8010a9f4e9a4561eccb838a47/api/graphite.go#L835). If none of the functions applied modify the datapoints, then the output series will also refer to the same underlying series. [plan.Run()](https://github.com/grafana/metrictank/blob/75884f2f5f73ccb8010a9f4e9a4561eccb838a47/expr/plan.go#L322) will call [ConsolidateNudged](https://github.com/grafana/metrictank/blob/75884f2f5f73ccb8010a9f4e9a4561eccb838a47/consolidation/consolidate.go#L24) which updates the datapoint slice backing array. It then updates the first series with the result (setting len appropriately). Then the next series still has it's original len and so says "Better consolidate this one too". But since it refers to the same backing array, we get double consolidation. However, they still have the len of a single consolidation, so halfway through the timestamps reset resulting in strange graphs.

Example: 
simply try to render the same target twice with a time range that would trigger runtime consolidation.

**Comment by Dieterbe** [comment]
hmm. seems to me that runtime consolidation is a write operation just like a function is, and therefore should apply COW.
how does that sound?

**Comment by shanson7** [comment]
That's what I did in the workaround I currently have deployed to prod: https://github.com/bloomberg/metrictank/pull/92/files#diff-ba835aec8460638bbf49f526041c0605R32
