### ISSUE TITLE
MetaTagRecords causes huge number of alloc objects

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1816]
While investigating reducing MT latency/CPU usage, I was looking at allocated objects to try to take load off the Garbage collector. Seems the primary user for our read nodes is coming from MetaTagRecords. Here is pprof output for 2 heap captures diffed between 12 minutes:

```
(pprof) alloc_objects
(pprof) top10
Showing nodes accounting for 528840179, 89.35% of 591863814 total
Dropped 529 nodes (cum <= 2959319)
Showing top 10 nodes out of 70
      flat  flat%   sum%        cum   cum%
  85330794 14.42% 14.42%  150770781 25.47%  github.com/grafana/metrictank/expr/tagquery.(*MetaTagRecord).GetMetricDefinitionFilter
  82126421 13.88% 28.29%  143882107 24.31%  github.com/grafana/metrictank/expr/tagquery.(*expressionEqual).StringIntoWriter
  65571063 11.08% 39.37%   65571063 11.08%  github.com/grafana/metrictank/expr/tagquery.(*expressionEqual).GetMetricDefinitionFilter
  61755686 10.43% 49.81%   61755686 10.43%  strings.(*Builder).Write
  48038394  8.12% 57.92%   96136362 16.24%  github.com/grafana/metrictank/vendor/github.com/Shopify/sarama.(*MessageSet).decode
  47772052  8.07% 65.99%   47772052  8.07%  github.com/grafana/metrictank/vendor/github.com/Shopify/sarama.(*partitionConsumer).parseMessages
  44823228  7.57% 73.57%   44823228  7.57%  github.com/grafana/metrictank/mdata.(*ReorderBuffer).Add
  44250158  7.48% 81.04%   95448226 16.13%  github.com/grafana/metrictank/vendor/github.com/Shopify/sarama.(*MessageBlock).decode
  42505543  7.18% 88.23%  338495824 57.19%  github.com/grafana/metrictank/idx/memory.newIdFilter
   6666840  1.13% 89.35%    6666840  1.13%  github.com/grafana/metrictank/vendor/github.com/tinylib/msgp/msgp.ReadStringBytes
```

The top 4 all stem from MetaTagRecords. At a glance, it seems that a string is built per record to use as a map key. Seems like this could be improved to not allocate so much.

**Comment by shanson7** [comment]
85330794 alloc objects in 12 minutes is over 118k alloc objects/sec.

**Comment by replay** [comment]
I think that's because when querying by two expressions of which one is based on a meta tag, then the meta tag one gets used as a filter to filter down the result set which is generated based on the other one. To build that filter function all meta records which match the meta tag expression get looked up, and each meta record instantiates a filter function.
I think probably to best way to avoid these allocations would be to only instantiate each metaTagRecord's filter function once and then cache it in the metaTagRecord data structure for reuse. A metaTagRecord never gets modified anyway, on swap/upsert calls they get re-instantiated.

**Comment by shanson7** [comment]
Ah, interesting. So  in our case we have 10's of thousands of meta records, each one is just a single `tag=value` expression. Are you saying that if the meta tag is `stage` and there was a query with `name=A, stage=B` that all meta records with the `stage` tag get stringified to match against the result set for `name=A`?

**Comment by replay** [comment]
> Are you saying that if the meta tag is stage and there was a query with name=A, stage=B that all meta records with the stage tag get stringified to match against the result set for name=A?

Not exactly, all meta records which have a meta tag matching the expression `stage=B` would get looked up. Then, based on each meta record's expressions, a filter function would get generated for each of them. This filter function then gets called for each metric in the result set from the expression `name=A` to decide whether this metric shall end up in the final result set.

**Comment by shanson7** [comment]
Would the example change you linked above require some locking?

**Comment by replay** [comment]
> Would the example change you linked above require some locking?

Ah sorry, yes it would, or an atomic pointer swap

**Comment by shanson7** [comment]
Removing stale tag as this is a pretty large number of allocations and might be one of the reasons that we have 20-40 second GC cycles (measured from calls to `runtime.GC()`, so a lot of that is background but we still see some effect from it).

Could someone review this as a fit for `customer-impacting` so it doesn't get marked stale again?

**Comment by replay** [comment]
I added an optimization in the PR #1898 which should reduce the allocations significantly in scenarios where the meta tags used by a query are made up only of meta records which all use equal-expressions.

I think it would be possible to further reduce the allocations per query by caching the filter functions which are used to filter the result set down by meta tag expressions, but that would then increase the memory usage by a bit due to the additional cache and it would put some load on the GC because the cached objects would be references to functions, that's why I didn't implement this yet. Let's first see how the PR #1898 performs and then decide whether this cache is really necessary.

**Comment by shanson7** [comment]
Rolled it out a few days ago, haven't done another heap profile yet though

**Comment by replay** [comment]
> Rolled it out a few days ago, haven't done another heap profile yet though

Cool, I'm curious to hear how it's going

**Comment by shanson7** [comment]
Here is a new diff across 10 minutes:

```
(pprof) alloc_objects
(pprof) top10
Showing nodes accounting for 228483230, 79.20% of 288501993 total
Dropped 504 nodes (cum <= 1442509)
Showing top 10 nodes out of 83
      flat  flat%   sum%        cum   cum%
  41695254 14.45% 14.45%   41695254 14.45%  github.com/grafana/metrictank/vendor/github.com/Shopify/sarama.(*partitionConsumer).parseRecords
  41498083 14.38% 28.84%   41793000 14.49%  github.com/grafana/metrictank/vendor/github.com/Shopify/sarama.recordsArray.decode
  40403573 14.00% 42.84%   40403573 14.00%  github.com/grafana/metrictank/mdata.(*ReorderBuffer).Add
  31009881 10.75% 53.59%   31009881 10.75%  github.com/grafana/metrictank/vendor/github.com/tinylib/msgp/msgp.ReadStringBytes
  19165953  6.64% 60.23%   19165953  6.64%  github.com/grafana/metrictank/idx/memory.metaRecordFilterBySetOfValidValues
  16712073  5.79% 66.03%   67251190 23.31%  github.com/grafana/metrictank/mdata.(*AggMetric).add
  10705364  3.71% 69.74%   10705364  3.71%  github.com/grafana/metrictank/mdata/chunk/tsz.(*bstream).writeByte
   9313376  3.23% 72.96%    9313376  3.23%  github.com/grafana/metrictank/mdata/chunk.New
   9208371  3.19% 76.16%   11559772  4.01%  bytes.(*Buffer).grow
   8771302  3.04% 79.20%   25007291  8.67%  github.com/grafana/metrictank/mdata/chunk.encode
```

I don't see any of the `tagquery` stuff showing up anymore and total allocations seems much, much lower.

**Comment by replay** [comment]
Cool, great to see that ^^.

Should I close this issue?

**Comment by shanson7** [comment]
Resolved
