### ISSUE TITLE
crng failure tolerance docs section unclear

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#1822]
https://grafana.com/docs/grafana-cloud/hosted-metrics/graphite/data-ingestion/#failure-tolerance-with-carbon-relay-ng
this section essentially says "you can do hot/cold" but gives no clues on how to do that. what configuration? should you put a loadbalancer in front? which one do we recommend?

**Comment by replay** [comment]
If somebody wants to stick to free open source solution, something like Corosync/Pacemaker should work well. Otherwise any proprietary load balancer which can handle TCP connections and implement liveness checks would work, such as Cisco, Kemp, etc.

**Comment by replay** [comment]
basically there are just many different ways how hot/cold can be implemented, that's why i omitted that part of the specific implementation

**Comment by Dieterbe** [comment]
we need to add suggestions to the doc, and add the it to the diagram
