### ISSUE TITLE
Expose more internal data to operators

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1839]
We would like to expose more data about the internal state of Metrictank to its operators. This has come up a number of times and you can see those discussions in the below references PRs and issues.

After some discussion in our last community call we decided that extending the current public or internal endpoints isn't the best solution. Most of the internal endpoints are not setup to fan out across the cluster, and we didn't think that exposing this data through the public endpoints was a good idea.

It was suggested that we create a new internal endpoint collection, something like `/admin` or `/ops`. We could then expose useful information to the operator to help them debug issues, or just get a snapshot of state. Further segregating these new endpoints from existing endpoints has a number benefits:
* No confusion about modifying existing endpoints
* Could add more controls if necessary
* Don't need to expose them to the `public` users of the system

As an example, we would like to add something similar to the following:
* `/xxx/metricDefinition` - This would take either a `series` or an `MKey` and return all available information in multiple formats (`msgp`, `json`, `whatever`).

Open for discussion. @Dieterbe @shanson7 @replay @fkaleo 

See also: #1829, #1115, #1527, #1565

**Comment by robert-milan** [comment]
List of proposed items to expose / functionality to make available (feel free to comment below and I will update this list):

- MetricDefinition / Archive information for a given MKey or possibly also series name (or pattern)
- Chunk Cache information

**Comment by Dieterbe** [comment]
Sounds good. Let's do "/admin". we can implement the things we need on an as-needed-basis.

**Comment by Dieterbe** [comment]
mauro also said "makes sense to me"
