### ISSUE TITLE
we're hitting cassandra when we shouldn't

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#184]
![mem-cass-huh](https://cloud.githubusercontent.com/assets/20774/14068772/d23b1ba4-f45b-11e5-80f6-a976c51d7e8d.png)

requests for <3h of data shouldn't need mem+cass.
I think this could be due to https://github.com/raintank/raintank-metric/blob/8897ef4f8f8f1a2585ee88ecadee501bfc1a4139/metric_tank/aggmetric.go#L231-L235

we should probably instrument each case with statsd and find out if that specific case is happening.

**Comment by Dieterbe** [comment]
possibly related: request handling changed the moment a newly promoted primary starts saving chunks.
https://snapshot.raintank.io/dashboard/snapshot/8npltHNJWA8wHLOdlVk3nHnWTTmLj1RQ

**Comment by woodsaj** [comment]
I dont see any problem with   https://github.com/raintank/raintank-metric/blob/8897ef4f8f8f1a2585ee88ecadee501bfc1a4139/metric_tank/aggmetric.go#L231-L235

Firstly, it is not possible to have an aggmetric that has no chunks.  The aggemtric is only created when we first see data, and therefore the first chunk is also created.   An aggmetric can never have all chunks deleted, the chunks  can only be pushed out of the ring buffer by newer chunks.  If the aggmetric doesnt exist at query time, then we just query cassandra.  https://github.com/raintank/metrictank/blob/master/dataprocessor.go#L317

So if a series is no longer receiving data but is still in the index, 1 of two things can happen.

1. the aggmetric doesnt exist (in which case we query cassandra) 

2. if the aggmetric is still in memory but has not seen any data during the requested range then we correctly return an empty list and cassandr is not queried.  https://github.com/raintank/metrictank/blob/8897ef4f8f8f1a2585ee88ecadee501bfc1a4139/metric_tank/aggmetric.go#L238-L253

if 1, then we would need to check `if from < (time.Now() - chunkspan*numChunks)" and only if it is should we query cassandra.  *we would also need to consider how long the MT node has been up for.

**Comment by woodsaj** [comment]
it should also be noted that if we if we start filtering the queries that are sent to cassandra as outlined above, we would also need to enforce metric-max-stale to be at least numchunks * chunkspan.
