### ISSUE TITLE
Metrictank Survey

### ISSUE THREAD

**Issue by robert-milan** [grafana/metrictank#1851]
We have almost no information about who is using Metrictank. I propose we put together a survey. All questions / fields / sections will be completely optional. We could also provide a tool to gather information (os / MT version / whatever). The tool would only collect the information and create a file, nothing that will automatically send the information to us. That way the user could edit it before they send it to remove possibly sensitive information (or information that their company does not want to share).

Survey properties:
- Normal data (company / location / whatever)
- Technical data (different sections for MT, deployment models, infrastructure, etc...)
- Operator data (how difficult is it to operate, typical problems, do you know where to get help?)

We also provide links to resources they can leverage for assistance at the top of the survey. This also relates directly to growing the Metrictank community.

Thoughts?

@shanson7 @RichiH @replay @fkaleo @Dieterbe @woodsaj

**Comment by shanson7** [comment]
I think this is a great idea.

I am a big fan of multiple choice, with an "other" short form option where feasible. Long form entries are difficult to aggregate results and mean looking through each answer to try to categorize.

**Comment by robert-milan** [comment]
> I think this is a great idea.
> 
> I am a big fan of multiple choice, with an "other" short form option where feasible. Long form entries are difficult to aggregate results and mean looking through each answer to try to categorize.

Yeah, I like multiple choice too. Does anyone have an idea for a platform / tool we can use to launch the survey and aggregate results ?

**Comment by Dieterbe** [comment]
How will we know which people to send the survey to?

**Comment by RichiH** [comment]
We discussed this during https://drive.google.com/file/d/19mvS_-cQwy1gZ3B2dl42q3O7L4AmfC8E/view?usp=sharing , I think in the last third.

**Comment by Dieterbe** [comment]
my notes from the video:
* mainly driven to know what to focus on wrt packaging. which distros and versions
* make it opt-in. 
* ask something like did you try MT and not succeed, if so, why
* spread as far as you can, via social media accounts of all developers, etc
* package hooks can be used to advertise our survey and can also be used to advertise community call, ML, etc.
* don't run a survey more than once every 2 months
