### ISSUE TITLE
metrictank dropping metrics above 100k per second

### ISSUE THREAD

**Issue by Bharat786** [grafana/metrictank#1856]
I am sending about 293400 metrics per second to metrictank but the grafana dashboard query : 

derivative(metrictank.stats.$environment.$instance.input.carbon.metricdata.received.counter32)derivative(metrictank.stats.$environment.$instance.input.carbon.metricdata.received.counter32)

is showing only about 100k to 150k per second the incoming metrics and no metrics are shown to be dropped.i am not able to figure out the problem as why metrictank is only able to handle so less metrics.

i am running metrictank with carbon input and a cluster of 3 cassandra at the backend.
RAM : 125 GB
HARD DISK : 132 GB
CPU CORES : 16

<img width="1662" alt="Screenshot 2020-07-09 at 14 35 24" src="https://user-images.githubusercontent.com/22790903/87020429-75736f80-c1f1-11ea-9934-852bd0ee65ad.png">

**Comment by Dieterbe** [comment]
is either the metrictank process,or the process sending the metrics maxing out cpu?
how do you send the data? have you confirmed that if you send the data elsewhere (e.g. into netcat) that the volume is as expected?

**Comment by Bharat786** [comment]
There are 16 CPU CORES in my system and both the metrictank and graphite-stresser(sending graphite metrics to the metrictank : LINK : https://github.com/feangulo/graphite-stresser ) are not consuming much of the CPU's as you can see from the below images :

metrictank cpu consumption :
<img width="1617" alt="Screenshot 2020-07-10 at 02 20 15" src="https://user-images.githubusercontent.com/22790903/87089783-9325f080-c254-11ea-98dc-6bc9b0c09371.png">

system metrics : 
<img width="1630" alt="Screenshot 2020-07-10 at 02 23 35" src="https://user-images.githubusercontent.com/22790903/87089818-a042df80-c254-11ea-8da7-857fb126b22e.png">

metrictank and stresser(java process) -> linux top command output : 
<img width="886" alt="Screenshot 2020-07-10 at 02 22 52" src="https://user-images.githubusercontent.com/22790903/87089889-b9e42700-c254-11ea-9b2b-83268997aaf0.png">

Metrictank is only able to handle 150k metrics per second.

1) what can be the possible reasons?
2) how i can scale metrictank for upto 40 million metrics per minute?

**Comment by Dieterbe** [comment]
in order to be sure the problem lies with metrictank, you have to be able to exclude your stresser.
you should measure the output rate of the stresser when you feed it into a different socket. seeing that it's doing 107% cpu, it might be maxed out.
