### ISSUE TITLE
Is there any Python example to send a metric point through Kafka mdm?

### ISSUE THREAD

**Issue by eleleme** [grafana/metrictank#1861]
Before submitting a feature request please review other open requests and issues to see if someone else has already requested this feature.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Dieterbe** [comment]
not that i know of.
you can submit a message in 2 formats: MetricData and MetricPoint.
the former is a messagepack encoded schema.MetricData structure. (see the definition in schema/metric.go)
should be fairly easy to replicate this in python.

what problem are you actually trying to solve? an alternative would be to run mt-gateway (which writes to kafka), and use the scripts from https://github.com/grafana/grafanacloud-hosted-metrics-graphite-sender-example to send data to mt-gateway
