### ISSUE TITLE
Add configurable timeout for index ops

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1870]
A very expensive request came into our Metrictank cluster yesterday and ended up taking down the entire cluster because it kept on running long after the origin request timed out. There should be a time out and/or context association for these  operations so that expensive requests can be canceled without needing to kill the node.

**Comment by replay** [comment]
That's the same as described here, right? https://github.com/grafana/metrictank/issues/514

**Comment by shanson7** [comment]
Yeah, seems the same. We had a large outage last night due to a very expensive meta tag request

**Comment by shanson7** [comment]
I have a WIP change here to timeout index ops (along with a change to avoid relinquishing write lock): https://github.com/grafana/metrictank/compare/master...bloomberg:avoid_locked_index

This is a considerably easier and nearly as effective change to make.

**Comment by Dieterbe** [comment]
as this is specific to (meta) tag stuff, @replay can you check that out? at a glance, it looks good to me.

**Comment by replay** [comment]
I like how this adds a timeout to the `TagQueryContext.Run()` method, this part looks good.

The change with `.tryAddMetric()` is interesting. So basically this tries to not release the write lock if possible, only if not releasing it would result in a dead lock situation then it releases it temporarily to resolve the dead lock, correct? That's a nice idea, I'm not sure if that results in a large benefit though, what prompted you to make this change? Did you see a lot of go routines stuck at trying to re-acquire that lock there?

**Comment by shanson7** [comment]
> The change with .tryAddMetric() is interesting. So basically this tries to not release the write lock if possible, only if not releasing it would result in a dead lock situation then it releases it temporarily to resolve the dead lock, correct?

Yes, that's correct

> That's a nice idea, I'm not sure if that results in a large benefit though, what prompted you to make this change? Did you see a lot of go routines stuck at trying to re-acquire that lock there?

Yes, this completely locked up our entire cluster when we had a rogue read query. Specifically because of this code: https://github.com/grafana/metrictank/blob/master/idx/memory/write_queue.go#L76

The write_queue lock being held while the index lock is being waited on caused ingest to block up.

Ultimately, I think these 2 changes should be split into different PRs.

**Comment by shanson7** [comment]
PR is still active
