### ISSUE TITLE
Tag queries with "metatag does not exist" style expression extremely slow

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1871]
Tag queries with an expression of the form `metatag=` (i.e. `metatag` does not exist) incredibly slow. Caused index lock ups. the example in this case was `[namespace^=b stage=]` where `stage` is the meta tag. We have about 50k meta tag records with `stage` in it.

**Comment by replay** [comment]
IIRC when planning the order in which the expressions get evaluated the non-meta tags always get preference over the meta tags. Furthermore, expressions asking for the absence of a tag can only be used as filters and not to build the initial result set. This means the index would first evaluate `namespace^=b` and build a result set from that, then filter it down by `stage=`. 

Are there are a lot of metrics where `namespace^=b` matches?

**Comment by shanson7** [comment]
> Are there are a lot of metrics where namespace^=b matches?

Yes, lots and lots.  But it takes about 120ms for `tags/autoComplete/values?tag=namespace&valuePrefix=b` to complete (including network time and all that).  But about 1.2 hours for `tags/autoComplete/values?expr=stage%3D&tag=namespace&valuePrefix=b` to complete. That's the issue.
