### ISSUE TITLE
Helm chart and sharding

### ISSUE THREAD

**Issue by kennux75** [grafana/metrictank#1882]
Hello,

We deployed MT in our kubernetes cluster, and I made an helm chart to automate the deployment of MT statefulsets, carbon-relay-ng and graphite. 
I tried to set up the following architecture:
- 1 write statefulset with one pod
- 2 read statefulset with 2 pods
- 1 query statefulset with 1 pod
- 1 carbon relay ng
- 1 graphite.

If I configure my yaml values file with only one shard like:
_sharding:
  shardA: "*"_
everything works fine. 

But it I configure 2 shards or more, I've got issues to diplay metrics after the 2 first "chunk spans".
For instance, 8 partitions in kafka: 
_sharding:
  shardA: "0,1,2,3"
  shardB: "4,5,6,7"_
There is a loop in the statefulset template for each shard group, deploying 1 write pod per shard group, etc. setting the MT_KAFKA_CLUSTER_PARTITIONS and MT_KAFKA_MDM_IN_PARTITIONS env variables.

Do you have an idea what could be the issue? I can provide templates and values file if needed.

Thanks a lot.

**Comment by shanson7** [comment]
> I've got issues to diplay metrics after the 2 first "chunk spans".

What sort of issues? Are they just not showing up? If you storage schema indicates that only 2 chunks should be kept in memory, then the read instances will drop older chunks and assume that they can be read from the datastore if needed. If the write shards are not persisting the values to the datastore, then I would expect the behavior where you can't see the older data.

**Comment by kennux75** [comment]
Hi Shanson!

Thanks for your reply.
The metrics randomly not showing up. Indeed, in my storage schemas, I let the default value for numchunks which is 2.

The thing is, if I have only one shard "topics = metrics and partitions = *", everything is working fine with the default parameter. So I think the write shard can write values to cassandra. 
But if I have 2 write shards of 2 partitions (topics = metrics and partitions = "0,1" and partitions = "2,3"), the read shards seems to have a pb to read values in the datastore. But I cannot see any store or idx errors in the dashboard.

**Comment by kennux75** [comment]
Hello,

I made some tries with an "empty" cluster, not receiving any metrics, except from mt-fake-metrics, 10m/s every 10sec, and 30m/s every 30 sec, with a storage schemas like:
[fake30]
     pattern = fake30.*
     retentions = 30s:7d
[default]
      pattern = .*
      retentions = 10s:7d

With a kafka topic with 4 partitions, instances in pairs, 2 write instances consuming partitions "0,1", and "2,3", and read instances consuming same partitions. From graphite, I query 2 "query" instances which have the "read ones" as peers.
I can reproduce the issue, which is after the 2nd chunk in memory, not all metrics are showing up, just a part of it. 
I cannot reproduce this issue with 1 write instance and 1 read instance consuming partitions "*".

There are some writes in cassandra, there are a few items in write queue but for a short time, far away from the queue limit. I'm not sure with a rate around 7hz, cassandra is the cause. I think I missed something in the configuration, but I cannot figure out what.
If you have an idea, thanks a lot :)

**Comment by Antoine-Auffret** [comment]
Hello @kennux75 and @shanson7 ,

> The metrics randomly not showing up. Indeed, in my storage schemas, I let the default value for numchunks which is 2.

Do you have both carbon-in and kafka-mdm-in enabled. If that's the case, you should disable carbon-in beacause this is the source of the metrics "randomly" not showing up. See #1440 for details.

@woodsaj could you explain us in details how the partition is carbon-in works when using metrictank in a cluster ? What's a shardGroup ? Why can't we set the same partition for different nodes like with kafka-mdm-in "partitions" ? What's the best way to use 4 MT with 2x replication like in the docker-cluster image with only carbon and without kafka ?

I'm trying to set up a metrictank cluster with a cassandra cluster and carbon-c-relay with 3 billion metrics per day in.

Thanks in advance for your support and any help you could give us.

Sincerely

**Comment by Dieterbe** [comment]
> Why can't we set the same partition for different nodes like with kafka-mdm-in "partitions"

IIRC you can. that said I would advise against running a cluster with carbon input. to me cluster implies HA. but the problem with carbon is, as soon as a MT instance needs to restart it needs to replay data to fill its chunks, but you can't do that with carbon.  kafka as a WAL solves that problem.

**Comment by Antoine-Auffret** [comment]
Thanks for your answer @Dieterbe.

I've done some more testing with carbon partitions to understand how MT's partitions work.

I'm currently using docker-cluster image as a base. In this image there is 4 MT (2x replication) and use 8 kafka partitions.
The partitions 0,1,2,3 are used for MT0 and MT1 whereas partitions 4,5,6,7 are used for MT2 and MT3.

For instance : https://github.com/grafana/metrictank/blob/b8bb52605ce405b361c54e2ae5f02c0e00362b6c/docker/docker-cluster/docker-compose.yml#L23-L24
When using carbon, I set up partition 0 for MT0 and MT1 and partition 1 for MT2 and MT3 using env var MT_CARBON_IN_PARTITION to override metrictank.ini configuration
https://github.com/grafana/metrictank/blob/b8bb52605ce405b361c54e2ae5f02c0e00362b6c/docker/docker-cluster/metrictank.ini#L271

Unfortunately when sending metrics with mt-fakemetrics using carbon (half metrics to MT0 and the other half for MT1, replicated in MT2 and MT3), the metrics in grafana are randomly not showing up. However it works perfectly using kafka.

What's the source of this issue ? Do you have a idea to fix this ?

Thanks again for your precious informations.

**Comment by shanson7** [comment]
> Unfortunately when sending metrics with mt-fakemetrics using carbon (half metrics to MT0 and the other half for MT1

Metrictank assumes that each instance is getting the same metrics. If you are only sending half to one instance and half to the other, this data is not being replicated. You would need to send *ALL* partition 0 metrics to *BOTH* MT0 and MT1. Ditto for partition 1 metrics and MT2/MT3.

**Comment by kennux75** [comment]
Hi @Antoine-Auffret ,

Thanks for your reply. I knew this case - I opened the #1440 ;).
I've double checked my configuration on kube, and I can confirm I only have kafka-mdm-in enabled.

The thing is that the data are not really show "randomly", but not every metrics are shown after a period "2xshortest chunkspan" (2x20mn for 10sec metrics interval, 2x1h for 30sec metrics interval etc)
After a period of 2 chunks, just a part of the oldest one appears in grafana, while the newest one filling up, and so on.
I checked cassandra errors to see if there are some errors, but nothing, and this problem does not appear with no shardGroups.

**Comment by Antoine-Auffret** [comment]
> > Why can't we set the same partition for different nodes like with kafka-mdm-in "partitions"
> 
> IIRC you can. that said I would advise against running a cluster with carbon input. to me cluster implies HA. but the problem with carbon is, as soon as a MT instance needs to restart it needs to replay data to fill its chunks, but you can't do that with carbon. kafka as a WAL solves that problem.

If you replace in the docker-cluster metrictank.ini file graphitemon:2003 by localhost:2003 to send MT metrics to metrictank rather than graphitemon, metrictank.stats.* are completely messed up and appear randomly.
https://github.com/grafana/metrictank/blob/dba010cfc881a4f5b3751d67c3c121cd8e5b9993/docker/docker-cluster/metrictank.ini#L210
Why ?
