### ISSUE TITLE
Upgrading to newer version of metrictank.

### ISSUE THREAD

**Issue by bharat404** [grafana/metrictank#1894]
Hey,

Currently i am using v0.13.1 version of metrictank and wants to upgrade it to the latest version that is v1.0.can anyone suggest what all i should take care of while upgrading to the newer version and will only changing the binary will be sufficient for the upgrade.

Thanks.

**Comment by Dieterbe** [comment]
Hi, the changelog lists all breaking changes for each release.

**Comment by bharat404** [comment]
Thanks.
