### ISSUE TITLE
Metrictank hanged, not serving any queries

### ISSUE THREAD

**Issue by spunpale** [grafana/metrictank#1896]
**Metrictank hangs while in operation**
* metrictank (version: v0.13.1 - runtime: go1.11.4) running on a Debian server. 
* No heavy querying (~30-40 qps)
* metrics-in of ~60k points/s using the carbon-input plugin

[cpu_profile_mt-hanged-24-08-2020.zip](https://github.com/grafana/metrictank/files/5149904/cpu_profile_mt-hanged-24-08-2020.zip)
[stack_trace_mt-hanged-24-08-2020.zip](https://github.com/grafana/metrictank/files/5149906/stack_trace_mt-hanged-24-08-2020.zip)

**Comment by robert-milan** [comment]
Hi, can you please provide more information?

- How many Metrictank instances are you running?
- Were you performing any actions other than ingesting metrics and querying metrics?
- Are you querying Metrictank directly or going through Grafana?
- Were your queries working and then stopped working?
- Approximately how many series are being queried at a time?
- How many series are active in your Metrictank instance?

**Comment by spunpale** [comment]
Hi, please find the requested information below.

> * How many Metrictank instances are you running?

1 primary node with carbon-in, along with a Cassandra cluster for storage.
> * Were you performing any actions other than ingesting metrics and querying metrics?

no.
> * Are you querying Metrictank directly or going through Grafana?

using a graphite-web data-source through Grafana. 
> * Were your queries working and then stopped working?

yes.
> * Approximately how many series are being queried at a time?

~20 reqs, max 300 series per req, ~60k points per req

<img width="536" alt="Screenshot 2020-09-01 at 5 01 05 PM" src="https://user-images.githubusercontent.com/70516541/91844254-bc6f6580-ec74-11ea-9571-868837452339.png">
<img width="1066" alt="Screenshot 2020-09-01 at 5 00 18 PM" src="https://user-images.githubusercontent.com/70516541/91844192-a1045a80-ec74-11ea-8fe0-9783df7e9c10.png">

> * How many series are active in your Metrictank instance?

~4.5M
<img width="407" alt="Screenshot 2020-09-01 at 5 03 44 PM" src="https://user-images.githubusercontent.com/70516541/91844439-1c660c00-ec75-11ea-853e-4a8dab9ca313.png">
