### ISSUE TITLE
Packages for Debian Stretch & Buster

### ISSUE THREAD

**Issue by D3luxee** [grafana/metrictank#1918]
Hi,
i was looking for the metrictank packages at https://packagecloud.io/raintank/raintank and it seems that metrictank gets only pushed into the wheezy & jessie repositories, both debian versions are already EoL.
The carbon-relay-ng for example is already available on stretch and buster.

It would be nice to get the packages pushed to stretch and buster repositories aswell.

Thanks

**Comment by Dieterbe** [comment]
I think the GL infra team is going to help us with packaging. ping @malcolmholmes @Duologic

**Comment by D3luxee** [comment]
@Dieterbe this is still relevant i think.

**Comment by Dieterbe** [comment]
sure but this needs someone to do the work and file a PR.
