### ISSUE TITLE
Tsdb-gw gone?

### ISSUE THREAD

**Issue by deniszh** [grafana/metrictank#1928]
Hello!
Could you please suggest software to put metrics to Kafka? I used https://github.com/raintank/tsdb-gw/ before, but now repo is gone for some reason. 
https://github.com/grafana/carbon-relay-ng is not supporting V2 format (and I didn't manage to make it work at all)

**Comment by replay** [comment]
Metrictank now has the `mt-gateway` utility to replace `tsdb-gw`: https://github.com/grafana/metrictank/tree/master/cmd/mt-gateway

**Comment by deniszh** [comment]
Ah, missed that somehow. But I do not see carbon interface there. :(

**Comment by Dieterbe** [comment]
for a carbon input, carbon-relay-ng works much better as it's designed for carbon. tsdb-gw was too specific to our internal infra (e.g. auth using grafana.com), mt-gateway replaces it as a more generic tool, but you're right [we should clean up our docs](https://github.com/grafana/metrictank/issues/1717) and it also doesn't have auth (yet). What kind of auth are you looking for? do you need integration with any particular system?

[carbon-relay-ng has on open issue to add the new MetricPoint format](https://github.com/grafana/carbon-relay-ng/issues/442), btw. i envision it would use the same library as mt-gateway.

**Comment by deniszh** [comment]
Auth is not neeeded in our usecase, you're right. But lack of MetricPoint not making carbon-relay-ng drop in replacement for tsdb-gw either.

**Comment by D3luxee** [comment]
In my opinion mt-gateway needs some kind of authentication to provide the multi tenancy that tsdb-gw provided.
Without a tool that resolves authenticated queries to a specific set of org id's the multi tenancy of metrictank is gone.

Without tsbd-gw we had to give direct access to metrictank and the users had to define the x-org header in the grafana datasource, but this would also grant them access to any org they want.

Authentication + setting the x-org header was and is the main use case of tsdb-gw for me.
