### ISSUE TITLE
keep semantic versioning (new v1.0.0 tag?)

### ISSUE THREAD

**Issue by D3luxee** [grafana/metrictank#1937]
Hi,
you should keep semantic versioning for all releases. Semantic versioning requires MAJOR.MINOR.PATCH the latest release of metrictank does not use semantic versioning.
This causes issues because go modules depend on semantic versioning of tags:

```
[]$ go get github.com/grafana/metrictank@v1.0
go get github.com/grafana/metrictank@v1.0: no matching versions for query "v1.0"

[]$ go get github.com/grafana/metrictank@v0.13.0
go: downloading github.com/grafana/metrictank v0.13.0
```

https://github.com/golang/go/wiki/Modules#semantic-import-versioning

**Comment by Dieterbe** [comment]
so we can solve this by creating a new tag v1.0.0 that points to the same commit that v1.0 already points to?

**Comment by D3luxee** [comment]
Yes, i think so.

**Comment by Dieterbe** [comment]
done. let me know (reopen) if that doesn't work.
cheers.
