### ISSUE TITLE
High priority / backlog on metric flush

### ISSUE THREAD

**Issue by D3luxee** [grafana/metrictank#1954]
**Describe the bug**
We experience a high backlog on metric flushes, the priorities are going up to 10 minutes.
This causes issues for some monitoring systems using metrictank as datasource.
The question is if there is some performance issue or if thats the expected performance of metrictank?

**Additional context**
- All write queues summed up are at 15 million metrics on flush.
- We ingest ~200k unique metric points per second.
- Metrics Active: idx = 13.97 Million, tank = 3.65 Million
- MetricData as metric format
- The backlog builds up on both nodes primary and secondary for the same partition set, but it takes the primary much longer to process the backlog.

**Helpful Information**
Metrictank Version: 1.0
Golang Version: 1.11.4
OS: Debian 10 / Buster
Cassandra Version: 3.11.3
Kafka Version: 2.3.0

Metrictank Hardware:
4 Nodes, 2 Primaries each with 8C/16T CPU and 377G Memory

Kafka Hardware:
3 Nodes per DC, each with Raid10 24x SAS 10k, 10C/20T and 94G Memory

Cassandra Nodes:
6 Nodes, each with 8x SSD configured as JBOD, 8C/16T and 64G Memory
num_tokens 8 and 1 replica

**Architecture**
![2020-12-16-122152_834x725_scrot](https://user-images.githubusercontent.com/10009528/102344732-a2942d00-3f9c-11eb-8ee1-e12697538e03.png)

**Comment by Dieterbe** [comment]
typically this happens when write queues are not sized correctly.
when the queue fills up it will block ingest. this is by design.
you can either make your queues bigger, or increase write concurrency to cassandra. (may or may not be very helpful, depends on how long it takes for the queue to fill up and drain)
you can look at the write queue panel on the dashboard to see this.

**Comment by D3luxee** [comment]
The write queues are at 5.5 Million each and write concurrency is set to 24.
On metric flush the queues wont exceed 2 million. This might be a bit inaccurate because we only have a resolution of 30sec on metrictanks metrics.
![2020-12-16-161356_743x755_scrot](https://user-images.githubusercontent.com/10009528/102367245-d467bc80-3fb9-11eb-96db-6ebbcaeaf975.png)

I think there was some kind of formula to calculate the min queue size, but i have to search it in the docs. But i might be wrong with it.

**Comment by Dieterbe** [comment]
if not the queues, the other reason may be that your cpu's get maxed out when it starts sealing all chunks and adding them to the write queue

**Comment by D3luxee** [comment]
It seems you're right, the primary which has to handle more metrics reaches 85% and builds up the backlog.
The second primary which has to process less metrics only has 50% cpu usage and no significant backlog.

Maybe we can reassign some partitions to distribute the metric load more evenly.
I will close this ticket after our measures were successful to confirm that it was the cpu usage.

Thanks for your help

**Comment by D3luxee** [comment]
I could confirm that it was in fact a cpu bottleneck, we've rebalanced the metrics more evenly and even a big flush does not cause backlog anymore.

Thanks for your help
