### ISSUE TITLE
Move to go modules for dependency management

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1985]
In the next release of golang (1.17) support GOPATH builds is going to be removed. Migrating to modules seems the way to go to future proof this project.

**Comment by Dieterbe** [comment]
i've tried it once or twice and both times it became painful and i gave up, but i also wasn't super motivated. 
FWIW i didn't see a clear deprecation notice on https://golang.org/doc/go1.17 and at least this seems to work fine still:
```
GO111MODULE=off make
```

**Comment by Dieterbe** [comment]
#1999

**Comment by shanson7** [comment]
I think this will need to be done eventually.
