### ISSUE TITLE
Conf parsing changes fail to parse regex

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#1990]
**Describe the bug**

In #1989 some changes were made to the conf parse code. In particular [this commit](https://github.com/grafana/configparser/commit/f5c9e475c7f0f1f8ea64b45bd9c1d226d01d391f) seems to disallow any strings with `[]` in it. In our case, storage-aggregations has some settings like:

`pattern = ^[^;]+\.max(?:;|$)`

which used to parse fine and now we get:

`2021-06-25 09:18:24.738 [FATAL] can't read storage-aggregation file "/etc/metrictank/storage-aggregation.conf": invalid line "pattern = ^[^;]+\\.max(?:;|$)": [ and ] are reserved for section headers and this contains additional non-section header data`

If I comment out the lines from that commit, everything works as expected. Perhaps this check should only look at chars up to the first `=` (or the whole line if no `=` exists)?

**Helpful Information**
Metrictank Version: master
Golang Version: 1.15.11

**Comment by shanson7** [comment]
Note: I can't seem to create issues on https://github.com/grafana/configparser

**Comment by Dieterbe** [comment]
> Note: I can't seem to create issues on https://github.com/grafana/configparser

ah, probably because it's a fork.
anyway yeah this is a legit bug. will fix it
