### ISSUE TITLE
orgid -1 -> 0

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#260]
can we make the "special org", currently at id=-1 , id=0 instead?
this help to encode orgid's, we can make them uints and save space

the only use of -1 that i'm aware of is for "globally visible data" that any org can see.
and we currently don't use 0. (we do use 1 for the admin org), so this should be pretty easy

**Comment by woodsaj** [comment]
That is fine with me

**Comment by Dieterbe** [comment]
k, this is low prio though, will probably address this at some point down the road.

**Comment by woodsaj** [comment]
So we cant use 0, as the metrics get rejected for being invalid.

https://snapshot.raintank.io/dashboard/snapshot/OM37FFnSW8MVfadRv1u13mJjR2ewR8ED?refresh=30s&panelId=1&fullscreen&orgId=2

**Comment by woodsaj** [comment]
So as discussed in the PR, we need to make the PublicOrgId configurable, but lets default to 0

**Comment by Dieterbe** [comment]
I don't understand how you reason from the rejected-invalid problem to your proposal of "make the PublicOrgId configurable, but lets default to 0", as that would still not work because the default still wouldn't work.
seems simpler to just allow orgid=0 in the validation rule.

**Comment by woodsaj** [comment]
I dont like the idea of removing the validation rule.  It would be too easy for a bug to result in the orgId being the zero value.  And this would result in all users being able to see the data being inserted.

So just make it configurable.  a default of `0` can just be treated as public metrics being disabled.

**Comment by Dieterbe** [comment]
#883
