### ISSUE TITLE
panic service http request

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#306]
```
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: 2016/09/06 19:28:05 http: panic serving 10.240.0.40:44232: runtime error: index out of range
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: goroutine 1647370369 [running]:
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: net/http.(*conn).serve.func1(0xc9cc36e080)
Sep 06 19:28:05 metrictank-1-production metrictank[7585]:         /usr/local/go/src/net/http/server.go:1389 +0xc1
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: panic(0xa641e0, 0xc82000e050)
Sep 06 19:28:05 metrictank-1-production metrictank[7585]:         /usr/local/go/src/runtime/panic.go:443 +0x4e9
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: main.mergeSeries(0xca75693800, 0x28, 0x28, 0x0, 0x0, 0x0)
Sep 06 19:28:05 metrictank-1-production metrictank[7585]:         /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/dataprocessor.go:392 +0x7f1
Sep 06 19:28:05 metrictank-1-production metrictank[7585]: main.Get(0x7efcec69c138, 0xc9550d2750, 0xc87d6f40e0, 0x7efced9aacd0, 0xc8202701c0, 0x7efced9aadf8, 0xc820074410, 0xc82015d7a0, 0x2, 0x2, ...)
Sep 06 19:28:05 metrictank-1-production metrictank[7585]:         /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/http.go:343 +0x1e53
```

```
root@metrictank-1-production:~# metrictank -version
metrictank (built with go1.6.2, git hash 0.5.2-41-g39bfcc8)
```

**Comment by woodsaj** [comment]
https://github.com/raintank/metrictank/blob/master/dataprocessor.go#L392

@Dieterbe this is panic'ing because when there are multiple metricDefs for the same series (ie when the interval changed) the two (or more) datasets have a different number of points. 
These points are fetched with `out, err := getTargets(store, reqs)` and "reqs" is from `reqs, err = alignRequests(reqs, aggSettings)`

If the requests are all aligned, shouldnt they all have the same number of datapoints?

**Comment by Dieterbe** [comment]
> If the requests are all aligned, shouldnt they all have the same number of datapoints?

i believe they should. i'll look into this.

**Comment by woodsaj** [comment]
my guess is that `[]` is being returned for series that have no chunks in memory and none in C* for the requested time range. ie, the metricDef exists in the metric but the metrictank instance has not ever seen that metric since it started.

**Comment by Dieterbe** [comment]
> my guess is that [] is being returned for series that have no chunks in memory and none in C* for the requested time range

even if getSeries returns no points, getTarget() runs everything through fix() which will assure the right format of the output series (quantized points), and in that case that would be a series of all nulls, but with correct timestamps and number of points.

I think it's something related to the interval being passed to fix(), or perhaps consolidate() or alignRequests().

**Comment by Dieterbe** [comment]
i will investigate whether this still happens in prod. but i don't think so

**Comment by Dieterbe** [comment]
i just looked at 76 cases of mt-read restarts in our prod env, and none were caused by `runtime error: index out of range`. also if/when this happen again, it won't bring down an instance anymore. as the call to mergeSeries happens in the same goroutine as the macaron handler,which will log the panic and move on. (this was introduced after the above mentioned changes)
