### ISSUE TITLE
re-evaluate kafka compression

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#312]
now that sarama is patched to support compressed offsets.
want to understand cpu vs mem vs disk io, effects on kafka/metrictank performance better.
can easily be done with raintank-docker and fakemetrics.

**Comment by woodsaj** [comment]
The compression was fixed in Sarama.v1.10.1, which we are now using.

We can benchmark this now.

**Comment by Dieterbe** [comment]
with our MetricPoint format for 0.9 i did some testing between comp=none and comp=snappy.
snappy was the clear winner. https://github.com/grafana/metrictank/pull/876#issuecomment-377916632
in the future, once our formats stabilize we can potentially do more testing of other compression algorithms.
