### ISSUE TITLE
CassandraStore refactor

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#350]
Below is a WIP list of issues with CassandraStore and some suggestions to solve some of them. 
@woodsaj @DanCech feedback please :)

first, terminology sync.
CRR =  cassandra read request
CWR = cassandra write request

Here's a list of things to address:
## 1) currently CRR's are not timed out

the actual cassandra select queries are subject to a timeout, but i'm talking about the time between issuing a CRR and starting a cassandra query for it.  if cassandra is slow, cassandra Search() requests will hang while:
a) it puts the CRRs in the queue (which blocks while queue is full)
b) the CRR advances through the queue at a potentially slow speed
c) the cassandra query is being executed (of course)

if cassandra can't keep up with the rate of requests cassGetDuration will just grow from seconds to minutes to many minutes.  no one is going to wait >10s so we shouldn't even start to process a CRR that's too old, and introduce a CRR timeout.
## 2) naive queue-putting slows down all requests

if there's 10 concurrent Search() calls and they each try to put elements in a readqueue (full or not), due to the undefined insertion order they will all slow down, since they will all more or less be able to put a few items in, but wait while others are putting in items before they can finish putting in all their CRR's. it would make more sense for Search requests to either put all their CRR's in the queue, or wait with all of them. (or put in none of them if it's not able to queue all its CRR's in a reasonable timespan, eg. a bit less then whatever the CRR timeout is)
## 3) confusing metrics.

currently we have:
cassGetDuration: CRR time spent enqueuing + in queue + executing queries
cassBlockDuration: CWR time spent enqueing + in queue 
cassPutDuration: time executing an insert query (erroreous or otherwise)
suggestion:
- rename cassBlockDuration -> cassPutWaitDuration
- rename cassPutDuration -> cassPutExecDuration
- split up cassGetDuration into cassGetWaitDuration (enqueing + in queue) and cassGetExecDuration (exec of the select query), e.g. similar to puts.
- if queries (inserts or selects) are retried, that is within the gocql library and abstracted away within CassandraStore so cass{Get,Put}ExecDuration could jump up if queries are being retried.  I think this the right way. we may want to instrument read/write retries also, though. (within gocql).
## 4) partial responses.

2 reasons for this:
a) some select queries may timeout or fail due to $random_error, while others may succeed.
b) the CRR timeout suggestion from 1) may selectively drop some CRR's, especially as the timespan between popping off from the queue becomes large between early CRR's and later CRR's from the same Search() (e.g. because cassandra is slow to process what's in the queue)

so we end up with partial response data. we collected some chunks, but are missing some.
when a user gets a partial graph, that is:
x) at best, still very useful (because maybe he has all the data he needs to draw conclusions)
y) at worst, very confusing and misleading. and removes confidence in the system if not clearly marked as a partial response (e.g. with a warning icon in grafana)

we could potentially try to adress b) by treating all CRR's for a given Search() as one unit of work, and either do all of them or none of them.  I think this is an interesting idea and would also help solve 2), but the main question is, is this approach not too crude to properly control the workload and the various safety mechanics (timeouts etc) e.g. because some unit of work might be 1 CRR while another is 10000, not to mention fairness (1 users big request may block 1000's of others) although we could leave it up to the operator to set the appropriate request restrictions and aggregations so that there's a known upper limit to the CRR's.

anyway, even if we do this that still leaves a) so a situation where we have only a fraction of the needed chunks is unavoidable.  So what should we do in this case? Two suggestions:
a) return a http 500 with no data at all
b) return partial data and have grafana display a warning that the view is incomplete. this can probably be easily achieved with a special response header, that we should be able to pass through graphite-api.
also: should we react differently based on whether the portion is small, half, or large?
## 5) messy shutdown behavior

when metrictank shuts down, there is no mechanism to:
a) finish in-progress read requests (while not accepting new incoming requests)
b) finish pending cassandra writes (and time them out with a fat warning that makes it to the log before the process exits)
## 6) Search() bad query processing

Search() sends all queries to cassandra first before it starts reading any of the results, and then does the result processing in serial.
we can respond to the user faster by:
a) processing results earlier (e.g. when they come in)
b) processing the results in parrallel

it's tempting to solve a and b by just extend the querying goroutine to also process the result when it comes back. but then we can have situations where cassandra underutilized if the MT has a cpu spike and all routines are busy processing, but nothing is querying.  OTOH if cpu was the bottleneck there's no point querying cassandra and accumulating more responses than what we can process. except maybe if there's a temporary cpu spike and cassandra is running close to max workload. then piling up the workload may push it over the edge.
it may make sense to start with this approach and switch to separate querying and processing workers 
(pushing the query results into another queue of a pipeline so that separate processing workers can operate on query responses while the querying routines move on to the next query) later if we see the need to.

An additional problem seems to be that if the query response is paged (and we do additional queries while Scan()ing, this approach makes it much more likely to trigger query timeouts

I think this is about our current level of understanding of this problem
- queries being held open much longer than needed is probably the problem. the proposed solution will probably fix this.

as per @woodsaj : 

> paging (e.g. executing queries while Scanning() in the serialized-after-all-results-came-in step) makes this much worse. default gocql pagesize is 5000 . and each 28day period is a different query. for us, with our 30min raw chunks we only do max `28x24x2=1344 (days * hours per day * chunks per hour)` "rows" per query

so we shouldn't trigger paging - and btw , for other people deploying MT, as long as their chunks are >9min, they won't trigger paging. we could make pagesize configurable though)
but anyway paging should not be an issue if we refactored the result processing.

quote from @woodsaj : 

> I have confirmed that when it comes to Paging, C\* treats columns in wide-rows like rows.  So if you perform a range query on a row (as we do) and the response has more then PageSize columns, they will be paginated.  
> What i think the likely problem we are encountering resource contention issues in MT.  The cassandra client protocol sends multiple queries over the same TCP connection.  However the responses need to read serially.  Anytime there is a delay reading a response from the network and writing it to internal buffers, all queries on the same TCP connection will also experience that delay.  
> So, decreasing the PageSize should in theory help ensure individual responses can be processed fast enough.  We can also try increasing the number of connections to cassandra.

seems to me like if we agree that the described refactoring the result processing is a good first step at optimizing the user experience, and will likely also address the timeouts, then we should just go for it and see how it fares. thought @woodsaj @DanCech ?
## 7) some things that have come up. some actionable, some are more for pondering.

a) do we need different session/conn pool for readers vs writers?

b) 
per AJ:

> One other improvement I noticed we could add is to use the TokenAwareHostPolicy (https://godoc.org/github.com/gocql/gocql#TokenAwareHostPolicy) to ensure that queries are routed to the C\* node that has the rows locally.  This prevents C\* from having to forward the query to another node if it doesnt have the data.

this seems like the right thing to do.

note that for writes we already send same-metric-key chunks into the same queue and the same worker (to maintain order). would it make sense to tie cassandra connections to workers? if so it might make sense to also consistently route read requests to read queues/workers as well.

c) do we still need an explicit circuit breaker as suggested in #147 ? if things get slow, I think the timeouts will essentially act as a "nuanced/selective" circuit breaker. if cassandra is down entirely, gocql might just handle that fine. needs a bit more research.

**Comment by woodsaj** [comment]
Write now metrictank is controlling the request concurrency to cassandra. However, i think we should remove the global concurrency limits and just send queries to cassandra allowing cassandra to apply the concurrency limits through its own concurrent_reads setting.  This allows us to control concurrency based on Cassandra capabilities.  If we need to increase concurrency to meet due to query timeouts we can do so by simply adding more Cassandra nodes without needing to re-configure metrictank.

However, to ensure individual users dont overwhelm the cluster with really large queries, we should instead impose a concurrency limit per request.  So for example, we limit each request to 5 concurrent queries.

**Comment by Dieterbe** [comment]
asked for some advice on the ML. https://groups.google.com/forum/#!topic/gocql/CbERzX_zvOc
