### ISSUE TITLE
verify whether our cassandra compression settings make sense

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#355]
In particular it includes lzo4 compression which might consume extra resources for no extra benefit. Benchmark with and without

**Comment by Dieterbe** [comment]
awoods
11:54 AM
compression settings can be changed on an existing cluster.  So there is no urgency to test it right now
11:54
https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsConfigCompress.html?hl=compression
dieter
11:54 AM
we've had lz4 enabled since we started. I never put much thought into it, not sure if @awoods did, but now i wonder if it makes sense given that we already have our own advanced compression
11:55
ah ok, so then we leave the ticket open, but move it post 0.7
awoods
11:56 AM
compression is enabled by default (lz4).
dieter
11:56 AM
@awoods any idea whether changing compression at runtime comes with costs or tradeoffs?
11:57
i just suspect that the lz4 algorithm will spend time trying to compress, but won't find redundant data to compress, or at least not enough to be worthwhile.
awoods
11:57 AM
it should be negligible.  sstables are write-once.  So changes to the compression will only happen after a compaction.
dieter
11:58 AM
ok so i will remove the milestone from that ticket and we can do it later
awoods
11:59 AM
https://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsWhenCompress.html  it is hard to say.  while our rows all do have the same number of columns (chunk T0 timestamps)  our data probably cant be compressed much further.  But the compression may help with the overheads of storing the column names (timestamps)
docs.datastax.com
When to compress data
Compression is best suited for tables that have many rows and each row has the same columns, or at least as many columns, as other rows.

**Comment by woodsaj** [comment]
The easiest way to test if sstable compression actually leads to reduced on-disk size (and therefore better reads and writes) is to take some compressed SSTABLES and use sstableloader to write them to a new table that doesnt have compression. then compare the sizes.
