### ISSUE TITLE
forceable chunk saving

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#357]
MT should have an option to force saving of all chunks and then exit
this facilitates restarts in single node instances with minimal data loss.
right now we have to wait for new data to come in which causes chunk saves, but this new data may take too long to arrive, which means we have to wait longer before we can restart.  so unless we control the kafka offset to go back in time and replay old data (which btw will also take longer if we had to wait longer), we will lose more data if we restart MT with offset = latest.

NB: setting chunkMaxStale very aggressively to combat this problem doesn't seem like a good solution because during normal operation it would cause chunks to be saved too eagerly so that we can't add points to it anymore.

**Comment by woodsaj** [comment]
forcefully saving will only limit dataloss if you shutdown at the very beginning of a chunkspan.  To prevent data loss in aggregated series this would mean restarting on the 6hour boundaries.  However it usually takes 20minutes or more to save all chunks every 6hours.  Would it be practical to wait 20minutes for a shutdown to complete?

I am not sure how viable this approach is.  I think that the only 2 options for limiting data loss are discussed in https://github.com/raintank/metrictank/issues/275
