### ISSUE TITLE
automatically pushing dashboard updates to grafana.net

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#395]
I would like our circleCI setup to automatically update the dashboard in grafana.net (https://grafana.net/dashboards/279)

but, we need to have different versions:
* a version representing the latest dashboard in `master`
* a version for each release (`0.5.8`, the upcoming `0.6`, etc)

I'm hoping we can automate this process and use the `Description` field on https://grafana.net/dashboards/279/revisions ?

@woodsaj thoughts?  @daniellee does this idea sound sane? any pointers ? is there an api we can use for this with an auth token?

**Comment by daniellee** [comment]
A version for each release is no problem but I'm not sure we have a good way of handling a version representing the latest dashboard in master. We can upload a new dashboard for the latest master but it would end with a lot of revisions and whichever dashboard happened to be uploaded last would be the one most people would download.

Are you thinking something like the DockerHub tags with latest + newest version: 

https://hub.docker.com/r/raintank/metrictank/tags/

**Comment by Dieterbe** [comment]
> whichever dashboard happened to be uploaded last would be the one most people would download.

can we create links such as:
```
https://grafana.net/api/dashboards/279/revisions/v0.5.8/download
https://grafana.net/api/dashboards/279/revisions/v0.6/download
```

if so, I think that's fine. 


> Are you thinking something like the DockerHub tags with latest + newest version:

i only see latest. not sure what is newest. but yeah something like that.

**Comment by daniellee** [comment]
I meant the `latest` tag and the tag for the latest version, e.g. `0.5.8-45-g3b59d4b`.

`https://grafana.net/api/dashboards/279/revisions/v0.5.8/download`

To achieve this, it would mean adding tagging support for dashboards which would make sense for dashboards that are connected to products and Grafana apps. At the moment, we only have support for revision number.

**Comment by Dieterbe** [comment]
The alternative of course, is that we turn the current dashboard (279) into one that tracks master, and so whenever you pull from that, you get latest master.  and for every release version, we create a completely new dashboard in gnet with its own page and id and all that. it seems a little "spammy"  though.  But we will run into the same problem with other software I think (consider snap, or nginx, apache, whatever.  If those come out with a new version that have a different stats tree)

**Comment by Dieterbe** [comment]
@cinaglia thoughts on this? aware of anyone else auto-pushing dashboards and marking versionned tags alongside master?
