### ISSUE TITLE
support for rewrite / overwrite / seek back in time

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#511]
the main reason that we haven't implemented this feature is not because it's impossible technically, it's just that it would be non-trivial and relatively expensive (need to retrieve any old chunks, decode them, rewrite them, etc), e.g. much more expensive than the cost of just adding normal points.

So we could implement the support for it, and perhaps it should also come with a certain cost, billing wise.

**Comment by replay** [comment]
I'm not sure what feature does. What does it rewrite?

**Comment by Dieterbe** [comment]
currently metrictank does not allow out-of-order data. e.g. any point for a given metric must have a higher timestamp than the last point. otherwise the point is not accepted and classified as "too old".

the feature discussed here would allow overwriting 1 or many points for a series, at any arbitrary position

**Comment by DanCech** [comment]
I don't think we need to get that involved off the bat, at least for the voxter use-case they would be ok with the ability to set the "head" of a given series back to an earlier date (and discard any existing "later" data) so that they could start sending data from that point in time.

**Comment by woodsaj** [comment]
can we simplify this by having the /metrics/delete endpoint also delete aggMetrics/cache when the series are removed from the index.  This would then allow users to immediately start streaming old data.  The only caveat is that they would need to send data starting from a chunk boundary, else the first partial chunk received would be saved to cassandra overwriting the previously saved complete chunk.

**Comment by DanCech** [comment]
yeah, I was thinking maybe an endpoint that would accept a timestamp to "reset" the series to so it can enforce that the timestamp is on a chunk boundary and alleviate the potential for surprised users

**Comment by replay** [comment]
So if that reset comes in, that would have to be replicated to all the metrictanks in the cluster somehow, similar like the persist messages. To clear the according chunks for the `AggMetrics` and `ChunkCache`s of the other metrictanks.
