### ISSUE TITLE
cancelation support for all index calls

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#514]
let's say you do a curl request for index.json  this will take a long time.
When you control-c curl, it'll kill the connection/request, but the server will keep working on it, it won't cancel any routines working on the index operation, nor any pending RPC requests to peers. MemoryIdx.List will keep running (both on local peer and any remotes), holding a readlock on the index, iterating the index, and building a result set.

This problem is also in other places, such as our render request handling (which invokes findSeries and getTargets in a non-cancellable way), index find, index delete (this one holds a full lock), etc.
But I propose to just tackle one specific case first, we can do the others later.

This will probably involve https://golang.org/pkg/context/

**Comment by fkaleo** [comment]
Perhaps reuse code at https://github.com/grafana/metrictank/pull/1370

**Comment by Dieterbe** [comment]
This should probably wait until
* #1646 
* #1550 
are done.
