### ISSUE TITLE
better error message when kafka's offset doesn't exist anymore

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#520]
I don't know all the details (is this in mdm-in or in cluster notifier handler) but @woodsaj reported via https://github.com/raintank/ops/pull/404

**Comment by woodsaj** [comment]
If kafka does not have the offset we are expecting dont think there is any way we can recover. So panic'ing seems like the correct behavior.

**Comment by Dieterbe** [comment]
Happened again today. This time nothing happened in kafka that would cause it to discard offsets after advertising them. And it led to a MT crash as shown below. Likely the cause this time is MT shutting down before it had a chance to properly initialize during startup.

```
[Sarama] 2017/04/06 10:44:30 kafka: error while consuming m-12574-S-ops/4: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
[Sarama] 2017/04/06 10:44:30 consumer/m-12574-S-ops/4 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa1be51]

goroutine 1218 [running]:
github.com/raintank/metrictank/input/kafkamdm.(*KafkaMdm).consumePartition(0xc420019450, 0xc420010b27, 0xd, 0x4, 0x138c18a94)
    /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/input/kafkamdm/kafkamdm.go:260 +0x701
created by github.com/raintank/metrictank/input/kafkamdm.(*KafkaMdm).Start
    /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/input/kafkamdm/kafkamdm.go:216 +0x31e
```

I think two things need to happen:

1) make the error nicer. print out something like "offset 12345 does no longer exist. Cannot consume. exiting", instead of a nil-pointer induced panic that doesn't even say which offset no longer exists
2) we should review the code with a focus on shutdown during init, and check whether that can also cause the nilpointer and fix it.

**Comment by woodsaj** [comment]
I think i know what causes this. 

Kafka is configured to keep log segments for logRetention ms.  Each log segment is log.segment.bytes in size (default 1gb).  The logic used by kafka for cleaning up old log segments is very simple. It just looks for any log segments that have a last modified time less then now-logRetention.

So what i think is happening is that MT starts up and starts consuming from the oldest offset, ie the beginning of the oldest log segment.  Before MT is able to read all of the oldest log segment, it is being deleted.

**Comment by woodsaj** [comment]
So this problem should only occur within the first few minutes of runtime while MT is replaying the backlog.  And crashing and restarting is still the only way to handle this issue.  

We can try and reduce it by tuning kafka (setting log.segment.bytes to a much lower value).

**Comment by Dieterbe** [comment]
> We can try and reduce it by tuning kafka (setting log.segment.bytes to a much lower value).

i don't like this idea. more, and smaller files make the filesystem less efficient; and also it would just make this scenario less likely, but not stop it.

If what you explained is what really happens (haven't found out yet, needs more research) and is part of normal behavior, then I don't think MT should crash. rather it should just retry (e.g. do another request to consume from oldest, whatever oldest is at that point), but only once or maybe a configurable (but typically low) amount of times. if it happens again, then it can crash.

**Comment by woodsaj** [comment]
> rather it should just retry (e.g. do another request to consume from oldest, whatever oldest is at that point)

it cant do that, as it will result in gaps in the chunks.  The only safe way to handle this is to drop all chunks in memory and start consuming from oldest again.  And the easiest way to do that is to just restart.

**Comment by Dieterbe** [comment]
ok so the only actionable item remaining is just a better fatal error when dieing.

**Comment by Dieterbe** [comment]
with 0.7.4-160-gd2c63ec8 : 
```
[Sarama] 2017/10/11 19:24:19 kafka: error while consuming m-12574-M-ops/3: kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
[Sarama] 2017/10/11 19:24:19 consumer/m-12574-M-ops/3 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa80e2d]

goroutine 1705 [running]:
github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).consumePartition(0xc4207b84b0, 0xc420014eb7, 0xd, 0xc400000003, 0x19465ce88)
	/home/ubuntu/.go_workspace/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:296 +0x70d
created by github.com/grafana/metrictank/input/kafkamdm.(*KafkaMdm).Start
	/home/ubuntu/.go_workspace/src/github.com/grafana/metrictank/input/kafkamdm/kafkamdm.go:216 +0xe0
```

**Comment by woodsaj** [comment]
the panic is due to trying to read `msg.Value` when msg is nil.

```
		case msg := <-messages:
			if LogLevel < 2 {
				log.Debug("kafka-mdm received message: Topic %s, Partition: %d, Offset: %d, Key: %x", msg.Topic, msg.Partition, msg.Offset, msg.Key)
			}
			k.handleMsg(msg.Value, partition)
			currentOffset = msg.Offset

**Comment by Dieterbe** [comment]
that would only close the consumption goroutines that run into trouble, and leave the others intact.
(it's possible, based on timing of segment deletes, where the consumers are, etc that some partitions run into this problem and others don't)
 in particular it would also keep the MT process running. 

I think something like #748 is better
