### ISSUE TITLE
Some thoughts on tagging

### ISSUE THREAD

**Issue by DanCech** [grafana/metrictank#532]
I have been doing a bit of thinking about how to efficiently support tagging within metrictank, and how we can add support for it in a way that will scale out and won't require major re-architecture in the backend.

My thought is to create a set of indexes that allow us to map tags to series, roughly as follows:

Using the metrics2.0 example:

```
{
    host: dfs1
    what: diskspace
    mountpoint: srv/node/dfs10
    unit: B
    type: used
    metric_type: gauge
}
meta: {
    agent: diamond,
    processed_by: statsd2
}
```

We start by creating a unique series "key" based on the tags that are present, much like carbon-tagger does, so we end up with something that looks like (tags sorted alphabetically):

`host=dfs1.metric_type=gauge.mountpoint=srv/node/dfs10.type=used.unit=B.what=diskspace`

But the exact format doesn't matter as long as it uniquely identifies any given set of tags, though a reversible format is advantageous later on (see below).

For each tag name (`host`, `what`, etc) we create a table that maps values to series keys, so for the above we'd have:
```
tag_host
value | key
dfs1  | host=dfs1.metric_type=gauge.mountpoint=srv/node/dfs10.type=used.unit=B.what=diskspace
```
```
tag_what
value | key
diskspace | host=dfs1.metric_type=gauge.mountpoint=srv/node/dfs10.type=used.unit=B.what=diskspace
```
etc

Storage optimizations here could be made by maintaining a separate mapping of numeric ids to tag values to series keys to reduce the amount of data duplication.

We could use a single table with `tag | value | key` columns, but splitting by tag should be an easy way to help things scale out as the number of tags and/or series increases.

Once we have this structure, we are able to map a query to series by lookup in these tables, say we get a query with `host=dfs1 AND what=diskspace`:

We `SELECT key FROM tag_host WHERE value='dfs1'` to get all the series with `host=dfs1` and `SELECT key FROM tag_what WHERE value='diskspace'` to get that list of series, then the logical AND is simply the intersection of the resulting sets.  OR can similarly be implemented as the union of the sets, etc.

Now we have a set of keys (in this case just the one) we can retrieve the data for those series and return them to the client.  If we use a tag to series key mapping that's reversible (as above) then we can easily return the full set of tags for each series by decoding the series key.

Metadata is trickier, and would need to be stored associated with individual measurements if we wanted to be able to track and return it over time (since it shouldn't impact the series key).  I don't have a good idea for how to do that efficiently yet.

All feedback appreciated!

**Comment by woodsaj** [comment]
> We start by creating a unique series "key" based on the tags that are present

We already do this, the key is an md5 hash of metric+concatenated string of sorted tag k:v pairs.  
see: https://github.com/raintank/schema/blob/master/metric.go#L89

> For each tag name (host, what, etc) we create a table 

given the set of tag names is unbounded, creating a table for each one seems like a bad idea to me.

Is a RDBMS even the right backend for this?   Do we want to add a RDBMS as a dependency for metrictank?

**Comment by DanCech** [comment]
Actually after discussion and looking at the mt cassandra index with @replay yesterday it looks like we have all the information we would need to store there already (the mapping from series id to a set of tags).

What we would need on the querying side is to load that data into a data structure that allows us to efficiently answer the question "what is the set of series ids that have value x for tag y?", then as noted above we can do set operations to perform the boolean logic between different tag specifications.

The major work required will really be in figuring our how to expose the ability to query by tag in grafana, and how to pass it back through graphite api.  My current thoughts on graphite api would be that we'd need to extend the internal concept of a series to include a set of tags, and provide ByTag equivalents for the various functions that work on node indexes (or possibly just allowing them to accept a tag name in place of a node index), and providing a mechanism to define a SeriesList based on a set of tags rather than a node glob.  Similarly in the grafana frontend we would need a way to select tags & values rather than nodes.

**Comment by Dieterbe** [comment]
would like to support autocomplete and partial matches, at least prefix matches. (e.g. `host=dfs*`).maybe a radix tree would be appropriate for that . note patterns can be deconstructed in an AND of its parts (`host={web,dfs}*`. we probably should not worry about supporting patterns with a wildcard prefix (e.g. `host=*123`)

**Comment by Dieterbe** [comment]
a few libraries that might be applicable when building an index.
* https://github.com/dgryski/go-trigram ( a favorite of mine, I recommend studying it in detail. it is well built and an interesting learning experience)
* https://github.com/dgryski/go-postings
* https://github.com/dgryski/go-bloomindex, based on http://bitfunnel.org/strangeloop/ which is a great talk and idea.
