### ISSUE TITLE
processing library standard timeseries format

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#629]
I wanted to benchmark some different approaches to modeling timeseries data, for two reasons:

1) our expr library needs to be consumable by multiple projects - specifically grafana in addition to MT
2) I've been thinking it may make sense for MT to change its internal representation of timeseries so it uses less memory

MT currently uses slices of `uint32,float64` pairs, see https://github.com/raintank/metrictank/blob/c2d3ca0a7d98bff2c97ff8923d0358f44ae2bdd3/api/models/series.go#L15
and https://github.com/raintank/schema/blob/master/point.go#L4

Grafana uses something a bit more complicated, mostly because of how it represents null values https://github.com/grafana/grafana/blob/master/pkg/tsdb/models.go#L57

carbonzipper and carbonapi use a slice of floats and just tracks the interval as a property. see https://github.com/go-graphite/carbonzipper/blob/master/carbonzipperpb3/carbonzipper3.pb.go#L43-L49
also note the `IsAbsent  []bool` property which describes for the points in `Values    []float64 ` whether they are actually valid (known) or not.  this is more effective than pointers to floats and whatnot, because the overhead is only 1 bit per point. (pointers are 8B and come with dereferencing overhead)

So first, we currently use math.NaN (which is a valid value in go , part of the IEEE float spec) to refer to null, even though i believe traditionally they are used more commonly to describe the output of division by zero and so on, which is not a number. we give it an additional use to convey "unknown value".

On one hand it think we could make graphite better, by -in our implementation- distinguishing between null and NaN (both in json output, in grafana's visualization, etc), but this seems like a low prio item that not many people will find valuable. To do that, we could do an approach like carbonapi, with an additional array of bools. I can also add that to the benchmarks and see the effect of that.

for now, though i just wanted to point you guys to https://github.com/Dieterbe/dataprocessexp where i tried the two basic approaches (explicit timestamps for every point vs single step value and points are just float values), and also an interface based approach, where callers of the library (grafana, MT) could use whatever datatype they want, as long as it is iterable via a simple interface implementation.
this approach seems to be too slow though. See the README for further thoughts, conclusions and recommendations. but basically seems like MT and grafana should use a format like the below (at least for input and output to the processing library, but ideally elsewhere too)

```
type Series struct {
  name string
  step uint32
  t0 uint32
  values []float64
}
```
it could possibly be extended with tags later, and an `isAbsent []bool` when we want to differentiate null and nan.

@woodsaj @torkelo what do you gguys think?

**Comment by DanCech** [comment]
Internally graphite-web does know the difference between `None` (python-ese for `null`) and `NaN`, there is no `NaN` value in json which is why both values are output as `null` (it also understands positive and negative infinity, and these are serialized into json as `1e9999` and `-1e9999` respectively).

**Comment by torkelo** [comment]
The problem with not having timestamp per value would be how to use it with non regular data. But if we only plan to support uniformly spaced data then I don't think that is going to be a problem. 

As long as we can with a custom json marshaller translate NaN to nulls then I think using regular float64  should be fine.

**Comment by torkelo** [comment]
forgot to say that I like the interface approach though. Would probably make things easier for MT/Grafana to share some foundation stuff but have different implementations for details.
