### ISSUE TITLE
log render requests and latencies 

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#678]
we need to be able to identify exact queries that are experiencing really poor query performance so that we can determine if the poor performance is due to the query trying to fetch too much data or some other bottleneck in the system

**Comment by replay** [comment]
I think one good way would be this:
1) define a slow query limit like `30s` or whatever
2) group the slow queries in some in-memory storage (which hopefully won't grow too large) and which can expire the data after X time

Then we need to figure out how to make that data accessible. Maybe MT could have some internal management endpoint which only listens on `localhost` and which can be queried for that data. This might be useful for other stuff too (e.g. posting cluster member IPs that it should connect to).

**Comment by Dieterbe** [comment]
if we do this in MT we could also track stats such as num series fetched and num points fetched, along with the query, so we can track that too.

**Comment by Dieterbe** [comment]
fixed via jaeger support
