### ISSUE TITLE
Add support to format=protobuf output to use with carbonapi

### ISSUE THREAD

**Issue by Nyoroon** [grafana/metrictank#706]
Hello!
It's possible to add support of protobuf format output?
https://github.com/go-graphite/carbonzipper/tree/master/carbonzipperpb3
Because carbonapi (alternative for graphite-{web,api} on go) supports only format=protobuf{,3} on "backend" servers :(
https://github.com/go-graphite/carbonapi

**Comment by deniszh** [comment]
Just my 5c: it's not some generic "protobuf3", it's a protocol from `carbonzipper` tool - https://github.com/go-graphite/carbonzipper which is also supported in https://github.com/lomik/go-carbon too.

**Comment by Dieterbe** [comment]
carbonapi has added support for the messagepack format used by graphite and metrictank.
https://github.com/go-graphite/carbonapi/commit/c5ba5726ea2161cf27573483fb2ca0f8131258ed
@Nyoroon does that work for you?

**Comment by Nyoroon** [comment]
@Dieterbe yeah, thanks
