### ISSUE TITLE
when multiple series get (back)filled with data that spans many chunks, metric-tank ingestion can block

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#76]
see https://github.com/raintank/raintank-metric/pull/67#issuecomment-162157211 and https://github.com/raintank/raintank-metric/pull/67#issuecomment-162752329

**Comment by woodsaj** [comment]
I think this is best addressed by simply imposing per org rate limits when accepting metrics.   Preventing users from bulkloading data into our SaaS platform is an expected limitation.
