### ISSUE TITLE
optimize index for heavy churn / rework index pruning

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#764]
index pruning.. aka the act of removing metricdefs from both the in-memory as well as cassandra index, after seeing no updates for a while (default 2 days). see https://github.com/grafana/metrictank/blob/master/docs/faq.md#does-it-work-well-with-transient-data-eg-new-metrics-constantly-appearing-and-other-metrics-becoming-inactive-such-as-those-from-docker-containers-
originally introduced in #319 

the reasons for this were/are : 
1) don't pollute the query editor with old inactive entries (e.g. containers) which makes the experience slow and frustrating. this is effectively no longer an issue thanks to https://github.com/grafana/grafana/issues/8055
2) constrain mem & disk usage of the index. I suspect ram usage is more important
3) speed of index operations

the downsides:
1) we drop entries from the index much sooner than the dropping of the data it corresponds to. so the data effectively becomes unreachable much sooner than what you'd think based on retention settings, which is confusing and misleading. 

prometheus v2 came up with an interesting approach to this. they effectively have a separate , complete index for each time period.  and I think their time periods are tied to their chunk sizes. based on the time range queried, you know which indices to query (and merge their results).
we could do something similar, but make the time slice configurable. for traditional, low-churn environments we could set the time slice to a year. for modern high-churn environments with container lifetimes of 10 minutes, we could set the timeslice to 10 minutes.
if we do this, it would make sense to make the timeslice config changeable over time,
(to accommodate customers moving from static to dynamic environments) and potentially even
have different indexes of data (for large scale customers that have both high-churn, and static metrics)

alternatively we could also switch from having the complete index (at least for the respective shards) in memory to only the 'hot' sections of the index in memory. though this needs a way to efficiently search and retrieve sections of the index from cassandra to keep the cache upto date (which could be based on pattern or tag search), and our current cassandra model is not well suited to that. it would also not solve the problem of the index being slow when browsing the metrics tree and there's a lot of nodes

**Comment by woodsaj** [comment]
grafana/grafana#8055 doesnt completely solve the pollution of the query editor with old series due to #714  
This is especially noticeable when you have template variables that are used on branch nodes. All branches will be shown, even for series that have not been seen for a long time

**Comment by Dieterbe** [comment]
step 1 #765

**Comment by DanCech** [comment]
A thought I had regarding this was that if we set an interval and for each interval write an index that includes just series that became stale during that interval, then we could perform historical lookups by combining the results from the current "working" index with results from a lookup into each of the "interval" indexes from start to now.  That would effectively locate every series that was not-stale at some point during the query period without the overhead of storing (and having to do lookups into) the complete index for each interval.
