### ISSUE TITLE
msgpack format

### ISSUE THREAD

**Issue by DanCech** [grafana/metrictank#768]
graphite-project/graphite-web#2123 adds support for using msgpack as a transport encoding for intra-cluster find and render requests which is substantially faster than pickle for large results.

It uses the same data structure as the pickle format, except that intervals are encoded as 2-element arrays rather than interval objects (which is actually how MT encodes them in its pickle output anyway), and the mime type `application/x-msgpack`

We should add support for `format=msgpack` so we can take advantage of the better performance.  For the most part this should just be a matter of using a msgpack encoder instead of pickle and sending the right content-type header, though we will also need to tweak the NaN handling to make sure they are properly encoded as `nil` values in the msgpack output.

**Comment by Dieterbe** [comment]
my only remark here is that msgp (currently existing format) vs msgpack is not clear.
 would it make sense to call it msgp-graphite instead? (minor point, i don't feel strongly about this. we could also just document it)

**Comment by DanCech** [comment]
no, graphite sends `format=msgpack`

**Comment by Dieterbe** [comment]
fixed by #789
