### ISSUE TITLE
reorderBuffer question

### ISSUE THREAD

**Issue by motyla** [grafana/metrictank#776]
Hi,

Can you ellaborate on how to configure the reorderBuffer?
What should be the relation between that number and the raw interval specified in the first defined retention.

From my tests it seems reorder work but the extra data it reorder is gone every "gc-interval".

**Comment by motyla** [comment]
I noticed my raw interval retention numchunks is set to 1.
I increase it to 2 and now running for a while with reorder and data is good.

Is that can explain the problem I had ?

**Comment by replay** [comment]
I don't think that's related to the reorder buffer, the data doesn't even go into the chunks defined by `numchunk` before it has been passed through the reorder buffer. numchunks should be set to `>=2`, so probably that was the problem

**Comment by motyla** [comment]
What about choosing the right number? With raw retention of 60s:7d seems a
reorder buffer of 20 works but 60 does not . While having the right
resource , RAM , I still can not  have a full reorder

**Comment by replay** [comment]
@motyla could you post your full `storage-schemas.conf` please?

**Comment by motyla** [comment]
Below my ```storage-schemas.conf``` file.
Most of the data is with the ones that have reorderBuffer definition

```
chunkspan = 2h
numchunks = 1

[kkk]
pattern = kkk
retentions = 1h:1y:24h:1,1d:3y:24h:1

[mmm]
pattern = ^mmm.
retentions = 5m:7d:12h:1,1h:1y:24h:1,1d:3y:24h:1

[vvv30m]
pattern = vvv_.*_30_min
retentions = 30m:30d:24h:1,1h:1y:24h:1,1d:3y:24h:1

[zzz]
pattern = ^zzz.
retentions = 1m:7d:2h:2,5m:30d:12h:1,1h:1y:24h:1,1d:3y:24h:1
reorderBuffer = 20

[my_queue]
pattern = ^application.production.from_db.technical_alerts.my_queue.per_code.
retentions = 15m:30d:24h:1,6h:1y:24h:1,1d:3y:24h:1

[application]
pattern = ^application.
retentions = 1m:1d:2h:1,5m:7d:12h:1,15m:30d:12h:1,6h:1y:24h:1,1d:3y:24h:1

[bbb]
pattern = ^aaa.production..*.ccc.
retentions = 1h:1y:24h:1,1d:3y:24h:1

[aaa]
pattern = ^aaa.
retentions = 1m:7d:2h:2,5m:30d:12h:1,1h:1y:24h:1,1d:3y:24h:1
reorderBuffer = 20

[metrictank]
pattern = ^metrictank.
retentions = 1s:35d:10min:2
reorderBuffer = 20

[default]
pattern = .*
retentions = 60s:1d:2h:1,1h:3d:24h:1
```

**Comment by replay** [comment]
thanks, and what is the exact problem that you are seeing?

**Comment by motyla** [comment]
yes . I still have data "too old" coming in.

**Comment by replay** [comment]
Ok, and are you sure that this data that's too old is not older than 20 datapoints?

**Comment by motyla** [comment]
No , but I assume that when putting 60 it will do a better reorder work (or the same if that's the case) and not make all data point gone after some interval

**Comment by replay** [comment]
how does it make data points disappear, is all the data that's older than a specific time completely gone or what happens?

**Comment by motyla** [comment]
after a restart of MT server when you look at some dashboard you see data coming in and then it goes to 0 and that's goes on and on at the same interval.

**Comment by replay** [comment]
after some internal discussion we have a theory what might be happening. could you try raising the `chunk-max-stale` and the `metric-max-stale` settings to some high value? it should be at least 1 chunk span + the length of the reorder buffer in time. this is only to verify that the bug is what we think it is.

**Comment by motyla** [comment]
Data goes back to last restart time.

Right now 20 does the work and data seems to be "enough" reordered , but
moving from this number seems to break it all.

**Comment by motyla** [comment]
@replay ,  metric-max-stale is already high , 6h.
I'm increasing the 1h chunk-max-stale to 6h and testing with reorderBuffer = 60

**Comment by shanson7** [comment]
I was also experiencing this issue and tracked it down to GC not accounting for the reorder buffer. I was able to reproduce on a local cluster and added a statement checking for this particular case and it does trigger. I'll try increasing `chunk-max-stale` with a frequent `gc-interval` and post updates.

**Comment by shanson7** [comment]
Increasing `chunk-max-stale` did indeed clear up the issue. It seems like any `aggmetric`s with data in the `rob` should not be eligible for cleanup OR during the `GC` check, the `rob` should be checked for stale data that might need to be flushed?

**Comment by shanson7** [comment]
Small clarification: increasing `chunk-max-stale` didn't do the trick, but increasing `gc-interval` did. This is because the code shortcircuits if no chunks exist and doesn't bother checking the stale age.

**Comment by motyla** [comment]
Yes , it did not do the trick for me also.

**Comment by Dieterbe** [comment]
this bug should now be fixed by merging the above PR
