### ISSUE TITLE
Remove tagged series from tree index

### ISSUE THREAD

**Issue by replay** [grafana/metrictank#798]
In order to be compatible with graphite, we need to remove the tagged series from the tree index. If there are series like `some.id.of.a.metric.1;tag1=value1` and `some.id.of.a.metric.2;tag2=value2` then a call to `/metrics/find?query=some.id.of.a.metric.*` should result in `[]`, while current it would result in the two metrics with tags. 
After that change, such tagged metrics will only be queriable via tag based queries.

The easiest way to do that should be to just not add tagged series into the tree index anymore.

It is important that index pruning still works for tagged series, even though they won't be in the tree index anymore.

**Comment by Dieterbe** [comment]
> call to /metrics/find?query=some.id.of.a.metric.* should result in []

why? wouldn't it be better to return `some.id.of.a.metric.1` and `some.id.of.a.metric.2` ?

**Comment by replay** [comment]
Because that's what graphite does. We discussed that on Slack about a week ago
