### ISSUE TITLE
Some functions modify series' in place, which effects names in other functions

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#829]
This is only an issue when the same target expression is used in a single request. For example:
`divideSeries(aliasByTags(seriesByTag('name=cpu.percent.idle','host=host1'),'host'),seriesByTag('name=cpu.percent.idle','host=host1')`

Note: the dividend is alias'd to the hostname, the divisor is not.

Graphite returns a name of:
`divideSeries(host1,cpu.percent.idle.g;host=host1)`

Metrictank returns:
`divideSeries(lxfsrvny1,lxfsrvny1)`

It seems the following expressions make in-place changes that effect all cached series:
[alias](https://github.com/grafana/metrictank/blob/master/expr/func_alias.go#L27)
[aliasByNode](https://github.com/grafana/metrictank/blob/master/expr/func_aliasbynode.go#L29)
[aliasSub](https://github.com/grafana/metrictank/blob/master/expr/func_aliassub.go#L33)

Additional Note: It seems that changing the single quotes to double quotes in the `seriesByTag` expression is enough to trick metrictank into fetching the series a second time and workaround that issue.

**Comment by Dieterbe** [comment]
sounds like a bug for sure. the cache should cache things with their canonical key/name, if that's even possible.

**Comment by shanson7** [comment]
I think that almost all functions do this now. But when in different targets, this isn't an issue. Seems like they need to be in the same target, like `group(alias(#A, 'test'), #A)`

**Comment by shanson7** [comment]
It seems that this one has gotten worse with the recent changes to include PNGroup. If 2 series from different targets are matched with PNGroup 0, they will share the same underlying fetched data.
