### ISSUE TITLE
Rollups can get lost if data stops being published for a long interval

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#834]
The issue we experienced was that for data that was sparsely populated, we saw the raw data but no rollups coming out. The issue seems to be that if a metric gets `GC`d, it's rollups aren't checked for whether they should persist. Basic rundown is something like:

1. Raw datapoint comes in and sits in `rob`
2. GC kicks off, rob is flushed, datapoint is put into both raw and hourly rollups
3. Next GC comes around data for raw is persisted to cassandra ([here](https://github.com/grafana/metrictank/blob/1d20a29/mdata/aggmetric.go#L593))
4. Some time passes (without new datapoints) and a few GC’s later, this `AggMetric` is eligible for GC. It gets deleted([here](https://github.com/grafana/metrictank/blob/1d20a29/mdata/aggmetric.go#L581)), but the hourly rollup was never persisted because a rollup *only* gets persisted due to data being added ([here](https://github.com/grafana/metrictank/blob/1d20a29/mdata/aggmetric.go#L515)).

So, any data waiting on that next datapoint to finalize the rollup is going to be lost in this case. The only workaround I could think of was raising the `metric-max-stale` setting, but with sparse data, I'm not sure how high to set that. Realistically, `metric-max-stale` should only need to be higher than my largest chunkSpan, which is `4h`.

**Comment by Dieterbe** [comment]
> but the hourly rollup was never persisted because a rollup only gets persisted due to data being added 

this is true but the link is incorrect. flush is triggered via callso to `a.addAggregators`

> Realistically, metric-max-stale should only need to be higher than my largest chunkSpan, which is 4h.

It sounds like this should be a general guideline + we should also close&flush aggregations when we GC out AggMetrics, otherwise the data gets lost.
in fact, why don't we add a config check to MT that makes sure that `metric-max-stale` is always larger than the highest chunkspan of any rollup ?
btw what's your `metric-max-stale` value anyway?

**Comment by shanson7** [comment]
A config check is one option. I was thinking that `GC` for the base aggmetric should call `GC` on it's children and only return true if all children do. This will also cause the children to persist if needed via the same logic as the base.

With this approach, `metric-max-stale` will be respected where it won't cause data loss, and sort of "bumped up" for longer chunk spans.

Our `metric-max-stale` is set to `6h`

**Comment by Dieterbe** [comment]
that's a good idea. though would be a bit more cpu intensive . i'm not a big fan of all these runtime checks though, if we instead could just assert that configuration is sane, that's simpler and more robust.

which led me to think that my idea would make more sense if we had per-rention max-stale settings, but you should check out #614 which is somewhat similar to your problem, in particular https://github.com/grafana/metrictank/issues/614#issuecomment-297068592 , we made some good thought progress there. basically we should switch to a different mechanism that applies equally for all metrics, and is based on how long data is retained in kafka.  i'm going to think a bit more about that, and we should probably resume this conversation there.

> Our metric-max-stale is set to 6h

when you observed the problem? you said your largest chunk was 4h so i suspect you had a shorter max-stale ?

**Comment by shanson7** [comment]
> would be a bit more cpu intensive . i'm not a big fan of all these runtime checks though, if we instead could just assert that configuration is sane, that's simpler and more robust.

I believe the base will need to minimally "flush" your children before returning true from `GC` so it seems easy enough to just make sure that the "flush" is sane by applying the exact same logic that is applied to the base. The only thing that would make this a bit more cpu intensive is that the "flush" could be un-sane and the base would stick around and be checked again next GC interval.

The benefit of this approach is that for different retention settings in the same MT, a small `metric-max-stale` will be as aggressive as is needed for each retention. If you set `metric-max-stale` to `2h` and 90% of your metrics have a max chunk span of `1h`, they can be cleaned up effectively, even if the other 10% have a max chunk span of `6h`. Those 10% will just stay until they can be cleaned up.

**Comment by Dieterbe** [comment]
never mind the cpu-intensive comment. it's irrelevant, what's paramount is correctness. please read through the linked thread and let me know what you think.

**Comment by shanson7** [comment]
I think that linked thread makes sense.

This issue wouldn't be solved until a `GC`d metric forces its children to be persisted. I still think that, even with all of those configurations in place, it makes sense (and would be the easiest solution, IMO) to make the base `AggMetric` "collectable" iff all of its children are.
