### ISSUE TITLE
Multi-series requests result in a lot of round-trips to peers

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#842]
When requesting data with multiple patterns (either by tags or not) a `find` is issued (serially) per target. This is to determine how many datapoints are going to be pulled back and what Metric Definitions are available, etc. After that, all of the requests are aligned and a single request is sent to fetch the data. This makes multi-target requests somewhat slower than making individual requests, as there are many back-and-forths to peers. 

A possible solution is to define a new request between peers that can `find` for multiple targets (similar to the request to get the data).

**Comment by Dieterbe** [comment]
looking at executePlan, seems like it should be fairly easy to parrallelize.
before we start work on this, i'ld like to see a bit more stats on how problematic this is exactly.
I can browse around in our jaeger traces a bit.
Do you have numbers or concrete observations you can share?

**Comment by Dieterbe** [comment]
We should look at some jaeger traces and see to which extent this contributes to request latency.
