### ISSUE TITLE
Support tag expressions in storage-{aggregations,schemas}.conf

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#845]
With tag support in metrictank, there may be different retention/aggregations based on tag values, not just names. For instance, longer retention for prod data.

**Comment by woodsaj** [comment]
I think this needs to be done in https://github.com/graphite-project/carbon first.  @DanCech

**Comment by DanCech** [comment]
You can do it today by using a pattern like `;tag=value`, or if you want to match multiple tags `;tagA=value(;.+)*;tagB=value`

**Comment by shanson7** [comment]
Ok, then MT would just need to pass `path` instead of `def.Name` here on these 2 lines:
https://github.com/grafana/metrictank/blob/36db80fb3c7d7859a0a0365fafce4cfefd805ab0/idx/memory/memory.go#L355

**Comment by shanson7** [comment]
With the caveat that this could definitely break existing patterns

**Comment by DanCech** [comment]
It'll also make it match the carbon behavior, so I think it's the right thing to do.

**Comment by Dieterbe** [comment]
> With the caveat that this could definitely break existing patterns (for tagged time-series) [in MT]

not a concern, since tagging in MT is still beta.
this change is probably something that should have gone with #806 (but in lieu of that, can be added now I think)
@replay any thoughts?

**Comment by replay** [comment]
That makes sense to me as @shanson7 described it, `mdata.MatchAgg()` would need to get `path` instead of `def.Name`
