### ISSUE TITLE
move tsdb-gw into metrictank

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#854]
right now we deploy tsdb-gw in front of metrictank. tsdb-gw has 5 routes it handles

-  POST /metrics/delete : gets proxied to metrictank
- POST /metrics :  publishes metrics to kafka
- GET /metrics/index.json: gets proxied  to metrictank
- GET /graphite/metrics/index.json: gets proxied to metrictank
- ANY /graphite/* : gets proxied to Graphite (but the graphite_url is often metrictank)

So all we really need to do is add support for `POST /metrics` to publish to kafka.

As we add new ingestion options, eg prometheus remote_write, opentsdb format, dd_agent, influxdb format etc..  it makes sense to just have these in metrictank as well.

Tsdb-gw currently also handles auth, but i dont think we need to include that in metrictank.  So for our deployments we would just use a small "auth-gw" service that authenticates against grafana.com

**Comment by Dieterbe** [comment]
my concern is this would make the scope of MT more muddy.
it already does so many different things. why does it also have to be the service ingesting data and publishing to kafka? I think having a dedicated service for that (tsdbgw) is an advantage, not a disadvantage.

**Comment by woodsaj** [comment]
I see your point.  I think the biggest win of having tsdb-gw separate is that your metrictank cluster can be unavailable due to all nodes replaying backlog, but users can still keep sending data.

What if we just moved tsdb-gw into the metrictank repo, but keep building it as a separate binary.
This will help ensure reduce code duplication (carbon ingestion) and ensure the binaries are using the same version of dependencies like raintank/schema.

**Comment by Dieterbe** [comment]
> What if we just moved tsdb-gw into the metrictank repo, but keep building it as a separate binary.

we could move "tsdb-gw with all non-metrictank-bits stripped out" into the MT repo.
to strip out: auth, graphite proxying.
basically what remains is a service that can take in all kinds of inputs, publishes into kafka, and does usage tracking
we still need a service that does graphite proxying though, as we've seen we cannot deploy mt-read as graphite_url across customers (it was problematic for a few, and we haven't diagnosed it yet)

i've generally always been a fan of keeping things together in the same repo for the kinds of benefits you mention.  last time we discussed this (probably more than 2y ago) you had a pretty strong opinion that different services should be split into separate repos but if your thinking on that is evolving more towards fewer repos, i'm all for that :)

**Comment by Dieterbe** [comment]
we decided to refactor tsdbgw in its own repo, but we can look at better library reuse later
