### ISSUE TITLE
MT cant start if it has no data in kafka and kafka-mdm-in-offset=auto

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#860]
https://github.com/grafana/metrictank/blob/master/input/kafkamdm/kafkamdm.go#L214

if we get an error trying to get an offset based on a duration, we should fall back to setting offset to sarama.Oldest.

**Comment by woodsaj** [comment]
why?  this is literally a 1 line change to fix.

**Comment by Dieterbe** [comment]
because this fallback makes sense when the duration offset was the output of an auto value in the entrypoint, but not so much if someone explicitly configured MT to consume a specific time range. (we don't do that however, so it's probably ok)

**Comment by woodsaj** [comment]
I think that is just a documentation issue.  
```
If offset is a duration and kafka does not have any messages that are older then the duration, then MT will just consume from the oldest offset.
```

**Comment by Dieterbe** [comment]
yeah i think that will do (not perfect, but good enough, especially considering setting explicit time ranges seems uncommon)
