### ISSUE TITLE
getOffset.py can set a negative offset

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#863]
```
try:
  retention=int(data.get('config', {}).get('retention.ms', 0)) <-----
  segmentSize=int(data.get('config', {}).get('segment.ms', 1800000))
except:
  default()

if retention == 0:
  default()

# oldest we can safetly consume from in minutes
oldest = (retention - segmentSize)/(1000 * 60)

print "%dm" % oldest

```

the marked line means the oldest formula can become:
```
>>> oldest = (0 - 1800000)/(1000 * 60)
>>> print "%dm" % oldest
-30m
```

of course the `retention.ms` key should always be in the config, and never be set to the default of 0,
which raises the question, why do even allow it to be unset and set to 0 in that case?
better to call `default()` in that case I think.

**Comment by woodsaj** [comment]
we already call `default()` if retention=0
```
if retention == 0:
  default()
```

**Comment by Dieterbe** [comment]
oops.
