### ISSUE TITLE
Better support for ephemeral time-series / "series churn"

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#865]
With the increase in popularity of systems like kubernetes (and other distributed systems like Hbase) more and more time-series are short-lived. 

In the example of kubernetes, "pod id" might be a useful tag in the short-term. After that pod goes away and is replaced with a new id, the old time-series becomes stale and is only useful as an aggregation (e.g. `sumSeries(seriesByTag('name=some.kube.metric'))`).  Currently, the only method of cleaning these up is the global `max-stale`, which filters at start up from the entire history of index data. After that, a query like  `sumSeries(seriesByTag('name=some.kube.metric'))` starts to falter if run for a time period greater than `max-stale`. 

Some ideas that I've been kicking around for this:

1. Support aggregating away a tag over time. While this can be handled outside of metrictank (via pre-aggregation), it needs to be explicitly opted into at query time (i.e. querying for the aggregated series, rather than trying to accumulate the individual components). This seems a little messy though.

2. Make `max-stale` pattern based (similar to aggs and retentions). That means that for ephemeral data you could forget about it sooner and simply require pre-aggregations for historical queries.

3. Treat index data more like the chunk data (i.e. keep a short period of time in memory, cache based on requests and on cache miss check cassandra). This seems like "The ultimate" solution to me, but I'm not sure how efficiently we could resolve some of the query expressions from cassandra.

**Comment by shalstea** [comment]
We could identify on our side and let you know that a particular namespace is ephemeral and therefore be managed in a special way.  All data within the namespace would be treated the same.

**Comment by Dieterbe** [comment]
>  Currently, the only method of cleaning these up is the global max-stale, which filters at start up from the entire history of index data.

note that we have a max-stale in 3 places. I presume you mean the one for cassandra-idx.
It does two things: filter at start up (as you say), and also prune the memory index at runtime every `prune-interval`

> After that, a query like sumSeries(seriesByTag('name=some.kube.metric')) starts to falter if run for a time period greater than max-stale.

can you be more specific, are you talking about `to - from> max-stale` or `now()-from >max-stale` what's the problem exactly?

note we have an existing ticket already:
"optimize index for heavy churn / rework index pruning" #764

but I think you're touching on a different aspect

**Comment by shanson7** [comment]
> what's the problem exactly?

Basically, if the series are pruned from the index, the data is inaccessible. Anytime a query has a `from` > `now() - max-stale` the results are effectively incomplete for any query that matches stale series that were pruned.

#764 actually seems very similar.
