### ISSUE TITLE
offset "auto" does not work as expected

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#866]
background: sometimes we get errors like `[Sarama] 2018/03/08 14:24:39 consumer/topic/36 shutting down because kafka server: The requested offset is outside the range of offsets maintained by the server for the given topic/partition.` shortly after startup of MT when offset=oldest
we have theorized that this happens when MT has started to consume the oldest chunk and then kafka deletes it while still consuming.  Not a huge deal, because with auto-restart when this happens and usually the 2nd time (or 3rd time) the backfill is able to "outrun" kafka's cleanup.

now, we recently were tired of it, so we came up with what we thought was the solution: we have segment size of a half hour, and offset=auto causes MT to consume from retention minus segment size, e.g. 7.7-0.5=7.2hr in our current deployments

however we're still seeing the same errors.
I think it may be due to kafka returning inaccurate estimates for the offset.

our sarama is currently at 1.10.1
we run kafka 0.10.1 in us-east and 0.10.2 in us-west. we plan to upgrade us-east imminently to the latter.

https://github.com/Shopify/sarama/wiki/Frequently-Asked-Questions#how-do-i-fetch-an-offset-for-a-specific-timestamp says:

> Starting in Sarama v1.11.0, this method will automatically use Kafka's new precise timestamp lookup if your Kafka version (as provided by Config.Version) is at least 0.10.1. Otherwise, the method will fall back to the old API which returns only a very approximate value.

irrespective of our plans to switch to confluent, an upgrade of sarama looks trivial. that might just make this work
see https://github.com/Shopify/sarama/blob/master/CHANGELOG.md

the first paragraph of https://www.confluent.io/blog/announcing-apache-kafka-0-10-1-0/ also confirms this

otherwise we're going to have to dig deeper into the getoffset api's

**Comment by woodsaj** [comment]
I think we can also address this by adding a small "buffer" when calculating the offset duration to use
https://github.com/grafana/metrictank/blob/master/scripts/k8s/getOffset.py#L46

right now, we request for exactly `retention - segmentSize` 
It seems likely that the only messages that are older then this value are messages in the oldest segment.
if we were to request (retention - (segmentSize * 1.1)) then we would ensure that the segment that matches our request offset duration is the second last segment.

**Comment by woodsaj** [comment]
This is still hurting us in production. I am going to update the code for calculating the offset to use
```
`retention.ms - (segment.ms + 60000)`   This 1min buffer should ensure that we dont end up with an offset that is in the last segment.

**Comment by replay** [comment]
Related: when using `mt-kafka-mdm-sniff-out-of-order` in production environments i usually get that too and need to set some env variables to override it

**Comment by woodsaj** [comment]
this still keeps popping up, even when using kafka 2.0.0 which should be returning the offset id at the timestamp we request, rather then returning the offset of the first message in the segment that was created before the requested timestamp.

I think the next step is to add some more logging to MT so that we log the oldest offset along with the offset that kafka returns for the timestamp we provide.  This will help us get a clearer picture of what is going on

**Comment by Dieterbe** [comment]
Sgtm
