### ISSUE TITLE
cassandra-idx-max-stale configurable via patterns

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#868]
one of our favorite HM customers is asking for MT_CASSANDRA_IDX_MAX_STALE not to be a global value, but rather to be able to control it with patterns (prefix is enough, doesn't need to be regex) so they can use more aggressive values (15d) for high cardinality data, and longer values (60d) for other data.

this seems like a useful feature request, and should be fairly easy to add to our pruning system.
@woodsaj any thoughts?

**Comment by woodsaj** [comment]
Seems like a good feature.  I guess the best way to approach it would be to have an 'index policy' which uses a similar format to the retention policy
