### ISSUE TITLE
remove deprecated "safety feature" in CassandraIdx

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#877]
in https://github.com/grafana/metrictank/pull/574 we introduced these lines:
```
       // This is just a safety precaution to prevent corrupt index entries.
       // This ensures that the index entry always contains the correct metricDefinition data.
       if inMemory {
               archive.MetricDefinition = *schema.MetricDefinitionFromMetricData(data)
               archive.MetricDefinition.Partition = partition
       }
```

1) as per https://github.com/grafana/metrictank/pull/574#discussion_r107259941
this was only temporary, and can be removed (note that the problem we saw originally was on the Nodes attribute of the MetricDefinition which we no longer use)

2) it doesn't work as you would expect because memoryIdx.AddOrUpdate()
returns a copy of the Archive (both in the case of new->added, and update scenario)
so any changes won't be seen by the memory index
see https://play.golang.org/p/mF5hFkVD8_C
the exception being the tags slice, if you don't update the slice you have access to the underlying array and can change it:
https://play.golang.org/p/y4EqMLAaFxg

so the only protection that code gives is if somehow the tags within the backing array get altered.
(not when the tags slice gets overridden by a slice with different array, or a capacity-extended slice)
we have no reason to believe we have such a bug, making this code removeable

on the other hand, if we have precisely such a tag-array bug, this would expose it.  we should do a sanity check of the index code before removing this.

**Comment by Dieterbe** [comment]
heh i totally missed the `c.MemoryIdx.Update(archive)` call after this code

**Comment by woodsaj** [comment]
lets get rid of this.    We definitely dont need it anymore.

**Comment by Dieterbe** [comment]
i'll do this as part of #876

**Comment by Dieterbe** [comment]
merged
