### ISSUE TITLE
Dual-license for smaller parts of metrictank

### ISSUE THREAD

**Issue by Civil** [grafana/metrictank#878]
I wanted to use parts of metrictank (in my example - https://github.com/grafana/metrictank/tree/master/consolidation ) which are insignificant but might help other projects, but I can't because the whole project is AGPL-3 licensed.

Can you please switch to dual license for those libraries?

Anything more permissive (LGPL-3, or ideally Apache2/BSD/MIT) will be ok.

And I'm talking not about whole project but only about small parts of it which might be reused or forked and reused.

**Comment by Dieterbe** [comment]
ok, it's it just a matter of dropping the license in the directory of the library?

**Comment by Civil** [comment]
That should be enough for me to be able to pick it up from you :)

I think formally you might need to get an approval from all contributors there (or whoever owns the code if there is an CLA)

**Comment by Civil** [comment]
From my understanding to relicense (or dual-license) consolidation part you will need:
1. Permission of the following people: @Spellchaser @woodsaj 
2. Also add license for schema.v1 (I'll myself won't use it, but to be completely correct you need to have compatible license there too)
3. Also dual-license https://github.com/grafana/metrictank/tree/master/batch (authors are the same there).

It seems that it should be enough.
