### ISSUE TITLE
debian package are not installable (tried on jessie and stretch)

### ISSUE THREAD

**Issue by beorn-** [grafana/metrictank#887]
It triggers the "version number does not start with digit" error

the version is a hash which is forbidden by debian policy, the version in the debian/control file has to be in the form : 0.8.3-1

where 0.8.3 is the version and -1 is the build revision

my opinion is that you could use latest tagged version and increment an int for the revision it's a common practice

**Comment by woodsaj** [comment]
I dont think this is a problem with our build scripts. Though we only use the docker images these days, in the past we have used the deb packages.

My guess is that there was problem during a build and the `git describe` only returned the commit id and not the tag information.

**Comment by woodsaj** [comment]
confirmed, i found broken packages in the repo from 6months ago.
eg `metrictank_f2df73a_amd64.deb`

**Comment by woodsaj** [comment]
ok, i have deleted the bad packages from the repo. Should be all good now.
