### ISSUE TITLE
summarize function returning incorrect results

### ISSUE THREAD

**Issue by woodsaj** [grafana/metrictank#903]
If i send a request for 3months of data, summarized into 30day averages
```
target: summarize(metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32, '30day', 'avg', false)
from: 1517414400
until: 1525104059
format: json
```

i get back 
```
[  
  {  
    "target":"summarize(metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32, \"30day\", \"avg\")",
    "tags":{  
      "name":"metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32",
      "summarize":"30day",
      "summarizeFunction":"avg"
    },
    "datapoints":[  
      [  
        66.50059255122777,
        1516320000
      ]
    ]
  }
]
```
As well as there being only 1 datapoint returned instead of the expected 3, the timestamp of the returned datapoint is for 12days before the requested From.

If a add a keepLastValue() function to the query, forcing the query to be handed off to Graphite, i get the correct results.

This looks to be a fairly recent bug, as a number of queries that were working last month are not working today.

**Comment by Dieterbe** [comment]
> This looks to be a fairly recent bug, as a number of queries that were working last month are not working today.

native `summarize()` support in MT was merged on march 8 via #837, likely there is a bug in it

**Comment by shanson7** [comment]
This line is probably also an issue: https://github.com/grafana/metrictank/blob/master/expr/func_summarize.go#L36

**Comment by shanson7** [comment]
Should summarize be resetting the consolidation function?
https://github.com/grafana/metrictank/blob/master/expr/func_summarize.go#L36

Seems like the python version doesn't do this.

**Comment by Dieterbe** [comment]
> Should summarize be resetting the consolidation function?
https://github.com/grafana/metrictank/blob/master/expr/func_summarize.go#L36
> Seems like the python version doesn't do this.

yes, see https://github.com/grafana/metrictank/blob/master/expr/NOTES#L73

**Comment by Dieterbe** [comment]
```
mt-index-cat --prefix metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32 cass -timeout 30s -keyspace \$MT_CASSANDRA_IDX_KEYSPACE -hosts \$MT_CASSANDRA_IDX_HOSTS '{{.Id}} {{.OrgId}} {{.Name}} {{.Interval}} {{.LastUpdate}} {{.Partition}}\n'"
1.2c908409650e626115cf8bf5c74331a0 1 metrictank.aggstats.1-mtqa.tank.metrics_active.gauge32 10 1528101600 4
```
