### ISSUE TITLE
stats library very slow to reconnect when graphite endpoint goes down

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#908]
for Mt's internal stats, if the carbon endpoint goes down and back up, it seems to take 15-20 minutes for MT to notice. so there's a long gap of no stats which finally will get filled in, but it takes too long

**Comment by woodsaj** [comment]
I think this can be easily solved by calling `conn.SetWriteDeadline(time.Now().Add(time.Second * 10))` before calling conn.Write() https://github.com/grafana/metrictank/blob/master/stats/out_graphite.go#L109
