### ISSUE TITLE
more accurate consolidation of NaN's

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#91]
re 79bdabd158e28c719c6913d05f9d97f433ed8f85

i've always disagreed with how graphite handles NaN's in runtime consolidation.
imagine a series that measures throughput with points 10, 12, 11, null, null, 10, 11, 12, 10
let's say you need to aggregate every 3 points with sum. this would return 33, 10, 33.
this will visually look like a drop in throughput, and if you have alerting that looks for throughput drops, it would trigger here.
IMHO `null+null+10=null`. i.e. if a term or a factor in an equation is null, the result should be null imho.
for storage aggregation they handle this fairly elegantly with xfilesfactor or whatever it's called, but for runtime consolidation it should either introduce a similar xfilesfactor or be stricter about nulls.

for some functions like avg, a missing value amongst several valid values is usually not a big deal, but the likeliness of it becoming a big deal increases with the amount of nulls which we don't account for, so i rather be safe for now.

**Comment by woodsaj** [comment]
> this will visually look like a drop in throughput, and if you have alerting that looks for throughput drops, it would trigger here.

but if the nulls are due to the thing you are polling being offline preventing it from being polled, then it would be a drop in throughput and an alert should be triggered.

The solution this type of issue though is to just use counters instead of gauges, but i agree with your point that there needs to be better control over how nulls are handled with consolidation.

There is no one approach that is going to work for everyone, so we need to give the user the ability to specify what they want. I think the only way to solve this is by extending the consolidateBy function to take an additional xfilesfactor argument. This would require a change in upstream graphite.

For now i think having consistent behavior with graphite is more important then doing the write thing.

**Comment by Dieterbe** [comment]
> but if the nulls are due to the thing you are polling being offline preventing it from being polled (..)

what if they're not? there are other reasons, like a crash/restart of a monitoring agent. this mangling of null (which means unknown) with "known as zero" can result in false alerts. better to treat null data separately

so @woodsaj until we have an xfilesfactor argument, what in your opinion is wrong with the suggested approach of evaluating an expression to null as soon as any variable in the expression is null?

**Comment by woodsaj** [comment]
> what if they're not? 

That is my point, there is no 1 way to deal with nulls that fits every need.

>  what in your opinion is wrong with the suggested approach of evaluating an expression to null as soon as any variable in the expression is null

It is not how graphite consolidates points.   Users expect a graphite TSDB to behave like a graphite TSDB.

If anything we need to add an xfilesFactor to our rollups.

**Comment by Dieterbe** [comment]
>  Users expect a graphite TSDB to behave like a graphite TSDB

i generally agree, especially around input/output format and the query api.
but i think graphite has some obvious flaws and inconsistencies around rollups and consolidation, that still surprises and/or annoys people (see also my [blog draft](https://github.com/Dieterbe/dieterblog/blob/master/content/post/graphite-statsd-gotchas.md)) and if we can change logic for the better, I think we should. we already do, like chosing the same aggregation function for runtime consolidation and rollups, graphite notoriously can easily use 2 different functions, one or both of which misconfigured, leading to nonsensical data.  I like that we can do better here.

> That is my point, there is no 1 way to deal with nulls that fits every need.

Well with your suggestion you can get woken up due to an innoculous monitoring glitch that introduces nulls, because it gets treated as a definite drop in throughput.
My view is that this is detrimental and should be avoided at all costs. Not only cause of the needless alert, but also because it's harder to tell from the data what's going on.
I rather restrict the throughput rule to only working with known data, and use a separate rule to tell whether a service is up or down or not, and separate logic to send warnings in case of issues with the monitoring system (but not criticals) and if all monitoring fails, only critical when it gets sufficiently bad that we can't monitor any KPI's.  (i.e. if the monitoring data is lacking to such an extent we don't have visibility into any of the key health indicators of our product).  I think this fits all needs and use cases, it's just that it is difficult to implement like this with alerting software.

However:
1) my ideal is probably too far out (not sure even bosun can do this, though it probably gets close, with its dependency system and whatnot)
2) my issue with your approach seems unlikely to be a real concern because most monitoring data will come out of the realtime highest precision archive.  you may only hit rolled up data for alerts in cases where you query a long series of time to compare against historical data.
3) still not a fan of what could visually look like drops even when they aren't, caused by null as zero processing. but the issue is not big enough to warrant more immediate attention. people should use counters as you say, or histograms and i haven't seen anyone obsess over this the way i do which is a good signal i'm probably taking this too far.

so i arrive at the same conclusion, but i still felt it useful to write down my thoughts.


> I think the only way to solve this is by extending the consolidateBy function to take an additional xfilesfactor argument.

if we add support of an xfilesFactor to our rollups on a per-series level, we could just use the same xfilesfactor in our runtime consolidation function.  it seems very likely that a well-chosen xff for rollups will also be a great choice for runtime consolidation, because the data is the same. 
setting xff for rollups will probably remove all need to specify xff as an arg to consolidateBy.
we can also use sensible xff default values (for both rollups and runtime consolidation), like maybe 0.8 for sum and 0.5 for avg because clearly avg is less sensitive to nulls than sum. i think these make both sense for rollups and runtime.  I think it's going to be really neat how we can make runtime consolidation be the very natural extension of rollups, not just in terms of which function to use (which we already do), but also in terms of xff.

> If anything we need to add an xfilesFactor to our rollups.

you're right. this seems pretty important. MT already has per-series step awareness, so we should just consult that when we complete an aggregation span, to see if we collected sufficient points or not.
