### ISSUE TITLE
which characters are valid in tag values

### ISSUE THREAD

**Issue by cyang16** [grafana/metrictank#941]
Metrictank is compatible with graphite query interface. Since graphite does not documents which characters are valid in tag values. 
Please advise / document which characters will be valid for long term supporting in metrictank.

Is white space a well supported in the tag value?

It is good to have a document about it for long term supporting (as a standard), or at least a guideline.
I believe many special characters is well supported now, but it is not guaranteed they will be well supported in the future, like special characters used in query syntax and regex could mess up easily.

**Comment by Dieterbe** [comment]
Hi @cyang16 
we are working on this, see #1216
