### ISSUE TITLE
flag.Duration and flag.DurationVar parse errors not handled properly

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#944]
from a customer

> we enabled index pruning (we were using 30d and that silently failed to parse as golang durations don’t support d unlike the other durations in MT)

flag.Duration and flag.DurationVar have no way to validate input, they just return 0
in some of these flags 0 is a valid input value, so in those cases we should use another input type..
where we do use the flag.Duration* types, we should validate that they are !=0

maybe for consistency we should use our own parsing everywhere

**Comment by Dieterbe** [comment]
> flag.Duration and flag.DurationVar have no way to validate input

incorrect. though the api is kindof weird.
the durationvars method return the error, and you can have the flagset exit or panic when it happens.
see https://play.golang.org/p/qhoOi_e2r79
need to do some more research if we can make it work with globalconf.
related: https://github.com/rakyll/globalconf/issues/21

**Comment by Dieterbe** [comment]
I think the simplest and clearest approach is to just use stringvars everywhere and do an explicit parse step  where we can easily check the error and fatal out if needed

**Comment by replay** [comment]
I guess now that it's merged we can just reuse `ConvertTimeout()` (https://github.com/grafana/metrictank/blob/master/store/cassandra/cassandra.go#L114), although we might want to move it somewhere else if it becomes an often reused utility function

**Comment by Dieterbe** [comment]
while we're at it: https://github.com/grafana/metrictank/pull/485#discussion_r97743784

**Comment by deniszh** [comment]
I did same '30d' mistake too, maybe it should be mentioned in example config?

**Comment by deniszh** [comment]
Or let me know how can I help with fixing that issue ( I mean which exact help is wanted)

**Comment by Dieterbe** [comment]
fixed by #1141
