### ISSUE TITLE
Chunk Cache Corruption causes request failures

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#967]
Related to #875 (which was a symptom of this problem for us).

Sometimes a chunk cache search results in `from > until`. Cassandra store then fails the whole query and the chunk cache needs to be cleared to get things working. I added a bit of debugging / detection to our production instances (as well as recovery steps). 

It seems that this occurs when the forward search has to stop and the backward search finds a `prev` that is *earlier* than the last found in the forward search. I dump the chunk state when this happens and end up ([see here](https://gist.github.com/shanson7/76e2a959fe4491969c550dcdba8e1471))

Basically the problem is in this section
```
2018/07/19 15:56:46 [W] CCacheMetric debugMetric: ts 1531245600; prev 1531242000; next 1531249200
2018/07/19 15:56:46 [W] CCacheMetric debugMetric: ts 1531249200; prev 1531245600; next 1531252800
2018/07/19 15:56:46 [W] CCacheMetric debugMetric: ts 1531252800; prev 1531249200; next 0             // Forward search would stop here!
2018/07/19 15:56:46 [W] CCacheMetric debugMetric: ts 1531350000; prev 1531249200; next 1531353600    // `prev` here points to the one *before* our until!!
2018/07/19 15:56:46 [W] CCacheMetric debugMetric: ts 1531353600; prev 1531350000; next 1531357200
```

I added code that just ditches the result of the chunk cache in this case and adds it back to the chunk cache after it gets a result from cassandra. Seems to work well enough in practice.

**Comment by shanson7** [comment]
Quick and dirty workaround [here](https://github.com/bloomberg/metrictank/compare/4c22f984b52719501ca5657bc3bfcb5a5642efd2...43944fe90cb01278ec0e50e5fac1ea488c980d07)

**Comment by Dieterbe** [comment]
I consider this sufficiently worked around now, via #986 we now don't fail the request and just refetch from storage.
that PR introduced new warning logs, which when seen, we can open a new ticket for.
