### ISSUE TITLE
Metrictank Peer sometimes returns http code 4608

### ISSUE THREAD

**Issue by shanson7** [grafana/metrictank#984]
I'm not entirely sure why but when cassandra fetches time out, the /getdata request has HTTP status code 4608, which obviously confuses things "cluster node unavailable" is returned

`[Macaron] 2018-08-08 23:40:26: Completed /getdata 4608  in 7.662508408s`

It seems like it stems from an invalid code in WrapError. A reasonable workaround while tracing the underlying cause would be to replace any code >599 (max HTTP status code) with a 500, since *something* happened.

**Comment by Dieterbe** [comment]
> which obviously confuses things "cluster node unavailable" is returned

not sure what this sentence means. the 4608 triggers  "cluster node unavailable" ?

**Comment by shanson7** [comment]
Yes. Since 4608 is not a valid HTTP status code, I believe an error is returned to the `Post` rather than an HTTP Response with a non-200 status code. So, the error that makes it back to users is "Cluster node unavailable"

**Comment by Dieterbe** [comment]
you're likely right. because none of the http status codes (200 or otherwises) causes Do() to error if the status code is valid. only protocol errors and such trigger errors.

BTW, "cluster node unavailable" could be slightly better phrased. maybe "error trying to talk to peer" is better
