### ISSUE TITLE
spread cassandra write load over time

### ISSUE THREAD

**Issue by Dieterbe** [grafana/metrictank#99]
currently write load spikes every chunkSpan because we try to save all chunks whenever they are ready to be saved.

we should investigate whether this has any negative impact on cassandra read performance and/or if we can solve this with cassandra tuning.

if not, we can change MT to spread the write load over time.

**Comment by woodsaj** [comment]
With https://github.com/raintank/raintank-metric/pull/95 writes are already spread based on the speed at which cassandra will process writes.  The write load being sent to cassandra can be tuned by adjusting cassandra-write-concurrency option.  If set to 1, then a single goroutine will sequentially read from the writeQueue and send to cassandra.

The default configuration of Cassandra should already prevent a high rate of writes from preventing reads and vice-versa.  Though we probably should verify this ourselves.

**Comment by Dieterbe** [comment]
the mere act of adding all chunks to the write queue at once instead of spread out in time is problematic though: 
it makes tuning the write queue hard (#125) and also triggers cpu spikes on the NMT machines (#105)
